-- 1: Patient has two different primary diagnoses between inpatient_services and inpatient_admissions, two records created with condition_status of primary. Id is PERSON_ID
UNION SELECT 1 AS id, 'Patient has two different primary diagnoses between inpatient_services and inpatient_admissions, two records created with condition_status of primary. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '1' AND condition_concept_id = '4008576' AND condition_type_concept_id = '38000183') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 1 AS id, 'Patient has two different primary diagnoses between inpatient_services and inpatient_admissions, two records created with condition_status of primary. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '1' AND condition_concept_id = '198337' AND condition_type_concept_id = '38000199') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 3: Patient has the same diagnosis code in outpatient_services and facility_header. Id is PERSON_ID
UNION SELECT 3 AS id, 'Patient has the same diagnosis code in outpatient_services and facility_header. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '3' AND condition_concept_id = '433706' AND condition_type_concept_id = '38000215') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 3 AS id, 'Patient has the same diagnosis code in outpatient_services and facility_header. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '3' AND condition_concept_id = '433706' AND condition_type_concept_id = '38000238') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 5: Patient has diagnosis in dx4 field in inpatient_services. Id is PERSON_ID
UNION SELECT 5 AS id, 'Patient has diagnosis in dx4 field in inpatient_services. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '5' AND condition_concept_id = '195587' AND condition_type_concept_id = '38000187') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 7: Patient has diagnosis in dx9 field in facility_header. Id is PERSON_ID
UNION SELECT 7 AS id, 'Patient has diagnosis in dx9 field in facility_header. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '7' AND condition_concept_id = '24970' AND condition_type_concept_id = '38000208') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 9: Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created. Id is PERSON_ID
UNION SELECT 9 AS id, 'Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created. Id is PERSON_ID' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '9' AND visit_concept_id = '9203') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 9 AS id, 'Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '9' AND condition_concept_id = '195587' AND condition_type_concept_id = '38000184') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 9 AS id, 'Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '9' AND condition_concept_id = '24970' AND condition_type_concept_id = '38000183') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 11: Patient has diagnosis in a dx field that has domain=procedure, condition record moved to procedure_occurrence. Id is PERSON_ID
UNION SELECT 11 AS id, 'Patient has diagnosis in a dx field that has domain=procedure, condition record moved to procedure_occurrence. Id is PERSON_ID' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '11' AND procedure_concept_id = '4047347' AND procedure_type_concept_id = '38000183') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 11 AS id, 'Patient has diagnosis in a dx field that has domain=procedure, condition record moved to procedure_occurrence. Id is PERSON_ID' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '11' AND procedure_concept_id = '46272569' AND procedure_type_concept_id = '38000183') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 13: Patient has diagnosis in a dx field that has domain=observation, condition record moved to observation. Id is PERSON_ID
UNION SELECT 13 AS id, 'Patient has diagnosis in a dx field that has domain=observation, condition record moved to observation. Id is PERSON_ID' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation WHERE person_id = '13' AND observation_concept_id = '4117957' AND observation_type_concept_id = '38000183') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 15: Patient has diagnosis in a dx field that has domain=measurement, condition record moved to measurement. Id is PERSON_ID
UNION SELECT 15 AS id, 'Patient has diagnosis in a dx field that has domain=measurement, condition record moved to measurement. Id is PERSON_ID' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '15' AND measurement_concept_id = '4034850' AND measurement_type_concept_id = '38000183') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 17: Patient has icd10 diagnosis in a dx field with dxver=0, condition record created with icd10 mapped to snomed. Id is PERSON_ID
UNION SELECT 17 AS id, 'Patient has icd10 diagnosis in a dx field with dxver=0, condition record created with icd10 mapped to snomed. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '17' AND condition_concept_id = '438021' AND condition_type_concept_id = '38000184') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 19: patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, observation record created with icd10cm mapped to snomed. Id is PERSON_ID
UNION SELECT 19 AS id, 'patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, observation record created with icd10cm mapped to snomed. Id is PERSON_ID' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation WHERE person_id = '19' AND observation_concept_id = '4155106' AND observation_type_concept_id = '38000184') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 19 AS id, 'patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, observation record created with icd10cm mapped to snomed. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '19' AND condition_concept_id = '46270117') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 21: Patient has icd10 diagnosis after 10/1/2015 in a dx field with dxver=null, condition record created with icd10 mapped to snomed. Id is PERSON_ID
UNION SELECT 21 AS id, 'Patient has icd10 diagnosis after 10/1/2015 in a dx field with dxver=null, condition record created with icd10 mapped to snomed. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '21' AND condition_concept_id = '438021' AND condition_type_concept_id = '38000184' AND condition_source_concept_id = '45602528') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 23: Patient has icd9 diagnosis before 10/1/2015 in a dx field with dxver=null, used ICD9. Id is PERSON_ID
UNION SELECT 23 AS id, 'Patient has icd9 diagnosis before 10/1/2015 in a dx field with dxver=null, used ICD9. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '23' AND condition_concept_id = '46270117' AND condition_type_concept_id = '38000184' AND condition_source_concept_id = '44821630') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 25: Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID
UNION SELECT 25 AS id, 'Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '25' AND condition_concept_id = '195587' AND condition_start_date = '2012-07-01' AND condition_type_concept_id = '38000187') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 25 AS id, 'Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '25' AND condition_concept_id = '195587' AND condition_start_date = '2012-08-02' AND condition_type_concept_id = '38000187') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 27: HRA mapped to condition/drug the END_DATE is NULL. Id is PERSON_ID
UNION SELECT 27 AS id, 'HRA mapped to condition/drug the END_DATE is NULL. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '27' AND condition_concept_id = '134736' AND condition_start_date = '2012-03-12' AND condition_end_date IS NULL AND condition_status_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 29: Patient has 1 in CC_ASTHMA column, condition_source_value=Self-reported Asthma. Id is PERSON_ID
UNION SELECT 29 AS id, 'Patient has 1 in CC_ASTHMA column, condition_source_value=Self-reported Asthma. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_occurrence WHERE person_id = '29' AND condition_concept_id = '317009' AND condition_start_date = '2012-09-13' AND condition_source_value = 'CC_ASTHMA' AND condition_status_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 31: Patient condition_concept_id of 0, no condition_era record created. Id is PERSON_ID.
UNION SELECT 31 AS id, 'Patient condition_concept_id of 0, no condition_era record created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_era WHERE person_id = '31') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 33: Two records with same condition_concept_id are less than 30 days apart, one condition_era record created. Id is PERSON_ID.
UNION SELECT 33 AS id, 'Two records with same condition_concept_id are less than 30 days apart, one condition_era record created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_era WHERE person_id = '33' AND condition_era_start_date = '2012-07-01' AND condition_era_end_date = '2012-07-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 35: Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.
UNION SELECT 35 AS id, 'Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_era WHERE person_id = '35' AND condition_era_start_date = '2012-07-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 35 AS id, 'Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.condition_era WHERE person_id = '35' AND condition_era_start_date = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 37: Date of death visit end date. Id is PERSON_ID.
UNION SELECT 37 AS id, 'Date of death visit end date. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.death WHERE person_id = '37' AND death_date = '2013-01-09') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 39: ICD10 Death and Death Type Correct. Id is PERSON_ID.
UNION SELECT 39 AS id, 'ICD10 Death and Death Type Correct. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.death WHERE person_id = '39' AND death_type_concept_id = '38003567') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 41: ICD9 Death and Death Type Correct. Id is PERSON_ID.
UNION SELECT 41 AS id, 'ICD9 Death and Death Type Correct. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.death WHERE person_id = '41' AND death_type_concept_id = '38003567') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 43: Discharge Status and Death Type Correct. Id is PERSON_ID.
UNION SELECT 43 AS id, 'Discharge Status and Death Type Correct. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.death WHERE person_id = '43' AND death_type_concept_id = '38003566') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 45: Death by ICD9 and Death by Discharge, Keep the Discharge. Id is PERSON_ID.
UNION SELECT 45 AS id, 'Death by ICD9 and Death by Discharge, Keep the Discharge. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.death WHERE person_id = '45' AND death_type_concept_id = '38003566') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 47: Death and then contined Activity Cancels Death. Id is PERSON_ID.
UNION SELECT 47 AS id, 'Death and then contined Activity Cancels Death. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.death WHERE person_id = '47') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 49: Duplicate drug records become one record in the CDM. Id is PERSON_ID.
UNION SELECT 49 AS id, 'Duplicate drug records become one record in the CDM. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_exposure WHERE person_id = '49' AND drug_concept_id = '40161912' AND drug_exposure_start_date = '02-01-2012') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 51: Negative daysupp should be 0 in cdm. Id is PERSON_ID.
UNION SELECT 51 AS id, 'Negative daysupp should be 0 in cdm. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_exposure WHERE person_id = '51' AND drug_concept_id = '1545998' AND drug_exposure_start_date = '06-12-2012' AND days_supply = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 53: Daysupp >365 should be 365 in cdm. Id is PERSON_ID.
UNION SELECT 53 AS id, 'Daysupp >365 should be 365 in cdm. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_exposure WHERE person_id = '53' AND drug_concept_id = '1545998' AND drug_exposure_start_date = '08-07-2012' AND days_supply = '365') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 55: CPT4 drug code in inpatient record moves to drug_exposure. Id is PERSON_ID.
UNION SELECT 55 AS id, 'CPT4 drug code in inpatient record moves to drug_exposure. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_exposure WHERE person_id = '55' AND drug_concept_id = '46233994' AND drug_exposure_start_date = '2012-08-09') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 57: Days supply is NULL but DRUG_EXPOSURE_END_DATE is set to DRUG_EXPOSURE_START_DATE (HIX-1430). Id is PERSON_ID.
UNION SELECT 57 AS id, 'Days supply is NULL but DRUG_EXPOSURE_END_DATE is set to DRUG_EXPOSURE_START_DATE (HIX-1430). Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_exposure WHERE person_id = '57' AND drug_concept_id = '46233994' AND drug_exposure_start_date = '2012-08-09' AND drug_exposure_end_date = '2012-08-09') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 59: Patient has 11 digit NDC that doesn''t map, should use first 9 digits instead. Id is PERSON_ID.
UNION SELECT 59 AS id, 'Patient has 11 digit NDC that doesn''t map, should use first 9 digits instead. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_exposure WHERE person_id = '59' AND drug_concept_id = '46275250' AND drug_exposure_start_date = '01-17-2012') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 61: Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to DRUG_CONCEPT_ID=0 because of the date filter. Id is PERSON_ID.
UNION SELECT 61 AS id, 'Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to DRUG_CONCEPT_ID=0 because of the date filter. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_exposure WHERE person_id = '61' AND drug_concept_id = '0' AND drug_exposure_start_date = '07-08-2006') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 63: Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to correct DRUG_CONCEPT_ID because of the date filter. Id is PERSON_ID.
UNION SELECT 63 AS id, 'Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to correct DRUG_CONCEPT_ID because of the date filter. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_exposure WHERE person_id = '63' AND drug_concept_id = '45775771' AND drug_exposure_start_date = '09-18-2014') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 65: Tofacitinib mapps to 11-digit DRUG_SOURCE_CONCEPT_ID instead of 9-digit (HIX-1534)
UNION SELECT 65 AS id, 'Tofacitinib mapps to 11-digit DRUG_SOURCE_CONCEPT_ID instead of 9-digit (HIX-1534)' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_exposure WHERE person_id = '65' AND drug_source_concept_id = '45332969') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 67: Two drugs with same ingredient within 30 days, should be one drug era. Id is PERSON_ID.
UNION SELECT 67 AS id, 'Two drugs with same ingredient within 30 days, should be one drug era. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_era WHERE person_id = '67' AND drug_concept_id = '1134439' AND drug_era_start_date = '02-04-2012' AND gap_days = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 69: Two drugs with same ingredient within 30 days, but 10 gap days. Id is PERSON_ID.
UNION SELECT 69 AS id, 'Two drugs with same ingredient within 30 days, but 10 gap days. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_era WHERE person_id = '69' AND drug_concept_id = '1134439' AND drug_era_start_date = '02-04-2012' AND gap_days = '10') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 71: Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.
UNION SELECT 71 AS id, 'Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_era WHERE person_id = '71' AND drug_concept_id = '1134439' AND drug_era_start_date = '02-04-2012' AND gap_days = '10') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 71 AS id, 'Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_era WHERE person_id = '71') != 1 THEN 'FAIL' ELSE 'PASS' END AS status
-- 73: Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.
UNION SELECT 73 AS id, 'Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_era WHERE person_id = '73' AND drug_concept_id = '1134439' AND drug_era_start_date = '09-21-2012' AND gap_days = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 73 AS id, 'Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_era WHERE person_id = '73' AND drug_concept_id = '1134439' AND drug_era_start_date = '12-08-2012' AND gap_days = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 75: Drug_era_end_date should be drug start date + days supply. Id is PERSON_ID.
UNION SELECT 75 AS id, 'Drug_era_end_date should be drug start date + days supply. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_era WHERE person_id = '75' AND drug_concept_id = '956874' AND drug_era_start_date = '12-08-2010' AND drug_era_end_date = '12-22-2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 77: Drug era created from procedure drug. Id is PERSON_ID.
UNION SELECT 77 AS id, 'Drug era created from procedure drug. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_era WHERE person_id = '77' AND drug_concept_id = '19135830' AND drug_era_start_date = '2012-03-26') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 79: Drug with two ingredients should have two drug eras. Id is PERSON_ID.
UNION SELECT 79 AS id, 'Drug with two ingredients should have two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_era WHERE person_id = '79' AND drug_concept_id = '1134439' AND drug_era_start_date = '05-01-2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 79 AS id, 'Drug with two ingredients should have two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_era WHERE person_id = '79' AND drug_concept_id = '1112807' AND drug_era_start_date = '05-01-2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 81: Two drugs with same ingredient within 30 days, one occurs outside of observation_period. Drug era should only include drug inside observation_period. Id is PERSON_ID.
UNION SELECT 81 AS id, 'Two drugs with same ingredient within 30 days, one occurs outside of observation_period. Drug era should only include drug inside observation_period. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.drug_era WHERE person_id = '81' AND drug_concept_id = '1134439' AND drug_era_start_date = '01-08-2012' AND gap_days = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 83: Location record generated for egeoloc 11. Id is PERSON_ID
UNION SELECT 83 AS id, 'Location record generated for egeoloc 11. Id is PERSON_ID' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.location WHERE state = 'NJ' AND location_source_value = '11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 84: No location record generated for egeoloc 89. Id is PERSON_ID
UNION SELECT 84 AS id, 'No location record generated for egeoloc 89. Id is PERSON_ID' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.location WHERE location_source_value = '89') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 85: Only one location record generated for 38. Id is PERSON_ID
UNION SELECT 85 AS id, 'Only one location record generated for 38. Id is PERSON_ID' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.location WHERE state = 'VA' AND location_source_value = '38') != 1 THEN 'FAIL' ELSE 'PASS' END AS status
-- 86: LOINC code does not have a dash in the second to last character, record is dropped. Id is PERSON_ID.
UNION SELECT 86 AS id, 'LOINC code does not have a dash in the second to last character, record is dropped. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '86') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 88: Svcdate is outside of observation period, record is kept. Id is PERSON_ID.
UNION SELECT 88 AS id, 'Svcdate is outside of observation period, record is kept. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '88') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 90: Patient has abnormal=L; value as concept_id = 4267416. Id is PERSON_ID.
UNION SELECT 90 AS id, 'Patient has abnormal=L; value as concept_id = 4267416. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '90' AND value_as_concept_id = '4267416') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 92: Patient has abnormal=H; value as concept_id = 4267416. Id is PERSON_ID.
UNION SELECT 92 AS id, 'Patient has abnormal=H; value as concept_id = 4267416. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '92' AND value_as_concept_id = '4328749') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 94: Patient has abnormal=N; value as concept_id = 4267416. Id is PERSON_ID.
UNION SELECT 94 AS id, 'Patient has abnormal=N; value as concept_id = 4267416. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '94' AND value_as_concept_id = '4069590') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 96: Patient has abnormal=A; value as concept_id = 4267416. Id is PERSON_ID.
UNION SELECT 96 AS id, 'Patient has abnormal=A; value as concept_id = 4267416. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '96' AND value_as_concept_id = '4135493') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 98: Patient has abnormal=+; value as concept_id = 4267416. Id is PERSON_ID.
UNION SELECT 98 AS id, 'Patient has abnormal=+; value as concept_id = 4267416. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '98' AND value_as_concept_id = '9191') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 100: Patient has result ne 0 and > neg 99999, result listed in value as number field. Id is PERSON_ID.
UNION SELECT 100 AS id, 'Patient has result ne 0 and > neg 99999, result listed in value as number field. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '100' AND value_as_number = '120') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 102: Patient lowercase units, maps to unit_concept_id 8840 (HIX-1183). Id is PERSON_ID.
UNION SELECT 102 AS id, 'Patient lowercase units, maps to unit_concept_id 8840 (HIX-1183). Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '102' AND value_as_number = '100' AND unit_concept_id = '8840') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 104: If you do not get a map from UCUM for UNIT_CONCEPT_ID then try JNJ_UNITS (HIX-1419). Id is PERSON_ID.
UNION SELECT 104 AS id, 'If you do not get a map from UCUM for UNIT_CONCEPT_ID then try JNJ_UNITS (HIX-1419). Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '104' AND unit_concept_id = '8739') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 106: for LOINCs 3142-7, 29463-7, 3141-9 sometimes padded with 0000, strip padding (HIX-1418). Id is PERSON_ID.
UNION SELECT 106 AS id, 'for LOINCs 3142-7, 29463-7, 3141-9 sometimes padded with 0000, strip padding (HIX-1418). Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '106' AND value_as_number = '150' AND unit_concept_id = '8739') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 108: Patient has REFHIGH and REFLOW mapping correctly. Check to ensure floats convert correctly. Id is PERSON_ID.
UNION SELECT 108 AS id, 'Patient has REFHIGH and REFLOW mapping correctly. Check to ensure floats convert correctly. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '108' AND value_as_concept_id = '9191' AND range_low = '1' AND range_high = '10.8') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 110: Patient has a LOINC of 3142-7, 29463-7, 3141-9 and RESULT > 100000 and RESUNIT = 'LBS'
UNION SELECT 110 AS id, 'Patient has a LOINC of 3142-7, 29463-7, 3141-9 and RESULT > 100000 and RESUNIT = 'LBS'' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '110' AND value_as_number = '195' AND unit_concept_id = '8739') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 112: Patient has a LOINC of 3142-7, 29463-7, 3141-9 and RESULT > 100000 and RESUNIT = 'LBS'.  No dropping of zeros
UNION SELECT 112 AS id, 'Patient has a LOINC of 3142-7, 29463-7, 3141-9 and RESULT > 100000 and RESUNIT = 'LBS'.  No dropping of zeros' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '112' AND value_as_number = '195000' AND unit_concept_id = '8739') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 114: Patient has 2 in CGTPKAMT column, value_as_number=1 pack per day or more. Id is PERSON_ID.
UNION SELECT 114 AS id, 'Patient has 2 in CGTPKAMT column, value_as_number=1 pack per day or more. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '114' AND measurement_date = '2012-03-14' AND value_as_number = '2' AND measurement_source_value = 'CGTPKAMT' AND value_source_value = '1 pack per day or more') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 116: Patient has weight 201, value_as_string = null, value_as_number=201. Id is PERSON_ID.
UNION SELECT 116 AS id, 'Patient has weight 201, value_as_string = null, value_as_number=201. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '116' AND measurement_date = '2012-07-16' AND value_as_number = '201' AND measurement_source_value = 'WEIGHT') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 118: BMI is only question answered bmi is only record created in observation . Id is PERSON_ID.
UNION SELECT 118 AS id, 'BMI is only question answered bmi is only record created in observation . Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.measurement WHERE person_id = '118' AND measurement_date = '2012-09-22' AND value_as_number = '28.6' AND measurement_source_value = 'BMI') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 120: Subsumed enrollment test where two enrollment durations with the second subsumed by the first results in a single observation. Id is PERSON_ID.
UNION SELECT 120 AS id, 'Subsumed enrollment test where two enrollment durations with the second subsumed by the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation_period WHERE person_id = '120' AND observation_period_start_date = '2012-01-01' AND observation_period_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 120 AS id, 'Subsumed enrollment test where two enrollment durations with the second subsumed by the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation_period WHERE person_id = '120') != 1 THEN 'FAIL' ELSE 'PASS' END AS status
-- 121: Combine enrollment test where two enrollment durations with the second within 30 days of the first results in a single observation. Id is PERSON_ID.
UNION SELECT 121 AS id, 'Combine enrollment test where two enrollment durations with the second within 30 days of the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation_period WHERE person_id = '121' AND observation_period_start_date = '2012-05-01' AND observation_period_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 121 AS id, 'Combine enrollment test where two enrollment durations with the second within 30 days of the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation_period WHERE person_id = '121') != 1 THEN 'FAIL' ELSE 'PASS' END AS status
-- 122: Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.
UNION SELECT 122 AS id, 'Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation_period WHERE person_id = '122' AND observation_period_start_date = '2012-01-01' AND observation_period_end_date = '2012-06-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 122 AS id, 'Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation_period WHERE person_id = '122' AND observation_period_start_date = '2012-08-02' AND observation_period_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 123: Test two duplicate enrollment records results in a single observation. Id is PERSON_ID.
UNION SELECT 123 AS id, 'Test two duplicate enrollment records results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation_period WHERE person_id = '123' AND observation_period_start_date = '2012-01-01' AND observation_period_end_date = '2012-12-25') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 123 AS id, 'Test two duplicate enrollment records results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation_period WHERE person_id = '123' AND observation_period_start_date = '2012-01-01' AND observation_period_end_date = '2012-12-25') != 1 THEN 'FAIL' ELSE 'PASS' END AS status
-- 124: When a person has a death recorded then we DO NOT truncate the OBSERVATION_PERIOD_END_DATE to reflect the corresponding DEATH_DATE. Id is PERSON_ID.
UNION SELECT 124 AS id, 'When a person has a death recorded then we DO NOT truncate the OBSERVATION_PERIOD_END_DATE to reflect the corresponding DEATH_DATE. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation_period WHERE person_id = '124' AND observation_period_start_date = '2012-01-01' AND observation_period_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 125: When a person has a death recorded then we DO NOT truncate the OBSERVATION_PERIOD_END_DATE to reflect the corresponding DEATH_DATE. Id is PERSON_ID.
UNION SELECT 125 AS id, 'When a person has a death recorded then we DO NOT truncate the OBSERVATION_PERIOD_END_DATE to reflect the corresponding DEATH_DATE. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation_period WHERE person_id = '125' AND observation_period_start_date = '2012-01-01' AND observation_period_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 126: Store Discharge Status. Id is PERSON_ID.
UNION SELECT 126 AS id, 'Store Discharge Status. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.observation WHERE person_id = '126' AND observation_concept_id = '4202605' AND observation_source_value = '51') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 128: Person does not have prescription benefits and is excluded. Id is PERSON_ID.
UNION SELECT 128 AS id, 'Person does not have prescription benefits and is excluded. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.payer_plan_period WHERE person_id = '128') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 129: Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.
UNION SELECT 129 AS id, 'Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.payer_plan_period WHERE person_id = '129' AND payer_plan_period_start_date = '2013-01-01' AND payer_plan_period_end_date = '2013-01-31' AND payer_source_value = 'N Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 129 AS id, 'Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.payer_plan_period WHERE person_id = '129' AND payer_plan_period_start_date = '2013-05-01' AND payer_plan_period_end_date = '2013-05-31' AND payer_source_value = 'N Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 130: Person has a gap of <32 days between enrollment periods with the same payer_source_value; person has ONE records. Id is PERSON_ID.
UNION SELECT 130 AS id, 'Person has a gap of <32 days between enrollment periods with the same payer_source_value; person has ONE records. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.payer_plan_period WHERE person_id = '130' AND payer_plan_period_start_date = '2013-01-01' AND payer_plan_period_end_date = '2013-02-28' AND payer_source_value = 'N Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 130 AS id, 'Person has a gap of <32 days between enrollment periods with the same payer_source_value; person has ONE records. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.payer_plan_period WHERE person_id = '130') != 1 THEN 'FAIL' ELSE 'PASS' END AS status
-- 131: Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.
UNION SELECT 131 AS id, 'Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.payer_plan_period WHERE person_id = '131' AND payer_plan_period_start_date = '2012-04-01' AND payer_plan_period_end_date = '2012-04-06' AND payer_source_value = 'C Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 131 AS id, 'Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.payer_plan_period WHERE person_id = '131' AND payer_plan_period_start_date = '2012-04-07' AND payer_plan_period_end_date = '2012-04-30' AND payer_source_value = 'C Commercial POS') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 132: Family source value derived from ENROLID. Id is PERSON_ID.
UNION SELECT 132 AS id, 'Family source value derived from ENROLID. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.payer_plan_period WHERE person_id = '132' AND payer_plan_period_start_date = '2012-04-01' AND payer_plan_period_end_date = '2012-04-30' AND payer_source_value = 'C Commercial PPO' AND family_source_value = 'SUBSTRING(RIGHT('00000000000' + CONVERT(VARCHAR,patient$enrolid), 11), 1,9)') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 133: Person does not have prescription benefits and is excluded. Id is PERSON_ID.
UNION SELECT 133 AS id, 'Person does not have prescription benefits and is excluded. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.payer_plan_period WHERE person_id = '133') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 134: Person with two genders is excluded. Id is PERSON_ID.
UNION SELECT 134 AS id, 'Person with two genders is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '134') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 135: Person with two birth years >2 yrs apart is excluded. Note person is <90 years old for MDCD test. Id is PERSON_ID.
UNION SELECT 135 AS id, 'Person with two birth years >2 yrs apart is excluded. Note person is <90 years old for MDCD test. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '135') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 136: Person with two birth years <2 yrs apart is kept with last birth year selected. Id is PERSON_ID.
UNION SELECT 136 AS id, 'Person with two birth years <2 yrs apart is kept with last birth year selected. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '136' AND year_of_birth = '1971') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 137: Person born before 1900 is excluded. Id is PERSON_ID.
UNION SELECT 137 AS id, 'Person born before 1900 is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '137') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 138: Person born after the current year is excluded. Id is PERSON_ID.
UNION SELECT 138 AS id, 'Person born after the current year is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '138') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 139: Person born in 2014 but enrolled in 2012 is excluded. Id is PERSON_ID.
UNION SELECT 139 AS id, 'Person born in 2014 but enrolled in 2012 is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '139') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 140: Person born in 2013 but enrolled in 2012 is kept, latest birth year taken. Id is PERSON_ID.
UNION SELECT 140 AS id, 'Person born in 2013 but enrolled in 2012 is kept, latest birth year taken. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '140' AND year_of_birth = '2013') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 141: Person with two enrollment_detail records has one person record. Id is PERSON_ID.
UNION SELECT 141 AS id, 'Person with two enrollment_detail records has one person record. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '141' AND year_of_birth = '1980') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 141 AS id, 'Person with two enrollment_detail records has one person record. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '141') != 1 THEN 'FAIL' ELSE 'PASS' END AS status
-- 142: Person with sex=3 is excluded. Id is PERSON_ID.
UNION SELECT 142 AS id, 'Person with sex=3 is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '142') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 143: Person born after current year. Id is PERSON_ID.
UNION SELECT 143 AS id, 'Person born after current year. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '143') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 144: Person has record with sex=3 but last record has sex=1, person is kept. Id is PERSON_ID.
UNION SELECT 144 AS id, 'Person has record with sex=3 but last record has sex=1, person is kept. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '144' AND gender_concept_id = '8507') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 145: Person born the same year as enrolled, use first enrollment month to impute month of birth and day of birth. Id is PERSON_ID.
UNION SELECT 145 AS id, 'Person born the same year as enrolled, use first enrollment month to impute month of birth and day of birth. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '145' AND year_of_birth = '2012' AND month_of_birth = '4' AND day_of_birth = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 146: Person with Rx benefits is kept. Id is PERSON_ID.
UNION SELECT 146 AS id, 'Person with Rx benefits is kept. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '146') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 147: Person without Rx benefits is excluded. Id is PERSON_ID.
UNION SELECT 147 AS id, 'Person without Rx benefits is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '147') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 148: Person with last enrollment_detail record that has egeoloc=11 gets associated to NJ. Id is PERSON_ID.
UNION SELECT 148 AS id, 'Person with last enrollment_detail record that has egeoloc=11 gets associated to NJ. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.person WHERE person_id = '148') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 149: Patient has a value in PPROC and PROC1 within inpatient_services. Two records should be created. Id is PERSON_ID.
UNION SELECT 149 AS id, 'Patient has a value in PPROC and PROC1 within inpatient_services. Two records should be created. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '149' AND procedure_concept_id = '2514413' AND procedure_date = '2000-01-02' AND procedure_type_concept_id = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 149 AS id, 'Patient has a value in PPROC and PROC1 within inpatient_services. Two records should be created. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '149' AND procedure_concept_id = '2514404' AND procedure_date = '2000-01-02' AND procedure_type_concept_id = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 151: Patient has two PPROC values, two are created, one with inpatient claim detail and the other with inpatient claim header as the procedure_type_concept. Id is PERSON_ID.
UNION SELECT 151 AS id, 'Patient has two PPROC values, two are created, one with inpatient claim detail and the other with inpatient claim header as the procedure_type_concept. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '151' AND procedure_concept_id = '40757105' AND procedure_date = '2012-06-12' AND procedure_type_concept_id = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 151 AS id, 'Patient has two PPROC values, two are created, one with inpatient claim detail and the other with inpatient claim header as the procedure_type_concept. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '151' AND procedure_concept_id = '40757126' AND procedure_date = '2012-06-12' AND procedure_type_concept_id = '32855') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 153: Patient has two different providers for the same procedure, two records should be created. Id is PERSON_ID.
UNION SELECT 153 AS id, 'Patient has two different providers for the same procedure, two records should be created. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '153' AND procedure_concept_id = '2109659' AND procedure_date = '2012-10-20' AND procedure_type_concept_id = '32854') != 2 THEN 'FAIL' ELSE 'PASS' END AS status
-- 155: Patient has HCPCS procedure code with value in PROCMOD, only HCPCS comes across in record since PROCMOD associated with CPT4 only. Id is PERSON_ID.
UNION SELECT 155 AS id, 'Patient has HCPCS procedure code with value in PROCMOD, only HCPCS comes across in record since PROCMOD associated with CPT4 only. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '155' AND procedure_concept_id = '2616464' AND procedure_date = '2012-05-12' AND modifier_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 157: Patient has two records for the same procedure, two records created. Id is PERSON_ID.
UNION SELECT 157 AS id, 'Patient has two records for the same procedure, two records created. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '157' AND procedure_concept_id = '2109995' AND procedure_date = '2012-02-15' AND procedure_type_concept_id = '32860') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 157 AS id, 'Patient has two records for the same procedure, two records created. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '157' AND procedure_concept_id = '2109995' AND procedure_date = '2012-02-15' AND procedure_type_concept_id = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 159: Patient has procedure in proc5 position in facility header, procedure_type_concept_id = 32860. Id is PERSON_ID.
UNION SELECT 159 AS id, 'Patient has procedure in proc5 position in facility header, procedure_type_concept_id = 32860. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '159' AND procedure_type_concept_id = '32860') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 159 AS id, 'Patient has procedure in proc5 position in facility header, procedure_type_concept_id = 32860. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '159' AND procedure_concept_id = '2313827' AND procedure_type_concept_id = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 161: Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.
UNION SELECT 161 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '161' AND procedure_concept_id = '2314252' AND procedure_type_concept_id = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 161 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '161' AND procedure_concept_id = '2314322' AND procedure_type_concept_id = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 161 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '161' AND procedure_concept_id = '40757149' AND procedure_type_concept_id = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 161 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '161' AND procedure_concept_id = '2313736' AND procedure_type_concept_id = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 161 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '161' AND procedure_concept_id = '42739018' AND procedure_type_concept_id = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 161 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '161' AND procedure_concept_id = '709845' AND procedure_type_concept_id = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 163: Patient has an ICD10PCS value in inpatient_admissions field pdx, pdx is correctly mapped and a procedure_occurrence record created (HIX-1255). Id is PERSON_ID.
UNION SELECT 163 AS id, 'Patient has an ICD10PCS value in inpatient_admissions field pdx, pdx is correctly mapped and a procedure_occurrence record created (HIX-1255). Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.procedure_occurrence WHERE person_id = '163' AND procedure_concept_id = '2789746' AND procedure_date = '2016-06-05' AND procedure_type_concept_id = '32855') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 165: Provider in facility header table with stdprov=220, specialty = emergency medicine. Id is PROVIDER_SOURCE_VALUE
UNION SELECT 165 AS id, 'Provider in facility header table with stdprov=220, specialty = emergency medicine. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.provider WHERE specialty_concept_id = '38004510' AND specialty_source_value = '220') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 167: Provider in facility header table with stdprov=''. Id is PROVIDER_SOURCE_VALUE
UNION SELECT 167 AS id, 'Provider in facility header table with stdprov=''. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.provider WHERE specialty_concept_id = '38004514') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 169: Provider in outpatient_services table with stdprov=285, specialty = infectious disease. Id is PROVIDER_SOURCE_VALUE
UNION SELECT 169 AS id, 'Provider in outpatient_services table with stdprov=285, specialty = infectious disease. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.provider WHERE specialty_concept_id = '38004484' AND specialty_source_value = '285') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 171: provider in inpatient_services table with stdprov=540, specialty = cardiac surgery. Id is PROVIDER_SOURCE_VALUE
UNION SELECT 171 AS id, 'provider in inpatient_services table with stdprov=540, specialty = cardiac surgery. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.provider WHERE specialty_concept_id = '38004497' AND specialty_source_value = '540') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 173: provider in lab table with stdprov =22, specialty = addiction medicine. Id is PROVIDER_SOURCE_VALUE
UNION SELECT 173 AS id, 'provider in lab table with stdprov =22, specialty = addiction medicine. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.provider WHERE specialty_concept_id = '38004498' AND specialty_source_value = '22') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 175: Even when PROVID IS NULL create a PROVIDER (HIX-1404). Id is PROVIDER_SOURCE_VALUE
UNION SELECT 175 AS id, 'Even when PROVID IS NULL create a PROVIDER (HIX-1404). Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.provider WHERE provider_source_value IS NULL AND specialty_source_value = '220') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 177: Patient with visit detail that starts before the observation period, start date trimmed to beginning of observation period. Id is PERSON_ID.
UNION SELECT 177 AS id, 'Patient with visit detail that starts before the observation period, start date trimmed to beginning of observation period. Id is PERSON_ID.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_detail WHERE person_id = '177' AND visit_detail_start_date = '2012-01-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 179: svcdate>tsvcdate, visit_end_date is svcdate. Id is PERSON_ID.
UNION SELECT 179 AS id, 'svcdate>tsvcdate, visit_end_date is svcdate. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '179' AND visit_start_date = '2012-03-21' AND visit_end_date = '2012-03-21') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 181: Service falls during observation period but ends after the period ends, visit_end_date is the observation_period_end_date. Id is PERSON_ID.
UNION SELECT 181 AS id, 'Service falls during observation period but ends after the period ends, visit_end_date is the observation_period_end_date. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '181' AND visit_start_date = '2012-12-30' AND visit_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 183: service in inpatient_services with stdplac of 23, visit classified as ER. Id is PERSON_ID.
UNION SELECT 183 AS id, 'service in inpatient_services with stdplac of 23, visit classified as ER. Id is PERSON_ID.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_detail WHERE person_id = '183' AND visit_detail_concept_id = '8870' AND visit_detail_start_date = '2012-04-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 185: service in outpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.
UNION SELECT 185 AS id, 'service in outpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '185' AND visit_concept_id = '9203' AND visit_start_date = '2012-05-01' AND visit_end_date = '2012-05-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 187: service in outpatient_services with revcode of 0100, visit classified as IP. Id is PERSON_ID.
UNION SELECT 187 AS id, 'service in outpatient_services with revcode of 0100, visit classified as IP. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '187' AND visit_concept_id = '9201' AND visit_start_date = '2012-10-17' AND visit_end_date = '2012-10-20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 189: Two visits created, expect a visit with a PRECEDING_VISIT_OCCURRENCE_ID. Id is PERSON_ID. (HIX-1521)
UNION SELECT 189 AS id, 'Two visits created, expect a visit with a PRECEDING_VISIT_OCCURRENCE_ID. Id is PERSON_ID. (HIX-1521)' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '189' AND visit_start_date = '2012-10-01' AND preceding_visit_occurrence_id = (SELECT visit_occurrence_id FROM ccae_cdm_test.visit_occurrence WHERE person_id = '189' AND visit_start_date = '2012-08-08')) = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 191: patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.
UNION SELECT 191 AS id, 'patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '191' AND visit_start_date = '2012-08-08' AND visit_end_date = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 191 AS id, 'patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '191' AND visit_start_date = '2012-10-01' AND visit_end_date = '2012-10-05') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 193: Patient has an ER record that starts and ends on the first day of the IP visit, separate ER visit created. Id is PERSON_ID.
UNION SELECT 193 AS id, 'Patient has an ER record that starts and ends on the first day of the IP visit, separate ER visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '193' AND visit_concept_id = '9203' AND visit_start_date = '2012-09-03' AND visit_end_date = '2012-09-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
UNION SELECT 193 AS id, 'Patient has an ER record that starts and ends on the first day of the IP visit, separate ER visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '193' AND visit_concept_id = '9201' AND visit_start_date = '2012-09-03' AND visit_end_date = '2012-09-10') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 195: Patient has two lines in the inpatient_services table where the difference between the end_date of one line and the start_date of the next is <= 1, one visit created. Id is PERSON_ID.
UNION SELECT 195 AS id, 'Patient has two lines in the inpatient_services table where the difference between the end_date of one line and the start_date of the next is <= 1, one visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '195') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 197: Setting Discharge_to_Concept_id for IP Record (HIX-1429). Id is PERSON_ID.
UNION SELECT 197 AS id, 'Setting Discharge_to_Concept_id for IP Record (HIX-1429). Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '197' AND visit_start_date = '2012-03-21' AND visit_end_date = '2012-03-21' AND discharge_to_concept_id = '8536') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 199: Patient has record in outpatient_services table but no rx benefits, visit dropped. Id is PERSON_ID.
UNION SELECT 199 AS id, 'Patient has record in outpatient_services table but no rx benefits, visit dropped. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '199') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 201: Patient has two records in the same visit with different provid and provstd. Id is PERSON_ID.
UNION SELECT 201 AS id, 'Patient has two records in the same visit with different provid and provstd. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_cdm_test.visit_occurrence WHERE person_id = '201' AND visit_start_date = '2012-08-08' AND visit_end_date = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status