DROP TABLE IF EXISTS cprd_cdm_test.test_results;
CREATE TABLE cprd_cdm_test.test_results (id INT, description VARCHAR(512), test VARCHAR(256), status VARCHAR(5));
-- 311: CARE_SITE - Practice_id=301, region=13, id is care_site_id
INSERT INTO cprd_cdm_test.test_results SELECT 311 AS id, 'CARE_SITE - Practice_id=301, region=13, id is care_site_id' AS description, 'Expect care_site' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.care_site WHERE care_site_id = '311' AND location_id = '13') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 1311: CONDITION_ERA - Patient has Medical records that collapse in the Condition Era table
INSERT INTO cprd_cdm_test.test_results SELECT 1311 AS id, 'CONDITION_ERA - Patient has Medical records that collapse in the Condition Era table' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_era WHERE person_id = '1311' AND condition_concept_id = '75555' AND condition_era_start_date = '2012-01-01' AND condition_era_end_date = '2012-01-02' AND condition_occurrence_count = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 2311: CONDITION_OCCURRENCE - Read clinical condition with visit, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 2311 AS id, 'CONDITION_OCCURRENCE - Read clinical condition with visit, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '2311' AND condition_concept_id = '75555' AND condition_start_date = '2012-01-01' AND condition_type_concept_id = '32020' AND provider_id = '1001' AND condition_source_value = 'F563500' AND condition_source_concept_id = '45436713') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 2311 AS id, 'CONDITION_OCCURRENCE - Read clinical condition with visit, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '2311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 3311: CONDITION_OCCURRENCE - Read clinical condition, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 3311 AS id, 'CONDITION_OCCURRENCE - Read clinical condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '3311' AND condition_concept_id = '195862' AND condition_start_date = '2012-03-01' AND condition_type_concept_id = '32020' AND provider_id = '1001' AND condition_source_value = 'K17y000' AND condition_source_concept_id = '45453481') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 3311 AS id, 'CONDITION_OCCURRENCE - Read clinical condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '3311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 4311: CONDITION_OCCURRENCE - Read clinical condition outside observation period, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 4311 AS id, 'CONDITION_OCCURRENCE - Read clinical condition outside observation period, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '4311' AND condition_concept_id = '195862' AND condition_start_date = '2009-03-01' AND condition_type_concept_id = '32020' AND provider_id = '1001' AND condition_source_value = 'K17y000' AND condition_source_concept_id = '45453481') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 4311 AS id, 'CONDITION_OCCURRENCE - Read clinical condition outside observation period, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '4311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 5311: CONDITION_OCCURRENCE - Read immunisation condition, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 5311 AS id, 'CONDITION_OCCURRENCE - Read immunisation condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '5311' AND condition_concept_id = '4123595' AND condition_start_date = '2011-03-01' AND condition_type_concept_id = '32020' AND provider_id = '1001' AND condition_source_value = 'J040.14' AND condition_source_concept_id = '45463565') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 5311 AS id, 'CONDITION_OCCURRENCE - Read immunisation condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '5311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 6311: CONDITION_OCCURRENCE - Read referral condition, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 6311 AS id, 'CONDITION_OCCURRENCE - Read referral condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '6311' AND condition_concept_id = '377368' AND condition_start_date = '2011-03-01' AND condition_type_concept_id = '32020' AND provider_id = '1001' AND condition_source_value = 'P00..00' AND condition_source_concept_id = '45420722') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 6311 AS id, 'CONDITION_OCCURRENCE - Read referral condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '6311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 7888: valid deathdate, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 7888 AS id, 'valid deathdate, id is person_id' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.death WHERE person_id = '7888' AND death_date = '2010-01-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 7888 AS id, 'valid deathdate, id is person_id' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.death WHERE person_id = '7888') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 8888: invalid: no deathdate, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 8888 AS id, 'invalid: no deathdate, id is person_id' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.death WHERE person_id = '8888') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 9111: drug era with 2 drug records, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 9111 AS id, 'drug era with 2 drug records, id is person_id' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_era WHERE person_id = '9111' AND drug_concept_id = '1316354' AND drug_era_start_date = '2012-01-01' AND drug_era_end_date = '2012-02-18' AND drug_exposure_count = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 9111 AS id, 'drug era with 2 drug records, id is person_id' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_era WHERE person_id = '9111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 10111: drug era with multilex drug code id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 10111 AS id, 'drug era with multilex drug code id is person_id' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_era WHERE person_id = '10111' AND drug_concept_id = '1177480' AND drug_era_start_date = '2012-01-31' AND drug_era_end_date = '2012-02-29' AND drug_exposure_count = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 10111 AS id, 'drug era with multilex drug code id is person_id' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_era WHERE person_id = '10111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 11311: DRUG_EXPOSURE - testing the lookup for numdays does correct end date start+28 days, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 11311 AS id, 'DRUG_EXPOSURE - testing the lookup for numdays does correct end date start+28 days, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '11311' AND drug_concept_id = '19073982' AND drug_exposure_end_date = '2012-1-29' AND refills = '1' AND quantity = '1' AND drug_source_value = '58976020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 11311 AS id, 'DRUG_EXPOSURE - testing the lookup for numdays does correct end date start+28 days, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '11311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 12311: DRUG_EXPOSURE - testing when there is no lookup available default to start dte, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 12311 AS id, 'DRUG_EXPOSURE - testing when there is no lookup available default to start dte, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '12311' AND drug_concept_id = '1539463' AND drug_exposure_end_date = '2012-1-1' AND refills = '1' AND quantity = '1' AND drug_source_value = '72487020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 12311 AS id, 'DRUG_EXPOSURE - testing when there is no lookup available default to start dte, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '12311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 13311: DRUG_EXPOSURE- The drug records comes in without a valid days supply, no lookup in DAYSSUPPLY_DECODES, no lookups in DAYSSUPPLY_MODES, assume 1 day duration.Id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 13311 AS id, 'DRUG_EXPOSURE- The drug records comes in without a valid days supply, no lookup in DAYSSUPPLY_DECODES, no lookups in DAYSSUPPLY_MODES, assume 1 day duration.Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '13311' AND drug_exposure_end_date = '2012-1-1' AND refills = '1' AND quantity = '1' AND drug_source_value = '93680020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 13311 AS id, 'DRUG_EXPOSURE- The drug records comes in without a valid days supply, no lookup in DAYSSUPPLY_DECODES, no lookups in DAYSSUPPLY_MODES, assume 1 day duration.Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '13311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 14311: DRUG_EXPOSURE - testing end date: You have a THERAPY.NUMDAYS = 40. Id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 14311 AS id, 'DRUG_EXPOSURE - testing end date: You have a THERAPY.NUMDAYS = 40. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '14311' AND drug_concept_id = '19073982' AND drug_exposure_end_date = '2012-2-9' AND refills = '1' AND quantity = '1' AND drug_source_value = '58976020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 14311 AS id, 'DRUG_EXPOSURE - testing end date: You have a THERAPY.NUMDAYS = 40. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '14311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 15311: DRUG_EXPOSURE - testing end date: You have a THERAPY.NUMDAYS = 366 - show correct to 29 days using lookup. Id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 15311 AS id, 'DRUG_EXPOSURE - testing end date: You have a THERAPY.NUMDAYS = 366 - show correct to 29 days using lookup. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '15311' AND drug_concept_id = '19073982' AND drug_exposure_end_date = '2012-1-29' AND refills = '1' AND quantity = '1' AND drug_source_value = '58976020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 15311 AS id, 'DRUG_EXPOSURE - testing end date: You have a THERAPY.NUMDAYS = 366 - show correct to 29 days using lookup. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '15311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 16311: DRUG_EXPOSURE - Test visit_occurrence_id: Drug is written to DRUG_EXPOSURE. Id is person_Id
INSERT INTO cprd_cdm_test.test_results SELECT 16311 AS id, 'DRUG_EXPOSURE - Test visit_occurrence_id: Drug is written to DRUG_EXPOSURE. Id is person_Id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '16311' AND drug_concept_id = '19073982' AND drug_exposure_start_date = '2012-03-12' AND refills = '1' AND quantity = '1' AND drug_source_value = '58976020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 16311 AS id, 'DRUG_EXPOSURE - Test visit_occurrence_id: Drug is written to DRUG_EXPOSURE. Id is person_Id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '16311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 17311: DRUG_EXPOSURE - Drug date does exist within a valid observation period but does not have a consultation date. Id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 17311 AS id, 'DRUG_EXPOSURE - Drug date does exist within a valid observation period but does not have a consultation date. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '17311' AND drug_concept_id = '19073982' AND drug_exposure_start_date = '2012-01-01' AND drug_exposure_end_date = '2012-1-29' AND refills = '1' AND quantity = '1' AND drug_source_value = '58976020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 17311 AS id, 'DRUG_EXPOSURE - Drug date does exist within a valid observation period but does not have a consultation date. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '17311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 18311: DRUG_EXPOSURE - PRODCODE = -1 - invalid.
INSERT INTO cprd_cdm_test.test_results SELECT 18311 AS id, 'DRUG_EXPOSURE - PRODCODE = -1 - invalid.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '18311') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 19311: DRUG_EXPOSURE - Invalid status, id = person_Id
INSERT INTO cprd_cdm_test.test_results SELECT 19311 AS id, 'DRUG_EXPOSURE - Invalid status, id = person_Id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '19311') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 20311: DRUG_EXPOSURE - valid immunization with visit, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 20311 AS id, 'DRUG_EXPOSURE - valid immunization with visit, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '20311' AND drug_concept_id = '19136026' AND drug_exposure_start_date = '2012-01-01' AND drug_exposure_end_date = '2012-01-01' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 20311 AS id, 'DRUG_EXPOSURE - valid immunization with visit, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '20311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 21311: DRUG_EXPOSURE - valid immunization without visit - null visit_occur_id
INSERT INTO cprd_cdm_test.test_results SELECT 21311 AS id, 'DRUG_EXPOSURE - valid immunization without visit - null visit_occur_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '21311' AND drug_concept_id = '19136026' AND drug_exposure_start_date = '2012-01-01' AND drug_exposure_end_date = '2012-01-01' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 21311 AS id, 'DRUG_EXPOSURE - valid immunization without visit - null visit_occur_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '21311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 22311: DRUG_EXPOSURE - Read  outside observation period, id = person_id
INSERT INTO cprd_cdm_test.test_results SELECT 22311 AS id, 'DRUG_EXPOSURE - Read  outside observation period, id = person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '22311' AND drug_concept_id = '19136026' AND drug_exposure_start_date = '2009-03-01' AND drug_exposure_end_date = '2009-03-01' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 23311: DRUG_EXPOSURE - immunization read code condition goes into conditions, id = person_id
INSERT INTO cprd_cdm_test.test_results SELECT 23311 AS id, 'DRUG_EXPOSURE - immunization read code condition goes into conditions, id = person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '23311') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 24311: DRUG_EXPOSURE - valid read from clinical, id = patient$person_id
INSERT INTO cprd_cdm_test.test_results SELECT 24311 AS id, 'DRUG_EXPOSURE - valid read from clinical, id = patient$person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '24311' AND drug_concept_id = '19136026' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 24311 AS id, 'DRUG_EXPOSURE - valid read from clinical, id = patient$person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '24311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 25311: DRUG_EXPOSURE - valid read from referral, id = person_id
INSERT INTO cprd_cdm_test.test_results SELECT 25311 AS id, 'DRUG_EXPOSURE - valid read from referral, id = person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '25311' AND drug_concept_id = '19136026' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 25311 AS id, 'DRUG_EXPOSURE - valid read from referral, id = person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '25311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 26311: DRUG_EXPOSURE - valid entry, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 26311 AS id, 'DRUG_EXPOSURE - valid entry, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '26311' AND drug_concept_id = '19136026' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 26311 AS id, 'DRUG_EXPOSURE - valid entry, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '26311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 27311: DRUG_EXPOSURE - valid entry, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 27311 AS id, 'DRUG_EXPOSURE - valid entry, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '27311' AND drug_concept_id = '19136026' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 27311 AS id, 'DRUG_EXPOSURE - valid entry, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '27311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 28311: valid entry for device exposure, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 28311 AS id, 'valid entry for device exposure, id is person_id' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.device_exposure WHERE person_id = '28311' AND device_concept_id = '4192787' AND device_exposure_start_date = '2012-01-01' AND device_exposure_end_date = '2012-01-01' AND device_source_value = '9b20.00') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 29311: You have a valid PRODCODE but doesnt get an VOCAB mapping.PRODCODE = 46190. Id is person_Id
INSERT INTO cprd_cdm_test.test_results SELECT 29311 AS id, 'You have a valid PRODCODE but doesnt get an VOCAB mapping.PRODCODE = 46190. Id is person_Id' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.device_exposure WHERE person_id = '29311' AND device_concept_id = '21380480' AND device_exposure_start_date = '2012-01-01' AND device_source_value = '99978020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 29311 AS id, 'You have a valid PRODCODE but doesnt get an VOCAB mapping.PRODCODE = 46190. Id is person_Id' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.device_exposure WHERE person_id = '29311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 30311: testing without hes to give visit_occurrence_id is null - clinical procedure without visit, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 30311 AS id, 'testing without hes to give visit_occurrence_id is null - clinical procedure without visit, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '30311' AND measurement_concept_id = '4132152' AND measurement_date = '2012-01-01' AND provider_id = '1001' AND measurement_source_value = '424Z.00' AND measurement_source_concept_id = '45508441') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 31311: Now test gold observation outside patient observation to exclude
INSERT INTO cprd_cdm_test.test_results SELECT 31311 AS id, 'Now test gold observation outside patient observation to exclude' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '31311' AND measurement_concept_id = '4132152' AND measurement_date = '2009-01-01' AND provider_id = '1001' AND measurement_source_value = '424Z.00' AND measurement_source_concept_id = '45508441') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 32311: immunisation procedure, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 32311 AS id, 'immunisation procedure, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '32311' AND measurement_concept_id = '4132152' AND measurement_date = '2011-03-01' AND provider_id = '1001' AND measurement_source_value = '424Z.00' AND measurement_source_concept_id = '45508441') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 33311: referral procedure, id is person_Id
INSERT INTO cprd_cdm_test.test_results SELECT 33311 AS id, 'referral procedure, id is person_Id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '33311' AND measurement_concept_id = '4132152' AND measurement_date = '2011-03-01' AND provider_id = '1001' AND measurement_source_value = '424Z.00' AND measurement_source_concept_id = '45508441') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 34311: test procedure, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 34311 AS id, 'test procedure, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '34311' AND measurement_concept_id = '4199172' AND measurement_date = '2011-03-01' AND provider_id = '1001' AND measurement_source_value = '215-Clotting tests') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 35311: test observation record 4 fields no range values, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 35311 AS id, 'test observation record 4 fields no range values, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '35311' AND measurement_concept_id = '4132152' AND measurement_date = '2012-01-01' AND value_as_concept_id = '45884153' AND measurement_source_value = '220-Full blood count' AND value_source_value = 'Normal') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 36311: test observation record 4 fields range low test, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 36311 AS id, 'test observation record 4 fields range low test, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '36311' AND measurement_concept_id = '4132152' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702' AND value_as_concept_id = '45884153' AND range_low = '1.2' AND value_source_value = 'Normal') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 37311: test observation record 4 fields range high test, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 37311 AS id, 'test observation record 4 fields range high test, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '37311' AND measurement_concept_id = '4132152' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702' AND value_as_concept_id = '45884153' AND range_high = '4.3' AND value_source_value = 'Normal') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 38311: test observation record 7 fields, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 38311 AS id, 'test observation record 7 fields, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '38311' AND measurement_concept_id = '2212396' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702' AND operator_concept_id = '4172703' AND value_as_number = '14.3' AND value_as_concept_id = '0' AND range_low = '11.5' AND range_high = '16.5' AND unit_concept_id = '8713' AND unit_source_value = 'g/dL') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 39311: test observation record enttype=284, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 39311 AS id, 'test observation record enttype=284, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '39311' AND measurement_concept_id = '3031455' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 40311: test observation record enttype=311, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 40311 AS id, 'test observation record enttype=311, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '40311' AND measurement_concept_id = '0' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 41311: test observation record enttype=154, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 41311 AS id, 'test observation record enttype=154, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '41311' AND measurement_concept_id = '4197249' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 42311: 1) additional observation, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 42311 AS id, '1) additional observation, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '42311' AND measurement_concept_id = '4154790' AND measurement_date = '2010-01-01' AND measurement_type_concept_id = '44818702' AND value_as_number = '80' AND measurement_source_value = '1-Examination Findings-Blood pressure-Diastolic') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 42311 AS id, '2) additional observation' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '42311' AND measurement_concept_id = '4152194' AND measurement_date = '2010-01-01' AND measurement_type_concept_id = '44818702' AND value_as_number = '160' AND measurement_source_value = '1-Examination Findings-Blood pressure-Systolic') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 43222: 201222: obs_period start should be uts and obs_period_end should be tod.
INSERT INTO cprd_cdm_test.test_results SELECT 43222 AS id, '201222: obs_period start should be uts and obs_period_end should be tod.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation_period WHERE person_id = '43222' AND observation_period_start_date = '2001-02-12' AND observation_period_end_date = '2010-01-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 43222 AS id, '201222: obs_period start should be uts and obs_period_end should be tod.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation_period WHERE person_id = '43222') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 44222: 202222: obs_period start should be crd and obs_period_end should be lcd since tod is null.
INSERT INTO cprd_cdm_test.test_results SELECT 44222 AS id, '202222: obs_period start should be crd and obs_period_end should be lcd since tod is null.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation_period WHERE person_id = '44222' AND observation_period_start_date = '2005-10-26' AND observation_period_end_date = '2011-11-11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 44222 AS id, '202222: obs_period start should be crd and obs_period_end should be lcd since tod is null.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation_period WHERE person_id = '44222') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 45222: 203222: patient deleted tod<uts.
INSERT INTO cprd_cdm_test.test_results SELECT 45222 AS id, '203222: patient deleted tod<uts.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation_period WHERE person_id = '45222') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 46311:  clinical procedure with visit
INSERT INTO cprd_cdm_test.test_results SELECT 46311 AS id, ' clinical procedure with visit' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '46311' AND observation_concept_id = '40479404' AND observation_date = '2012-01-01' AND observation_type_concept_id = '38000280' AND observation_source_value = '65PT.11' AND observation_source_concept_id = '45425506') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 46311 AS id, ' clinical procedure with visit' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '46311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 47311:  clinical procedure without visit
INSERT INTO cprd_cdm_test.test_results SELECT 47311 AS id, ' clinical procedure without visit' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '47311' AND observation_concept_id = '40479404' AND observation_date = '2012-03-01' AND observation_type_concept_id = '38000280' AND observation_source_value = '65PT.11' AND observation_source_concept_id = '45425506') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 48311:  clinical procedure outside observation period
INSERT INTO cprd_cdm_test.test_results SELECT 48311 AS id, ' clinical procedure outside observation period' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '48311' AND observation_concept_id = '4044812' AND observation_date = '2009-03-01' AND observation_source_value = 'R100.00' AND observation_source_concept_id = '45474099') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 49311: immunisation procedure
INSERT INTO cprd_cdm_test.test_results SELECT 49311 AS id, 'immunisation procedure' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '49311' AND observation_concept_id = '4044812' AND observation_date = '2011-03-01' AND observation_type_concept_id = '38000280' AND observation_source_value = 'R100.00' AND observation_source_concept_id = '45474099') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 50311: referral procedure
INSERT INTO cprd_cdm_test.test_results SELECT 50311 AS id, 'referral procedure' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '50311' AND observation_concept_id = '4044812' AND observation_date = '2011-03-01' AND observation_type_concept_id = '38000280' AND observation_source_value = 'R100.00' AND observation_source_concept_id = '45474099') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 51311: test procedure
INSERT INTO cprd_cdm_test.test_results SELECT 51311 AS id, 'test procedure' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '51311' AND observation_concept_id = '4044812' AND observation_date = '2011-03-01' AND observation_type_concept_id = '38000280' AND observation_source_value = '215--R100.00' AND observation_source_concept_id = '45474099') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 52311: observation not mapped
INSERT INTO cprd_cdm_test.test_results SELECT 52311 AS id, 'observation not mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '52311' AND observation_concept_id = '0' AND observation_date = '2011-03-01' AND observation_source_value = '215--Z5A6200' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 53311: Read clinical medical history condition non-mapped
INSERT INTO cprd_cdm_test.test_results SELECT 53311 AS id, 'Read clinical medical history condition non-mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '53311' AND observation_concept_id = '0' AND observation_date = '2011-01-01' AND observation_source_value = 'Z5A6200' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 54311: Read referral medical history condition non-mapped
INSERT INTO cprd_cdm_test.test_results SELECT 54311 AS id, 'Read referral medical history condition non-mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '54311' AND observation_concept_id = '0' AND observation_date = '2011-01-01' AND observation_source_value = 'Z5A6200' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 55311: Read test medical history condition non-mapped
INSERT INTO cprd_cdm_test.test_results SELECT 55311 AS id, 'Read test medical history condition non-mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '55311' AND observation_concept_id = '0' AND observation_date = '2011-01-01' AND observation_source_value = '215--Z5A6200' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 56311: Read immunisatoin medical history condition non-mapped
INSERT INTO cprd_cdm_test.test_results SELECT 56311 AS id, 'Read immunisatoin medical history condition non-mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '56311' AND observation_concept_id = '0' AND observation_date = '2011-01-01' AND observation_source_value = 'Z5A6200' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 57311: test observation record 4 fields
INSERT INTO cprd_cdm_test.test_results SELECT 57311 AS id, 'test observation record 4 fields' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '57311' AND observation_concept_id = '40479404' AND observation_date = '2012-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = 'Normal' AND observation_source_value = '215--65PT.11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 58311: test observation record 7 fields
INSERT INTO cprd_cdm_test.test_results SELECT 58311 AS id, 'test observation record 7 fields' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '58311' AND observation_concept_id = '4187457' AND observation_date = '2012-01-01' AND observation_type_concept_id = '38000280' AND value_as_number = '3.7' AND qualifier_concept_id = '4172703' AND observation_source_value = '412-Airway ...-66Ya.00' AND unit_source_value = '%') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 58311 AS id, 'test observation record 7 fields' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '58311') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 59311: 1) additional observation 
INSERT INTO cprd_cdm_test.test_results SELECT 59311 AS id, '1) additional observation ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '59311' AND observation_concept_id = '0' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = '72487020' AND value_as_concept_id = '1539463' AND observation_source_value = '21-Allergy-Allergy-Drug Code' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 59311 AS id, '2) additional observation ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '59311' AND observation_concept_id = '0' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = 'Intolerance' AND observation_source_value = '21-Allergy-Allergy-Reaction Type' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 59311 AS id, '3) additional observation ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '59311' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_number = '3' AND observation_source_value = '21-Allergy-Allergy-Severity' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 59311 AS id, '4) additional observation ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '59311' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_number = '3' AND observation_source_value = '21-Allergy-Allergy-Certainty' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 59311 AS id, '4) additional observation ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '59311' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = 'M240012' AND observation_source_value = '21-Allergy-Allergy-Read Code For Reaction' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 60311: 1) dates 
INSERT INTO cprd_cdm_test.test_results SELECT 60311 AS id, '1) dates ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '60311' AND observation_concept_id = '0' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = '2007-07-08' AND observation_source_value = '461-Miscellaneous-Repeat Medication Review-Due Date' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 60311 AS id, '2) dates' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '60311' AND observation_concept_id = '0' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = '2007-01-08' AND observation_source_value = '461-Miscellaneous-Repeat Medication Review-Seen By' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 61311: scores with 0 mapping
INSERT INTO cprd_cdm_test.test_results SELECT 61311 AS id, 'scores with 0 mapping' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '61311' AND observation_concept_id = '0' AND observation_type_concept_id = '38000280' AND value_as_string = '1JJ..00') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 62311: scores mapped
INSERT INTO cprd_cdm_test.test_results SELECT 62311 AS id, 'scores mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '62311' AND observation_concept_id = '40769009' AND observation_type_concept_id = '44814721' AND value_as_number = '500' AND observation_source_value = '372-0-10302') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 63311: scores mapped, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 63311 AS id, 'scores mapped, id is person_id' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '63311' AND observation_concept_id = '0' AND observation_source_value = '372-Diagnostic Tests-Scoring test result-Condition') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 64311: additional observation 114-2, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 64311 AS id, 'additional observation 114-2, id is person_id' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '64311' AND observation_concept_id = '0' AND observation_source_value = '114-Maternity-Preg out-Discharge Date') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 65311: additional observation 60-1 with SUM, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 65311 AS id, 'additional observation 60-1 with SUM, id is person_id' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '65311' AND observation_concept_id = '0' AND value_as_number = '8' AND observation_source_value = '60-Maternity-Ante-natal booking-Weeks gestation' AND unit_source_value = 'week') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 66311: accept is 0 so should be deleted
INSERT INTO cprd_cdm_test.test_results SELECT 66311 AS id, 'accept is 0 so should be deleted' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '66311') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 67311: valid
INSERT INTO cprd_cdm_test.test_results SELECT 67311 AS id, 'valid' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '67311' AND gender_concept_id = '8507' AND year_of_birth = '1999' AND month_of_birth = '1' AND care_site_id = '311' AND person_source_value = '67311' AND gender_source_value = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 68311: invalid: delete because crd 2013-01-01 > deathdate 2012-01-01
INSERT INTO cprd_cdm_test.test_results SELECT 68311 AS id, 'invalid: delete because crd 2013-01-01 > deathdate 2012-01-01' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '68311') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 69311: invalid: delete because crd 2013-01-01 > todate 2011-05-03
INSERT INTO cprd_cdm_test.test_results SELECT 69311 AS id, 'invalid: delete because crd 2013-01-01 > todate 2011-05-03' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '69311') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 70113: invalid: delete because uts 2014-01-01 > lcd 2012-12-01
INSERT INTO cprd_cdm_test.test_results SELECT 70113 AS id, 'invalid: delete because uts 2014-01-01 > lcd 2012-12-01' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '70113') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 71311: valid but mob =0 then MONTH_OF_BIRTH=NULL
INSERT INTO cprd_cdm_test.test_results SELECT 71311 AS id, 'valid but mob =0 then MONTH_OF_BIRTH=NULL' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '71311' AND gender_concept_id = '8507' AND year_of_birth = '1999' AND month_of_birth IS NULL AND care_site_id = '311' AND person_source_value = '71311' AND gender_source_value = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 72311: invalid year of birth 74
INSERT INTO cprd_cdm_test.test_results SELECT 72311 AS id, 'invalid year of birth 74' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '72311') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 73311: valid gender female
INSERT INTO cprd_cdm_test.test_results SELECT 73311 AS id, 'valid gender female' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '73311' AND gender_concept_id = '8532' AND care_site_id = '311' AND person_source_value = '73311' AND gender_source_value = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 74311: invalid not entered gender
INSERT INTO cprd_cdm_test.test_results SELECT 74311 AS id, 'invalid not entered gender' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '74311') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 75311: invalid Indeterminate gender
INSERT INTO cprd_cdm_test.test_results SELECT 75311 AS id, 'invalid Indeterminate gender' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '75311') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 76311: invalid unknown gender
INSERT INTO cprd_cdm_test.test_results SELECT 76311 AS id, 'invalid unknown gender' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '76311') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 77311: Read clinical procedure with visit
INSERT INTO cprd_cdm_test.test_results SELECT 77311 AS id, 'Read clinical procedure with visit' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '77311' AND procedure_concept_id = '4074106' AND procedure_date = '2012-01-01' AND procedure_type_concept_id = '38000275' AND provider_id = '1001' AND procedure_source_value = '7J46z00' AND procedure_source_concept_id = '45419444') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 78311: clinical procedure without visit
INSERT INTO cprd_cdm_test.test_results SELECT 78311 AS id, 'clinical procedure without visit' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '78311' AND procedure_concept_id = '4336549' AND procedure_date = '2012-03-01' AND procedure_type_concept_id = '38000275' AND provider_id = '1001' AND procedure_source_value = '7414200' AND procedure_source_concept_id = '45425628') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 79311: clinical procedure outside observation period
INSERT INTO cprd_cdm_test.test_results SELECT 79311 AS id, 'clinical procedure outside observation period' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '79311' AND procedure_concept_id = '4192131' AND procedure_type_concept_id = '38000275' AND procedure_source_concept_id = '45425639') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 80311: immunisation procedure
INSERT INTO cprd_cdm_test.test_results SELECT 80311 AS id, 'immunisation procedure' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '80311' AND procedure_concept_id = '4192131' AND procedure_date = '2011-03-01' AND procedure_type_concept_id = '38000275' AND provider_id = '1001' AND procedure_source_value = '744C.00' AND procedure_source_concept_id = '45425639') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 81311: referral procedure
INSERT INTO cprd_cdm_test.test_results SELECT 81311 AS id, 'referral procedure' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '81311' AND procedure_concept_id = '4192131' AND procedure_date = '2011-03-01' AND procedure_type_concept_id = '38000275' AND provider_id = '1001' AND procedure_source_value = '744C.00' AND procedure_source_concept_id = '45425639') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 82311: test procedure
INSERT INTO cprd_cdm_test.test_results SELECT 82311 AS id, 'test procedure' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '82311' AND procedure_concept_id = '4192131' AND procedure_date = '2011-03-01' AND procedure_type_concept_id = '38000275' AND provider_id = '1001' AND procedure_source_value = '215--744C.00' AND procedure_source_concept_id = '45425639') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 83: valid GP: role=2 (Partner); provider_concept_id=38004446 id is provider_id
INSERT INTO cprd_cdm_test.test_results SELECT 83 AS id, 'valid GP: role=2 (Partner); provider_concept_id=38004446 id is provider_id' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.provider WHERE provider_id = '83' AND specialty_concept_id = '38004514' AND specialty_source_value = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 84: valid GP: role=68 (Radiographer ); provider_concept_id=38004675 id is provider_id
INSERT INTO cprd_cdm_test.test_results SELECT 84 AS id, 'valid GP: role=68 (Radiographer ); provider_concept_id=38004675 id is provider_id' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.provider WHERE provider_id = '84' AND specialty_concept_id = '45756825' AND specialty_source_value = '68') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 85: valid GP: role=0 (Data Not Entered ) provider concept_id=38004514 id is provider_id
INSERT INTO cprd_cdm_test.test_results SELECT 85 AS id, 'valid GP: role=0 (Data Not Entered ) provider concept_id=38004514 id is provider_id' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.provider WHERE provider_id = '85' AND specialty_concept_id = '38004514' AND specialty_source_value = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 86555: Multiple consids on the same date but no event record, no visit created.
INSERT INTO cprd_cdm_test.test_results SELECT 86555 AS id, 'Multiple consids on the same date but no event record, no visit created.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.visit_occurrence WHERE person_id = '86555' AND visit_start_date = '2013-02-01' AND visit_end_date = '2013-02-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 87555: eventdate in CLINICAL is NULL	No VISIT_OCCURRENCE record created
INSERT INTO cprd_cdm_test.test_results SELECT 87555 AS id, 'eventdate in CLINICAL is NULL	No VISIT_OCCURRENCE record created' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.visit_occurrence WHERE person_id = '87555') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 88555: IMMUNISATION record occurs outside of a valid OBSERVATION_PERIOD, VISIT_OCCURRENCE record still created
INSERT INTO cprd_cdm_test.test_results SELECT 88555 AS id, 'IMMUNISATION record occurs outside of a valid OBSERVATION_PERIOD, VISIT_OCCURRENCE record still created' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.visit_occurrence WHERE person_id = '88555') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 89555: VISIT_OCCURRENCE - Two records on the same day create on VISIT_OCCURRENCE record
INSERT INTO cprd_cdm_test.test_results SELECT 89555 AS id, 'VISIT_OCCURRENCE - Two records on the same day create on VISIT_OCCURRENCE record' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.visit_occurrence WHERE person_id = '89555') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;