DROP TABLE IF EXISTS cprd_cdm_test.test_results;
CREATE TABLE cprd_cdm_test.test_results (id INT, description VARCHAR(512), test VARCHAR(256), status VARCHAR(5));
-- 311: Practice_id=301, region=13, id is care_site_id
INSERT INTO cprd_cdm_test.test_results SELECT 311 AS id, 'Practice_id=301, region=13, id is care_site_id' AS description, 'Expect care_site' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.care_site WHERE care_site_id = '311' AND location_id = '13') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 1111: Patient has Medical records that collapse in the Condition Era table
INSERT INTO cprd_cdm_test.test_results SELECT 1111 AS id, 'Patient has Medical records that collapse in the Condition Era table' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_era WHERE person_id = '1111' AND condition_concept_id = '75555' AND condition_era_start_date = '2012-01-01' AND condition_era_end_date = '2012-01-02' AND condition_occurrence_count = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 2111: Read clinical condition with visit, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 2111 AS id, 'Read clinical condition with visit, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '2111' AND condition_concept_id = '75555' AND condition_start_date = '2012-01-01' AND condition_type_concept_id = '32020' AND provider_id = '1001' AND condition_source_value = 'F563500' AND condition_source_concept_id = '45436713') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 2111 AS id, 'Read clinical condition with visit, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '2111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 3111: Read clinical condition, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 3111 AS id, 'Read clinical condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '3111' AND condition_concept_id = '195862' AND condition_start_date = '2012-03-01' AND condition_type_concept_id = '32020' AND provider_id = '1001' AND condition_source_value = 'K17y000' AND condition_source_concept_id = '45453481') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 3111 AS id, 'Read clinical condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '3111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 4111: Read clinical condition outside observation period, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 4111 AS id, 'Read clinical condition outside observation period, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '4111' AND condition_concept_id = '195862' AND condition_start_date = '2009-03-01' AND condition_type_concept_id = '32020' AND provider_id = '1001' AND condition_source_value = 'K17y000' AND condition_source_concept_id = '45453481') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 4111 AS id, 'Read clinical condition outside observation period, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '4111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 5111: Read immunisation condition, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 5111 AS id, 'Read immunisation condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '5111' AND condition_concept_id = '4123595' AND condition_start_date = '2011-03-01' AND condition_type_concept_id = '32020' AND provider_id = '1001' AND condition_source_value = 'J040.14' AND condition_source_concept_id = '45463565') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 5111 AS id, 'Read immunisation condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '5111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 6111: Read referral condition, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 6111 AS id, 'Read referral condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '6111' AND condition_concept_id = '377368' AND condition_start_date = '2011-03-01' AND condition_type_concept_id = '32020' AND provider_id = '1001' AND condition_source_value = 'P00..00' AND condition_source_concept_id = '45420722') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 6111 AS id, 'Read referral condition, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '6111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 7111: Read test condition with no visit, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 7111 AS id, 'Read test condition with no visit, id is person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '7111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 8111: drug era with 2 drug records, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 8111 AS id, 'drug era with 2 drug records, id is person_id' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_era WHERE person_id = '8111' AND drug_concept_id = '1316354' AND drug_era_start_date = '2012-01-01' AND drug_era_end_date = '2012-02-18' AND drug_exposure_count = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 8111 AS id, 'drug era with 2 drug records, id is person_id' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_era WHERE person_id = '8111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 9111: drug era with multilex drug code id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 9111 AS id, 'drug era with multilex drug code id is person_id' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_era WHERE person_id = '9111' AND drug_concept_id = '1177480' AND drug_era_start_date = '2012-01-31' AND drug_era_end_date = '2012-02-29' AND drug_exposure_count = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 9111 AS id, 'drug era with multilex drug code id is person_id' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_era WHERE person_id = '9111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 10111: testing the lookup for numdays does correct end date start+28 days, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 10111 AS id, 'testing the lookup for numdays does correct end date start+28 days, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '10111' AND drug_concept_id = '19073982' AND drug_exposure_end_date = '2012-1-29' AND refills = '1' AND quantity = '1' AND drug_source_value = '58976020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 10111 AS id, 'testing the lookup for numdays does correct end date start+28 days, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '10111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 11111: testing when there is no lookup available default to start dte, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 11111 AS id, 'testing when there is no lookup available default to start dte, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '11111' AND drug_concept_id = '1539463' AND drug_exposure_end_date = '2012-1-1' AND refills = '1' AND quantity = '1' AND drug_source_value = '72487020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 11111 AS id, 'testing when there is no lookup available default to start dte, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '11111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 12111: The drug records comes in without a valid days supply, no lookup in DAYSSUPPLY_DECODES, no lookups in DAYSSUPPLY_MODES, assume 1 day duration.Id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 12111 AS id, 'The drug records comes in without a valid days supply, no lookup in DAYSSUPPLY_DECODES, no lookups in DAYSSUPPLY_MODES, assume 1 day duration.Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '12111' AND drug_exposure_end_date = '2012-1-1' AND refills = '1' AND quantity = '1' AND drug_source_value = '93680020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 12111 AS id, 'The drug records comes in without a valid days supply, no lookup in DAYSSUPPLY_DECODES, no lookups in DAYSSUPPLY_MODES, assume 1 day duration.Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '12111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 13111: testing end date: You have a THERAPY.NUMDAYS = 40. Id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 13111 AS id, 'testing end date: You have a THERAPY.NUMDAYS = 40. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '13111' AND drug_concept_id = '19073982' AND drug_exposure_end_date = '2012-2-9' AND refills = '1' AND quantity = '1' AND drug_source_value = '58976020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 13111 AS id, 'testing end date: You have a THERAPY.NUMDAYS = 40. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '13111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 14111: testing end date: You have a THERAPY.NUMDAYS = 366 - show correct to 29 days using lookup. Id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 14111 AS id, 'testing end date: You have a THERAPY.NUMDAYS = 366 - show correct to 29 days using lookup. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '14111' AND drug_concept_id = '19073982' AND drug_exposure_end_date = '2012-1-29' AND refills = '1' AND quantity = '1' AND drug_source_value = '58976020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 14111 AS id, 'testing end date: You have a THERAPY.NUMDAYS = 366 - show correct to 29 days using lookup. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '14111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 15111: Test visit_occurrence_id: Drug is written to DRUG_EXPOSURE. Id is person_Id
INSERT INTO cprd_cdm_test.test_results SELECT 15111 AS id, 'Test visit_occurrence_id: Drug is written to DRUG_EXPOSURE. Id is person_Id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '15111' AND drug_concept_id = '19073982' AND drug_exposure_start_date = '2012-03-12' AND refills = '1' AND quantity = '1' AND drug_source_value = '58976020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 15111 AS id, 'Test visit_occurrence_id: Drug is written to DRUG_EXPOSURE. Id is person_Id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '15111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 16111: Drug date does exist within a valid observation period but does not have a consultation date. Id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 16111 AS id, 'Drug date does exist within a valid observation period but does not have a consultation date. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '16111' AND drug_concept_id = '19073982' AND drug_exposure_start_date = '2012-01-01' AND drug_exposure_end_date = '2012-1-29' AND refills = '1' AND quantity = '1' AND drug_source_value = '58976020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 16111 AS id, 'Drug date does exist within a valid observation period but does not have a consultation date. Id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '16111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 17111: PRODCODE = -1 - invalid.
INSERT INTO cprd_cdm_test.test_results SELECT 17111 AS id, 'PRODCODE = -1 - invalid.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '17111') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 18111: Invalid status, id = person_Id
INSERT INTO cprd_cdm_test.test_results SELECT 18111 AS id, 'Invalid status, id = person_Id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '18111') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 19111: valid immunization with visit, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 19111 AS id, 'valid immunization with visit, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '19111' AND drug_concept_id = '19136026' AND drug_exposure_start_date = '2012-01-01' AND drug_exposure_end_date = '2012-01-01' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 19111 AS id, 'valid immunization with visit, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '19111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 20111: valid immunization without visit - null visit_occur_id
INSERT INTO cprd_cdm_test.test_results SELECT 20111 AS id, 'valid immunization without visit - null visit_occur_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '20111' AND drug_concept_id = '19136026' AND drug_exposure_start_date = '2012-01-01' AND drug_exposure_end_date = '2012-01-01' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 20111 AS id, 'valid immunization without visit - null visit_occur_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '20111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 21111: Read  outside observation period, id = person_id
INSERT INTO cprd_cdm_test.test_results SELECT 21111 AS id, 'Read  outside observation period, id = person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '21111' AND drug_concept_id = '19136026' AND drug_exposure_start_date = '2009-03-01' AND drug_exposure_end_date = '2009-03-01' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 22111: immunization read code condition goes into conditions, id = person_id
INSERT INTO cprd_cdm_test.test_results SELECT 22111 AS id, 'immunization read code condition goes into conditions, id = person_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.condition_occurrence WHERE person_id = '22111') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 23111: valid read from clinical, id = patient$person_id
INSERT INTO cprd_cdm_test.test_results SELECT 23111 AS id, 'valid read from clinical, id = patient$person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '23111' AND drug_concept_id = '19136026' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 23111 AS id, 'valid read from clinical, id = patient$person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '23111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 24111: valid read from referral, id = person_id
INSERT INTO cprd_cdm_test.test_results SELECT 24111 AS id, 'valid read from referral, id = person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '24111' AND drug_concept_id = '19136026' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 24111 AS id, 'valid read from referral, id = person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '24111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 25111: valid read from test, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 25111 AS id, 'valid read from test, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '25111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 26111: valid entry, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 26111 AS id, 'valid entry, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '26111' AND drug_concept_id = '19136026' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 26111 AS id, 'valid entry, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '26111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 27111: valid entry, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 27111 AS id, 'valid entry, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '27111' AND drug_concept_id = '19136026' AND drug_type_concept_id = '38000177' AND drug_source_value = '65M2.00' AND drug_source_concept_id = '45432113') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 27111 AS id, 'valid entry, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '27111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 28111: valid entry, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 28111 AS id, 'valid entry, id is person_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.drug_exposure WHERE person_id = '28111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 29111: valid entry for device exposure, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 29111 AS id, 'valid entry for device exposure, id is person_id' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.device_exposure WHERE person_id = '29111' AND device_concept_id = '4192787' AND device_exposure_start_date = '2012-01-01' AND device_exposure_end_date = '2012-01-01' AND device_source_value = '9b20.00') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 30111: You have a valid PRODCODE but doesnt get an VOCAB mapping.PRODCODE = 46190. Id is person_Id
INSERT INTO cprd_cdm_test.test_results SELECT 30111 AS id, 'You have a valid PRODCODE but doesnt get an VOCAB mapping.PRODCODE = 46190. Id is person_Id' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.device_exposure WHERE person_id = '30111' AND device_concept_id = '21380480' AND device_exposure_start_date = '2012-01-01' AND device_source_value = '99978020') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 30111 AS id, 'You have a valid PRODCODE but doesnt get an VOCAB mapping.PRODCODE = 46190. Id is person_Id' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.device_exposure WHERE person_id = '30111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 31111: testing without hes to give visit_occurrence_id is null - clinical procedure without visit, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 31111 AS id, 'testing without hes to give visit_occurrence_id is null - clinical procedure without visit, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '31111' AND measurement_concept_id = '4132152' AND measurement_date = '2012-01-01' AND provider_id = '1001' AND measurement_source_value = '424Z.00' AND measurement_source_concept_id = '45508441') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 32111: Now test gold observation outside patient observation to exclude
INSERT INTO cprd_cdm_test.test_results SELECT 32111 AS id, 'Now test gold observation outside patient observation to exclude' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '32111' AND measurement_concept_id = '4132152' AND measurement_date = '2009-01-01' AND provider_id = '1001' AND measurement_source_value = '424Z.00' AND measurement_source_concept_id = '45508441') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 33111: immunisation procedure, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 33111 AS id, 'immunisation procedure, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '33111' AND measurement_concept_id = '4132152' AND measurement_date = '2011-03-01' AND provider_id = '1001' AND measurement_source_value = '424Z.00' AND measurement_source_concept_id = '45508441') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 34111: referral procedure, id is person_Id
INSERT INTO cprd_cdm_test.test_results SELECT 34111 AS id, 'referral procedure, id is person_Id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '34111' AND measurement_concept_id = '4132152' AND measurement_date = '2011-03-01' AND provider_id = '1001' AND measurement_source_value = '424Z.00' AND measurement_source_concept_id = '45508441') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 35111: test procedure, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 35111 AS id, 'test procedure, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '35111' AND measurement_concept_id = '4132152' AND measurement_date = '2011-03-01' AND provider_id = '1001' AND measurement_source_value = '215--424Z.00' AND measurement_source_concept_id = '45508441') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 36111: test observation record 4 fields no range values, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 36111 AS id, 'test observation record 4 fields no range values, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '36111' AND measurement_concept_id = '4132152' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702' AND value_as_concept_id = '45884153' AND measurement_source_value = '220--424Z.00' AND value_source_value = 'Normal') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 37111: test observation record 4 fields range low test, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 37111 AS id, 'test observation record 4 fields range low test, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '37111' AND measurement_concept_id = '4132152' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702' AND value_as_concept_id = '45884153' AND range_low = '1.2' AND measurement_source_value = '220--424Z.00' AND value_source_value = 'Normal') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 38111: test observation record 4 fields range high test, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 38111 AS id, 'test observation record 4 fields range high test, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '38111' AND measurement_concept_id = '4132152' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702' AND value_as_concept_id = '45884153' AND range_high = '4.3' AND measurement_source_value = '220--424Z.00' AND value_source_value = 'Normal') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 39111: test observation record 7 fields, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 39111 AS id, 'test observation record 7 fields, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '39111' AND measurement_concept_id = '4118981' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702' AND operator_concept_id = '4172703' AND value_as_number = '14.3' AND value_as_concept_id = '0' AND range_low = '11.5' AND range_high = '16.5' AND unit_concept_id = '8713' AND unit_source_value = 'g/dL') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 40111: test observation record enttype=284, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 40111 AS id, 'test observation record enttype=284, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '40111' AND measurement_concept_id = '4118981' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 41111: test observation record enttype=311, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 41111 AS id, 'test observation record enttype=311, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '41111' AND measurement_concept_id = '4118981' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 42111: test observation record enttype=154, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 42111 AS id, 'test observation record enttype=154, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '42111' AND measurement_concept_id = '4118981' AND measurement_date = '2012-01-01' AND measurement_type_concept_id = '44818702') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 43111: 1) additional observation, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 43111 AS id, '1) additional observation, id is person_id' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '43111' AND measurement_concept_id = '4154790' AND measurement_date = '2010-01-01' AND measurement_type_concept_id = '44818702' AND value_as_number = '80' AND measurement_source_value = '1-Examination Findings-Blood pressure-Diastolic') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 43111 AS id, '2) additional observation' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.measurement WHERE person_id = '43111' AND measurement_concept_id = '4152194' AND measurement_date = '2010-01-01' AND measurement_type_concept_id = '44818702' AND value_as_number = '160' AND measurement_source_value = '1-Examination Findings-Blood pressure-Systolic') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 44222: 201222: obs_period start should be uts and obs_period_end should be tod.
INSERT INTO cprd_cdm_test.test_results SELECT 44222 AS id, '201222: obs_period start should be uts and obs_period_end should be tod.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation_period WHERE person_id = '44222' AND observation_period_start_date = '2001-02-12' AND observation_period_end_date = '2010-01-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 44222 AS id, '201222: obs_period start should be uts and obs_period_end should be tod.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation_period WHERE person_id = '44222') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 45222: 202222: obs_period start should be crd and obs_period_end should be lcd since tod is null.
INSERT INTO cprd_cdm_test.test_results SELECT 45222 AS id, '202222: obs_period start should be crd and obs_period_end should be lcd since tod is null.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation_period WHERE person_id = '45222' AND observation_period_start_date = '2005-10-26' AND observation_period_end_date = '2011-11-11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 45222 AS id, '202222: obs_period start should be crd and obs_period_end should be lcd since tod is null.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation_period WHERE person_id = '45222') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 46222: 203222: patient deleted tod<uts.
INSERT INTO cprd_cdm_test.test_results SELECT 46222 AS id, '203222: patient deleted tod<uts.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation_period WHERE person_id = '46222') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 47111:  clinical procedure with visit
INSERT INTO cprd_cdm_test.test_results SELECT 47111 AS id, ' clinical procedure with visit' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '47111' AND observation_concept_id = '40479404' AND observation_date = '2012-01-01' AND observation_type_concept_id = '38000280' AND observation_source_value = '65PT.11' AND observation_source_concept_id = '45425506') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 47111 AS id, ' clinical procedure with visit' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '47111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 48111:  clinical procedure without visit
INSERT INTO cprd_cdm_test.test_results SELECT 48111 AS id, ' clinical procedure without visit' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '48111' AND observation_concept_id = '40479404' AND observation_date = '2012-03-01' AND observation_type_concept_id = '38000280' AND observation_source_value = '65PT.11' AND observation_source_concept_id = '45425506') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 49111:  clinical procedure outside observation period
INSERT INTO cprd_cdm_test.test_results SELECT 49111 AS id, ' clinical procedure outside observation period' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '49111' AND observation_concept_id = '4044812' AND observation_date = '2009-03-01' AND observation_source_value = 'R100.00' AND observation_source_concept_id = '45474099') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 50111: immunisation procedure
INSERT INTO cprd_cdm_test.test_results SELECT 50111 AS id, 'immunisation procedure' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '50111' AND observation_concept_id = '4044812' AND observation_date = '2011-03-01' AND observation_type_concept_id = '38000280' AND observation_source_value = 'R100.00' AND observation_source_concept_id = '45474099') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 51111: referral procedure
INSERT INTO cprd_cdm_test.test_results SELECT 51111 AS id, 'referral procedure' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '51111' AND observation_concept_id = '4044812' AND observation_date = '2011-03-01' AND observation_type_concept_id = '38000280' AND observation_source_value = 'R100.00' AND observation_source_concept_id = '45474099') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 52111: test procedure
INSERT INTO cprd_cdm_test.test_results SELECT 52111 AS id, 'test procedure' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '52111' AND observation_concept_id = '4044812' AND observation_date = '2011-03-01' AND observation_type_concept_id = '38000280' AND observation_source_value = '215--R100.00' AND observation_source_concept_id = '45474099') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 53111: observation not mapped
INSERT INTO cprd_cdm_test.test_results SELECT 53111 AS id, 'observation not mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '53111' AND observation_concept_id = '0' AND observation_date = '2011-03-01' AND observation_source_value = '215--Z5A6200' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 54111: Read clinical medical history condition non-mapped
INSERT INTO cprd_cdm_test.test_results SELECT 54111 AS id, 'Read clinical medical history condition non-mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '54111' AND observation_concept_id = '0' AND observation_date = '2011-01-01' AND observation_source_value = 'Z5A6200' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 55111: Read referral medical history condition non-mapped
INSERT INTO cprd_cdm_test.test_results SELECT 55111 AS id, 'Read referral medical history condition non-mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '55111' AND observation_concept_id = '0' AND observation_date = '2011-01-01' AND observation_source_value = 'Z5A6200' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 56111: Read test medical history condition non-mapped
INSERT INTO cprd_cdm_test.test_results SELECT 56111 AS id, 'Read test medical history condition non-mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '56111' AND observation_concept_id = '0' AND observation_date = '2011-01-01' AND observation_source_value = '215--Z5A6200' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 57111: Read immunisatoin medical history condition non-mapped
INSERT INTO cprd_cdm_test.test_results SELECT 57111 AS id, 'Read immunisatoin medical history condition non-mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '57111' AND observation_concept_id = '0' AND observation_date = '2011-01-01' AND observation_source_value = 'Z5A6200' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 58111: test observation record 4 fields
INSERT INTO cprd_cdm_test.test_results SELECT 58111 AS id, 'test observation record 4 fields' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '58111' AND observation_concept_id = '40479404' AND observation_date = '2012-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = 'Normal' AND observation_source_value = '215--65PT.11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 59111: test observation record 7 fields
INSERT INTO cprd_cdm_test.test_results SELECT 59111 AS id, 'test observation record 7 fields' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '59111' AND observation_concept_id = '4187457' AND observation_date = '2012-01-01' AND observation_type_concept_id = '38000280' AND value_as_number = '3.7' AND qualifier_concept_id = '4172703' AND observation_source_value = '412-Airway ...-66Ya.00' AND unit_source_value = '%') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 59111 AS id, 'test observation record 7 fields' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '59111') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 60111: 1) additional observation
INSERT INTO cprd_cdm_test.test_results SELECT 60111 AS id, '1) additional observation ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '60111' AND observation_concept_id = '0' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = '72487020' AND value_as_concept_id = '1539463' AND observation_source_value = '21-Allergy-Allergy-Drug Code' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 60111 AS id, '2) additional observation ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '60111' AND observation_concept_id = '0' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = 'Intolerance' AND observation_source_value = '21-Allergy-Allergy-Reaction Type' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 60111 AS id, '3) additional observation ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '60111' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_number = '3' AND observation_source_value = '21-Allergy-Allergy-Severity' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 60111 AS id, '4) additional observation ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '60111' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_number = '3' AND observation_source_value = '21-Allergy-Allergy-Certainty' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 60111 AS id, '4) additional observation ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '60111' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = 'M240012' AND observation_source_value = '21-Allergy-Allergy-Read Code For Reaction' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 61111: 1) dates
INSERT INTO cprd_cdm_test.test_results SELECT 61111 AS id, '1) dates ' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '61111' AND observation_concept_id = '0' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = '2007-07-08' AND observation_source_value = '461-Miscellaneous-Repeat Medication Review-Due Date' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cprd_cdm_test.test_results SELECT 61111 AS id, '2) dates' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '61111' AND observation_concept_id = '0' AND observation_date = '2010-01-01' AND observation_type_concept_id = '38000280' AND value_as_string = '2007-01-08' AND observation_source_value = '461-Miscellaneous-Repeat Medication Review-Seen By' AND observation_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 62111: scores with 0 mapping
INSERT INTO cprd_cdm_test.test_results SELECT 62111 AS id, 'scores with 0 mapping' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '62111' AND observation_concept_id = '0' AND observation_type_concept_id = '38000280' AND value_as_string = '1JJ..00') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 63111: scores mapped
INSERT INTO cprd_cdm_test.test_results SELECT 63111 AS id, 'scores mapped' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '63111' AND observation_concept_id = '40769009' AND observation_type_concept_id = '44814721' AND value_as_number = '500' AND observation_source_value = '372-0-10302') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 64111: scores mapped, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 64111 AS id, 'scores mapped, id is person_id' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '64111' AND observation_concept_id = '0' AND observation_source_value = '372-Diagnostic Tests-Scoring test result-Condition') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 65111: additional observation 114-2, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 65111 AS id, 'additional observation 114-2, id is person_id' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '65111' AND observation_concept_id = '0' AND observation_source_value = '114-Maternity-Preg out-Discharge Date') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 66111: additional observation 60-1 with SUM, id is person_id
INSERT INTO cprd_cdm_test.test_results SELECT 66111 AS id, 'additional observation 60-1 with SUM, id is person_id' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.observation WHERE person_id = '66111' AND observation_concept_id = '0' AND value_as_number = '8' AND observation_source_value = '60-Maternity-Ante-natal booking-Weeks gestation' AND unit_source_value = 'week') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 67111: accept is 0 so should be deleted
INSERT INTO cprd_cdm_test.test_results SELECT 67111 AS id, 'accept is 0 so should be deleted' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '67111') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 68111: valid
INSERT INTO cprd_cdm_test.test_results SELECT 68111 AS id, 'valid' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '68111' AND gender_concept_id = '8507' AND year_of_birth = '1999' AND month_of_birth = '1' AND care_site_id = '111' AND person_source_value = '68111' AND gender_source_value = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 69111: invalid: delete because crd 2013-01-01 > deathdate 2012-01-01
INSERT INTO cprd_cdm_test.test_results SELECT 69111 AS id, 'invalid: delete because crd 2013-01-01 > deathdate 2012-01-01' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '69111') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 70111: invalid: delete because crd 2013-01-01 > todate 2011-05-03
INSERT INTO cprd_cdm_test.test_results SELECT 70111 AS id, 'invalid: delete because crd 2013-01-01 > todate 2011-05-03' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '70111') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 71113: invalid: delete because uts 2014-01-01 > lcd 2012-12-01
INSERT INTO cprd_cdm_test.test_results SELECT 71113 AS id, 'invalid: delete because uts 2014-01-01 > lcd 2012-12-01' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '71113') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 72111: valid but mob =0 then MONTH_OF_BIRTH=NULL
INSERT INTO cprd_cdm_test.test_results SELECT 72111 AS id, 'valid but mob =0 then MONTH_OF_BIRTH=NULL' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '72111' AND gender_concept_id = '8507' AND year_of_birth = '1999' AND month_of_birth IS NULL AND care_site_id = '111' AND person_source_value = '72111' AND gender_source_value = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 73111: invalid year of birth 74
INSERT INTO cprd_cdm_test.test_results SELECT 73111 AS id, 'invalid year of birth 74' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '73111') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 74111: valid gender female
INSERT INTO cprd_cdm_test.test_results SELECT 74111 AS id, 'valid gender female' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '74111' AND gender_concept_id = '8532' AND care_site_id = '111' AND person_source_value = '74111' AND gender_source_value = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 75111: invalid not entered gender
INSERT INTO cprd_cdm_test.test_results SELECT 75111 AS id, 'invalid not entered gender' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '75111') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 76111: invalid Indeterminate gender
INSERT INTO cprd_cdm_test.test_results SELECT 76111 AS id, 'invalid Indeterminate gender' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '76111') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 77111: invalid unknown gender
INSERT INTO cprd_cdm_test.test_results SELECT 77111 AS id, 'invalid unknown gender' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.person WHERE person_id = '77111') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 78111: Read clinical procedure with visit
INSERT INTO cprd_cdm_test.test_results SELECT 78111 AS id, 'Read clinical procedure with visit' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '78111' AND procedure_concept_id = '4074106' AND procedure_date = '2012-01-01' AND procedure_type_concept_id = '38000275' AND provider_id = '1001' AND procedure_source_value = '7J46z00' AND procedure_source_concept_id = '45419444') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 79111: clinical procedure without visit
INSERT INTO cprd_cdm_test.test_results SELECT 79111 AS id, 'clinical procedure without visit' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '79111' AND procedure_concept_id = '4336549' AND procedure_date = '2012-03-01' AND procedure_type_concept_id = '38000275' AND provider_id = '1001' AND procedure_source_value = '7414200' AND procedure_source_concept_id = '45425628') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 80111: clinical procedure outside observation period
INSERT INTO cprd_cdm_test.test_results SELECT 80111 AS id, 'clinical procedure outside observation period' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '80111' AND procedure_concept_id = '4192131' AND procedure_type_concept_id = '38000275' AND procedure_source_concept_id = '45425639') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 81111: immunisation procedure
INSERT INTO cprd_cdm_test.test_results SELECT 81111 AS id, 'immunisation procedure' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '81111' AND procedure_concept_id = '4192131' AND procedure_date = '2011-03-01' AND procedure_type_concept_id = '38000275' AND provider_id = '1001' AND procedure_source_value = '744C.00' AND procedure_source_concept_id = '45425639') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 82111: referral procedure
INSERT INTO cprd_cdm_test.test_results SELECT 82111 AS id, 'referral procedure' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '82111' AND procedure_concept_id = '4192131' AND procedure_date = '2011-03-01' AND procedure_type_concept_id = '38000275' AND provider_id = '1001' AND procedure_source_value = '744C.00' AND procedure_source_concept_id = '45425639') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 83111: test procedure
INSERT INTO cprd_cdm_test.test_results SELECT 83111 AS id, 'test procedure' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.procedure_occurrence WHERE person_id = '83111' AND procedure_concept_id = '4192131' AND procedure_date = '2011-03-01' AND procedure_type_concept_id = '38000275' AND provider_id = '1001' AND procedure_source_value = '215--744C.00' AND procedure_source_concept_id = '45425639') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 84: valid GP: role=2 (Partner); provider_concept_id=38004446 id is provider_id
INSERT INTO cprd_cdm_test.test_results SELECT 84 AS id, 'valid GP: role=2 (Partner); provider_concept_id=38004446 id is provider_id' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.provider WHERE provider_id = '84' AND specialty_concept_id = '38004514' AND specialty_source_value = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 85: valid GP: role=68 (Radiographer ); provider_concept_id=38004675 id is provider_id
INSERT INTO cprd_cdm_test.test_results SELECT 85 AS id, 'valid GP: role=68 (Radiographer ); provider_concept_id=38004675 id is provider_id' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.provider WHERE provider_id = '85' AND specialty_concept_id = '45756825' AND specialty_source_value = '68') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 86: valid GP: role=0 (Data Not Entered ) provider concept_id=38004514 id is provider_id
INSERT INTO cprd_cdm_test.test_results SELECT 86 AS id, 'valid GP: role=0 (Data Not Entered ) provider concept_id=38004514 id is provider_id' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.provider WHERE provider_id = '86' AND specialty_concept_id = '38004514' AND specialty_source_value = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 87555: Multiple consides on the same date but no event record, no visit created.
INSERT INTO cprd_cdm_test.test_results SELECT 87555 AS id, 'Multiple consides on the same date but no event record, no visit created.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.visit_occurrence WHERE person_id = '87555' AND visit_start_date = '2013-02-01' AND visit_end_date = '2013-02-01') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 88555: eventdate in CLINICAL is NULL	No VISIT_OCCURRENCE record created
INSERT INTO cprd_cdm_test.test_results SELECT 88555 AS id, 'eventdate in CLINICAL is NULL	No VISIT_OCCURRENCE record created' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.visit_occurrence WHERE person_id = '88555') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 89555: IMMUNISATION record occurs outside of a valid OBSERVATION_PERIOD, VISIT_OCCURRENCE record still created
INSERT INTO cprd_cdm_test.test_results SELECT 89555 AS id, 'IMMUNISATION record occurs outside of a valid OBSERVATION_PERIOD, VISIT_OCCURRENCE record still created' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cprd_cdm_test.visit_occurrence WHERE person_id = '89555') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
