DROP TABLE IF EXISTS ccae_tests_cdm.test_results;
CREATE TABLE ccae_tests_cdm.test_results (id INT, description VARCHAR(512), test VARCHAR(256), status VARCHAR(5));
-- 1: Patient has two different primary diagnoses between inpatient_services and inpatient_admissions, two records created with condition_status of primary. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 1 AS id, 'Patient has two different primary diagnoses between inpatient_services and inpatient_admissions, two records created with condition_status of primary. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '1' AND condition_concept_id  = '4008576' AND condition_type_concept_id  = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 1 AS id, 'Patient has two different primary diagnoses between inpatient_services and inpatient_admissions, two records created with condition_status of primary. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '1' AND condition_concept_id  = '198337' AND condition_type_concept_id  = '32855') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 3: Patient has the same diagnosis code in outpatient_services and facility_header. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 3 AS id, 'Patient has the same diagnosis code in outpatient_services and facility_header. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '3' AND condition_concept_id  = '433706' AND condition_type_concept_id  = '32846' AND condition_status_source_value  = 'DX1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 3 AS id, 'Patient has the same diagnosis code in outpatient_services and facility_header. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '3' AND condition_concept_id  = '433706' AND condition_type_concept_id  = '32846' AND condition_status_source_value  = 'DX9') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 5: Patient has diagnosis in dx4 field in inpatient_services. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 5 AS id, 'Patient has diagnosis in dx4 field in inpatient_services. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '5' AND condition_concept_id  = '195587' AND condition_type_concept_id  = '32854' AND condition_status_source_value  = 'DX4') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 7: Patient has diagnosis in dx9 field in facility_header. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 7 AS id, 'Patient has diagnosis in dx9 field in facility_header. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '7' AND condition_concept_id  = '24970' AND condition_type_concept_id  = '32854' AND condition_status_source_value  = 'DX9') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 9: Patient has stdplac = 23 and diagnosis codes in the pdx and dx1 fields, ER record created. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 9 AS id, 'Patient has stdplac = 23 and diagnosis codes in the pdx and dx1 fields, ER record created. Id is PERSON_ID' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '9' AND visit_concept_id  = '9203') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 9 AS id, 'Patient has stdplac = 23 and diagnosis codes in the pdx and dx1 fields, ER record created. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '9' AND condition_concept_id  = '195587' AND condition_type_concept_id  = '32854' AND condition_status_source_value  = 'DX1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 9 AS id, 'Patient has stdplac = 23 and diagnosis codes in the pdx and dx1 fields, ER record created. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '9' AND condition_concept_id  = '24970' AND condition_type_concept_id  = '32854' AND condition_status_source_value  = 'PDX') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 11: Patient has diagnosis in a dx field that has domain=procedure, condition record moved to procedure_occurrence. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 11 AS id, 'Patient has diagnosis in a dx field that has domain=procedure, condition record moved to procedure_occurrence. Id is PERSON_ID' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '11' AND procedure_concept_id  = '4047347' AND procedure_type_concept_id  = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 11 AS id, 'Patient has diagnosis in a dx field that has domain=procedure, condition record moved to procedure_occurrence. Id is PERSON_ID' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '11' AND procedure_concept_id  = '46272569' AND procedure_type_concept_id  = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 13: Patient has diagnosis in a dx field that has domain=observation, condition record moved to observation. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 13 AS id, 'Patient has diagnosis in a dx field that has domain=observation, condition record moved to observation. Id is PERSON_ID' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation WHERE person_id  = '13' AND observation_concept_id  = '4117957' AND observation_type_concept_id  = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 15: Patient has diagnosis in a dx field that has domain=measurement, condition record moved to measurement. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 15 AS id, 'Patient has diagnosis in a dx field that has domain=measurement, condition record moved to measurement. Id is PERSON_ID' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '15' AND measurement_concept_id  = '4034850' AND measurement_type_concept_id  = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 17: Patient has icd10 diagnosis in a dx field with dxver=0, condition record created with icd10 mapped to snomed. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 17 AS id, 'Patient has icd10 diagnosis in a dx field with dxver=0, condition record created with icd10 mapped to snomed. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '17' AND condition_concept_id  = '438021' AND condition_type_concept_id  = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 19: patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, observation record created with icd10cm mapped to snomed. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 19 AS id, 'patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, observation record created with icd10cm mapped to snomed. Id is PERSON_ID' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation WHERE person_id  = '19' AND observation_concept_id  = '4155106' AND observation_type_concept_id  = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 19 AS id, 'patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, observation record created with icd10cm mapped to snomed. Id is PERSON_ID' AS description, 'Expect No condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '19' AND condition_concept_id  = '46270117') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 21: Patient has icd10 diagnosis after 10/1/2015 in a dx field with dxver=null, condition record created with icd10 mapped to snomed. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 21 AS id, 'Patient has icd10 diagnosis after 10/1/2015 in a dx field with dxver=null, condition record created with icd10 mapped to snomed. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '21' AND condition_concept_id  = '438021' AND condition_type_concept_id  = '32854' AND condition_source_concept_id  = '45602528') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 23: Patient has icd9 diagnosis before 10/1/2015 in a dx field with dxver=null, used ICD9. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 23 AS id, 'Patient has icd9 diagnosis before 10/1/2015 in a dx field with dxver=null, used ICD9. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '23' AND condition_concept_id  = '46270117' AND condition_type_concept_id  = '32854' AND condition_source_concept_id  = '44821630') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 25: Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 25 AS id, 'Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '25' AND condition_concept_id  = '195587' AND condition_start_date  = '2012-07-01' AND condition_type_concept_id  = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 25 AS id, 'Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '25' AND condition_concept_id  = '195587' AND condition_start_date  = '2012-08-02' AND condition_type_concept_id  = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 27: Event date is outside of observation_period, condition_occurrence record created. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 27 AS id, 'Event date is outside of observation_period, condition_occurrence record created. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '27' AND condition_concept_id  = '195587' AND condition_start_date  = '2022-08-02' AND condition_type_concept_id  = '32854') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 29: Condition_occurrence record default end_date is NULL. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 29 AS id, 'Condition_occurrence record default end_date is NULL. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '29' AND condition_concept_id  = '195587' AND condition_start_date  = '2022-08-03' AND condition_end_date  IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 31: HRA mapped to condition/drug the END_DATE is NULL. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 31 AS id, 'HRA mapped to condition/drug the END_DATE is NULL. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '31' AND condition_concept_id  = '134736' AND condition_start_date  = '2012-03-12' AND condition_end_date  IS NULL AND condition_status_concept_id  IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 33: Patient has 1 in CC_ASTHMA column, condition_source_value=Self-reported Asthma. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 33 AS id, 'Patient has 1 in CC_ASTHMA column, condition_source_value=Self-reported Asthma. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_occurrence WHERE person_id  = '33' AND condition_concept_id  = '317009' AND condition_start_date  = '2012-09-13' AND condition_status_concept_id  IS NULL AND condition_source_value  = 'CC_ASTHMA') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 35: Patient condition_concept_id of 0, no condition_era record created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 35 AS id, 'Patient condition_concept_id of 0, no condition_era record created. Id is PERSON_ID.' AS description, 'Expect No condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_era WHERE person_id  = '35') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 37: Two records with same condition_concept_id are less than 30 days apart, one condition_era record created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 37 AS id, 'Two records with same condition_concept_id are less than 30 days apart, one condition_era record created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_era WHERE person_id  = '37' AND condition_era_start_date  = '2012-07-01' AND condition_era_end_date  = '2012-07-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 39: Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 39 AS id, 'Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_era WHERE person_id  = '39' AND condition_era_start_date  = '2012-07-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 39 AS id, 'Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.condition_era WHERE person_id  = '39' AND condition_era_start_date  = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 41: Cost. Patient has values in ingcost, dispfee and AWP (HIX-1319). Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 41 AS id, 'Cost. Patient has values in ingcost, dispfee and AWP (HIX-1319). Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_domain_id  = 'Drug' AND total_cost  = '20' AND paid_patient_copay  = '20' AND paid_ingredient_cost  = '50' AND paid_dispensing_fee  = '25') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 43: Cost. Patient has cost values, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 43 AS id, 'Cost. Patient has cost values, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '43' AND procedure_concept_id  = '40757105' AND procedure_date  = '2012-06-11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 43 AS id, 'Cost. Patient has cost values, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_domain_id  = 'Procedure' AND paid_by_patient  = '160' AND paid_patient_copay  = '40' AND paid_patient_deductible  = '120') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 45: Cost. Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 45 AS id, 'Cost. Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '45' AND measurement_concept_id  = '2212375' AND measurement_date  = '2012-05-07') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 45 AS id, 'Cost. Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_domain_id  = 'Measurement' AND total_paid  = '157' AND paid_by_payer  = '120' AND paid_patient_copay  = '37') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 47: Cost. Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 47 AS id, 'Cost. Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation WHERE person_id  = '47' AND observation_concept_id  = '2721503' AND observation_date  = '2012-10-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 47 AS id, 'Cost. Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_domain_id  = 'Observation' AND paid_by_payer  = '75' AND paid_patient_coinsurance  = '100' AND paid_by_primary  = '52') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 49: Cost. Patient has cost values and revenue code, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 49 AS id, 'Cost. Patient has cost values and revenue code, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_domain_id  = 'Procedure' AND paid_by_patient  = '100' AND paid_patient_copay  = '80' AND paid_patient_deductible  = '20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 51: Cost. Testing DRG Populates (HIX-1431). Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 51 AS id, 'Cost. Testing DRG Populates (HIX-1431). Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_domain_id  = 'Procedure' AND paid_by_patient  = '100' AND paid_patient_copay  = '80' AND paid_patient_deductible  = '20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 53: Cost. Patient has cost values, cost is correctly associated with the right event_id (HIX-1515).
INSERT INTO ccae_tests_cdm.test_results SELECT 53 AS id, 'Cost. Patient has cost values, cost is correctly associated with the right event_id (HIX-1515).' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_event_id  IN (SELECT procedure_occurrence_id FROM ccae_tests_cdm.procedure_occurrence WHERE person_id = '53')) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 55: Cost. Patient has invalid revenue code, revenue_code_concept_id set to 0. Id is PERSON_ID. (HIX-1486)
INSERT INTO ccae_tests_cdm.test_results SELECT 55 AS id, 'Cost. Patient has invalid revenue code, revenue_code_concept_id set to 0. Id is PERSON_ID. (HIX-1486)' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_event_id  IN (SELECT procedure_occurrence_id FROM ccae_tests_cdm.procedure_occurrence WHERE person_id = '55') AND revenue_code_concept_id  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 57: Cost. DRUG_CLAIMS constants
INSERT INTO ccae_tests_cdm.test_results SELECT 57 AS id, 'Cost. DRUG_CLAIMS constants' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_event_id  IN (SELECT procedure_occurrence_id FROM ccae_tests_cdm.procedure_occurrence WHERE person_id = '57') AND cost_domain_id  = 'Visit Detail' AND cost_type_concept_id  = '32869' AND currency_concept_id  = '44818668' AND revenue_code_concept_id  = '0' AND drg_concept_id  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 59: Cost. OUTPATIENT_SERVICES constants
INSERT INTO ccae_tests_cdm.test_results SELECT 59 AS id, 'Cost. OUTPATIENT_SERVICES constants' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_event_id  IN (SELECT procedure_occurrence_id FROM ccae_tests_cdm.procedure_occurrence WHERE person_id = '59') AND cost_domain_id  = 'Visit Detail' AND cost_type_concept_id  = '32860' AND currency_concept_id  = '44818668' AND revenue_code_concept_id  = '0' AND drg_concept_id  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 61: Cost. INPATIENT_SERVICES constants
INSERT INTO ccae_tests_cdm.test_results SELECT 61 AS id, 'Cost. INPATIENT_SERVICES constants' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_event_id  IN (SELECT procedure_occurrence_id FROM ccae_tests_cdm.procedure_occurrence WHERE person_id = '61') AND cost_domain_id  = 'Visit Detail' AND cost_type_concept_id  = '32854' AND currency_concept_id  = '44818668' AND revenue_code_concept_id  = '0' AND drg_concept_id  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 63: Cost. INPATIENT_ADMISSIONS constants
INSERT INTO ccae_tests_cdm.test_results SELECT 63 AS id, 'Cost. INPATIENT_ADMISSIONS constants' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.cost WHERE cost_event_id  IN (SELECT procedure_occurrence_id FROM ccae_tests_cdm.procedure_occurrence WHERE person_id = '63') AND cost_domain_id  = 'Visit Detail' AND cost_type_concept_id  = '32855' AND currency_concept_id  = '44818668' AND revenue_code_concept_id  = '0' AND drg_concept_id  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 65: Duplicate drug records become one record in the CDM. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 65 AS id, 'Duplicate drug records become one record in the CDM. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '65' AND drug_concept_id  = '40161912' AND drug_exposure_start_date  = '2012-02-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 67: Negative daysupp should be 0 in cdm. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 67 AS id, 'Negative daysupp should be 0 in cdm. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '67' AND drug_concept_id  = '1545998' AND drug_exposure_start_date  = '2012-06-12' AND days_supply  = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 69: Daysupp >365 should be 365 in cdm. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 69 AS id, 'Daysupp >365 should be 365 in cdm. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '69' AND drug_concept_id  = '1545998' AND drug_exposure_start_date  = '2012-08-07' AND days_supply  = '365') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 71: CPT4 drug code in inpatient record moves to drug_exposure. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 71 AS id, 'CPT4 drug code in inpatient record moves to drug_exposure. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '71' AND drug_concept_id  = '46234006' AND drug_exposure_start_date  = '2012-08-09') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 73: Days supply is NULL but DRUG_EXPOSURE_END_DATE is set to DRUG_EXPOSURE_START_DATE (HIX-1430). Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 73 AS id, 'Days supply is NULL but DRUG_EXPOSURE_END_DATE is set to DRUG_EXPOSURE_START_DATE (HIX-1430). Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '73' AND drug_concept_id  = '46234006' AND drug_exposure_start_date  = '2012-08-09' AND drug_exposure_end_date  = '2012-08-09') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 75: Patient has 11 digit NDC that doesn''t map, should use first 9 digits instead. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 75 AS id, 'Patient has 11 digit NDC that doesn''t map, should use first 9 digits instead. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '75' AND drug_concept_id  = '46275250' AND drug_exposure_start_date  = '2012-01-17') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 77: Drug exposure quantity - if not populated in source, leave it NULL. Id is PERSON_ID. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 77 AS id, 'Drug exposure quantity - if not populated in source, leave it NULL. Id is PERSON_ID. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '77' AND drug_concept_id  = '46275250' AND drug_exposure_start_date  = '2012-01-19' AND quantity  IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 79: Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to DRUG_CONCEPT_ID=0 because of the date filter. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 79 AS id, 'Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to DRUG_CONCEPT_ID=0 because of the date filter. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '79' AND drug_concept_id  = '0' AND drug_exposure_start_date  = '2006-07-08') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 81: Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to correct DRUG_CONCEPT_ID because of the date filter. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 81 AS id, 'Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to correct DRUG_CONCEPT_ID because of the date filter. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '81' AND drug_concept_id  = '45775771' AND drug_exposure_start_date  = '2014-09-18') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 83: Tofacitinib mapps to 11-digit DRUG_SOURCE_CONCEPT_ID instead of 9-digit (HIX-1534)
INSERT INTO ccae_tests_cdm.test_results SELECT 83 AS id, 'Tofacitinib mapps to 11-digit DRUG_SOURCE_CONCEPT_ID instead of 9-digit (HIX-1534)' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '83' AND drug_source_concept_id  = '45332969') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 85: Event date is outside of observation_period, drug_exposure record created. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 85 AS id, 'Event date is outside of observation_period, drug_exposure record created. Id is PERSON_ID' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '85' AND drug_exposure_start_date  = '2019-09-18') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 87: Source_concept_ids must vary for different dates
INSERT INTO ccae_tests_cdm.test_results SELECT 87 AS id, 'Source_concept_ids must vary for different dates' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '87' AND drug_concept_id  = '19124326' AND drug_exposure_start_date  = '1970-01-01' AND drug_exposure_end_date  = '2014-11-10' AND drug_source_concept_id  = '2718911') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 87 AS id, 'Source_concept_ids must vary for different dates' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '87' AND drug_concept_id  = '0' AND drug_exposure_start_date  = '2014-11-11' AND drug_exposure_end_date  = '2023-06-30' AND drug_source_concept_id  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 87 AS id, 'Source_concept_ids must vary for different dates' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_exposure WHERE person_id  = '87' AND drug_concept_id  = '1302318' AND drug_exposure_start_date  = '2023-07-01' AND drug_exposure_end_date  = '2099-12-31' AND drug_source_concept_id  = '2100003123') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 89: Two drugs with same ingredient within 30 days, should be one drug era. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 89 AS id, 'Two drugs with same ingredient within 30 days, should be one drug era. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_era WHERE person_id  = '89' AND drug_concept_id  = '1134439' AND drug_era_start_date  = '2012-02-04' AND gap_days  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 91: Two drugs with same ingredient within 30 days, but 10 gap days. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 91 AS id, 'Two drugs with same ingredient within 30 days, but 10 gap days. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_era WHERE person_id  = '91' AND drug_concept_id  = '1134439' AND drug_era_start_date  = '2012-02-04' AND gap_days  = '11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 93: Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 93 AS id, 'Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_era WHERE person_id  = '93' AND drug_concept_id  = '1134439' AND drug_era_start_date  = '2012-02-04' AND gap_days  = '12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 93 AS id, 'Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.' AS description, 'Expect 1 drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_era WHERE person_id  = '93') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 95: Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 95 AS id, 'Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_era WHERE person_id  = '95' AND drug_concept_id  = '1134439' AND drug_era_start_date  = '2012-09-21' AND gap_days  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 95 AS id, 'Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_era WHERE person_id  = '95' AND drug_concept_id  = '1134439' AND drug_era_start_date  = '2012-12-08' AND gap_days  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 97: Drug_era_end_date should be drug start date + days supply. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 97 AS id, 'Drug_era_end_date should be drug start date + days supply. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_era WHERE person_id  = '97' AND drug_concept_id  = '956874' AND drug_era_start_date  = '2010-12-08' AND drug_era_end_date  = '2010-12-21') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 99: Drug era created from procedure drug. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 99 AS id, 'Drug era created from procedure drug. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_era WHERE person_id  = '99' AND drug_concept_id  = '19135830' AND drug_era_start_date  = '2012-03-26') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 101: Drug with two ingredients should have two drug eras. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 101 AS id, 'Drug with two ingredients should have two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_era WHERE person_id  = '101' AND drug_concept_id  = '1134439' AND drug_era_start_date  = '2010-05-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 101 AS id, 'Drug with two ingredients should have two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.drug_era WHERE person_id  = '101' AND drug_concept_id  = '1112807' AND drug_era_start_date  = '2010-05-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 105: Location record generated for egeoloc 11. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 105 AS id, 'Location record generated for egeoloc 11. Id is PERSON_ID' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.location WHERE state  = 'NJ' AND location_source_value  = '11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 106: Only one location record generated for 89. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 106 AS id, 'Only one location record generated for 89. Id is PERSON_ID' AS description, 'Expect 1 location' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.location WHERE state  = 'UN' AND location_source_value  = '89') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 107: Only one location record generated for 38. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 107 AS id, 'Only one location record generated for 38. Id is PERSON_ID' AS description, 'Expect 1 location' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.location WHERE state  = 'VA' AND location_source_value  = '38') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 110: Svcdate is outside of observation period, record is kept. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 110 AS id, 'Svcdate is outside of observation period, record is kept. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '110') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 112: Patient has abnormal=L; value as concept_id = 4267416. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 112 AS id, 'Patient has abnormal=L; value as concept_id = 4267416. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '112' AND value_as_concept_id  = '4267416') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 114: Patient has abnormal=H; value as concept_id = 4267416. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 114 AS id, 'Patient has abnormal=H; value as concept_id = 4267416. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '114' AND value_as_concept_id  = '4328749') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 116: Patient has abnormal=N; value as concept_id = 4267416. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 116 AS id, 'Patient has abnormal=N; value as concept_id = 4267416. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '116' AND value_as_concept_id  = '4069590') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 118: Patient has abnormal=A; value as concept_id = 4267416. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 118 AS id, 'Patient has abnormal=A; value as concept_id = 4267416. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '118' AND value_as_concept_id  = '4135493') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 120: Patient has abnormal=+; value as concept_id = 4267416. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 120 AS id, 'Patient has abnormal=+; value as concept_id = 4267416. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '120' AND value_as_concept_id  = '9191') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 122: Patient has result ne 0 and > neg 99999, result listed in value as number field. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 122 AS id, 'Patient has result ne 0 and > neg 99999, result listed in value as number field. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '122' AND value_as_number  = '120') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 124: Patient lowercase units, maps to unit_concept_id 8840 (HIX-1183). Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 124 AS id, 'Patient lowercase units, maps to unit_concept_id 8840 (HIX-1183). Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '124' AND value_as_number  = '100' AND unit_concept_id  = '8840') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 126: For UNIT_CONCEPT_ID UCUM lookup should not be used, use JNJ_UNITS istead. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 126 AS id, 'For UNIT_CONCEPT_ID UCUM lookup should not be used, use JNJ_UNITS istead. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '126' AND unit_concept_id  = '8739') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 128: For UNIT_CONCEPT_ID UCUM lookup should not be used, use JNJ_UNITS istead. 586323 concept_id is expected. 9471 is a wrong UCUM derived unit. Id is a PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 128 AS id, 'For UNIT_CONCEPT_ID UCUM lookup should not be used, use JNJ_UNITS istead. 586323 concept_id is expected. 9471 is a wrong UCUM derived unit. Id is a PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '128' AND unit_concept_id  = '586323') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 130: Patient has null in resunit, measurement record have unit_concept_id = NULL and unit_source_concept_id = NULL. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 130 AS id, 'Patient has null in resunit, measurement record have unit_concept_id = NULL and unit_source_concept_id = NULL. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '130' AND unit_concept_id  IS NULL AND unit_source_concept_id  IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 132: for LOINCs 3142-7, 29463-7, 3141-9 sometimes padded with 0000, strip padding (HIX-1418). Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 132 AS id, 'for LOINCs 3142-7, 29463-7, 3141-9 sometimes padded with 0000, strip padding (HIX-1418). Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '132' AND value_as_number  = '150' AND unit_concept_id  = '8739') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 134: Patient has REFHIGH and REFLOW mapping correctly. Check to ensure floats convert correctly. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 134 AS id, 'Patient has REFHIGH and REFLOW mapping correctly. Check to ensure floats convert correctly. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '134' AND range_low  = '1' AND range_high  = '10.8') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 136: Patient has a LOINC of 3142-7, 29463-7, 3141-9 and RESULT > 100000 and RESUNIT = ''LBS''
INSERT INTO ccae_tests_cdm.test_results SELECT 136 AS id, 'Patient has a LOINC of 3142-7, 29463-7, 3141-9 and RESULT > 100000 and RESUNIT = ''LBS''' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '136' AND value_as_number  = '195' AND unit_concept_id  = '8739') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 138: Event date is outside of observation_period, measurement record created. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 138 AS id, 'Event date is outside of observation_period, measurement record created. Id is PERSON_ID' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '138' AND measurement_date  = '2022-04-06') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 140: Patient has weight 201, value_as_string = null, value_as_number=201. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 140 AS id, 'Patient has weight 201, value_as_string = null, value_as_number=201. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '140' AND measurement_date  = '2012-07-16' AND value_as_number  = '201' AND measurement_source_value  = 'WEIGHT') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 142: BMI is only question answered bmi is only record created in observation . Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 142 AS id, 'BMI is only question answered bmi is only record created in observation . Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '142' AND measurement_date  = '2012-09-22' AND value_as_number  = '28.6' AND measurement_source_value  = 'BMI') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 144: Subsumed enrollment test where two enrollment durations with the second subsumed by the first results in a single observation. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 144 AS id, 'Subsumed enrollment test where two enrollment durations with the second subsumed by the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation_period WHERE person_id  = '144' AND observation_period_start_date  = '2012-01-01' AND observation_period_end_date  = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 144 AS id, 'Subsumed enrollment test where two enrollment durations with the second subsumed by the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect 1 observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation_period WHERE person_id  = '144') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 145: Combine enrollment test where two enrollment durations with the second within 30 days of the first results in a single observation. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 145 AS id, 'Combine enrollment test where two enrollment durations with the second within 30 days of the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation_period WHERE person_id  = '145' AND observation_period_start_date  = '2012-05-01' AND observation_period_end_date  = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 145 AS id, 'Combine enrollment test where two enrollment durations with the second within 30 days of the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect 1 observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation_period WHERE person_id  = '145') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 146: Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 146 AS id, 'Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation_period WHERE person_id  = '146' AND observation_period_start_date  = '2012-01-01' AND observation_period_end_date  = '2012-06-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 146 AS id, 'Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation_period WHERE person_id  = '146' AND observation_period_start_date  = '2012-08-02' AND observation_period_end_date  = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 147: Test two duplicate enrollment records results in a single observation. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 147 AS id, 'Test two duplicate enrollment records results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation_period WHERE person_id  = '147' AND observation_period_start_date  = '2012-01-01' AND observation_period_end_date  = '2012-12-25') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 147 AS id, 'Test two duplicate enrollment records results in a single observation. Id is PERSON_ID.' AS description, 'Expect 1 observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation_period WHERE person_id  = '147' AND observation_period_start_date  = '2012-01-01' AND observation_period_end_date  = '2012-12-25') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 148: PERIOD_TYPE_CONCEPT_ID=32813
INSERT INTO ccae_tests_cdm.test_results SELECT 148 AS id, 'PERIOD_TYPE_CONCEPT_ID=32813' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation_period WHERE person_id  = '148' AND period_type_concept_id  = '32813') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 149: SVCDATE is outside of observation_period, measurement record created . Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 149 AS id, 'SVCDATE is outside of observation_period, measurement record created . Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '149' AND measurement_date  = '2013-10-13' AND value_as_number  = '20.0' AND measurement_source_value  = 'BMI') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 151: Patient answered 3 for question EXERWEEK, value_as_number=3. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 151 AS id, 'Patient answered 3 for question EXERWEEK, value_as_number=3. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation WHERE person_id  = '151' AND observation_date  = '2012-05-25' AND value_as_number  = '3' AND observation_source_value  = 'EXERWEEK') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 153: Patient has 2 in CGTPKAMT column, value_as_number=1 pack per day or more. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 153 AS id, 'Patient has 2 in CGTPKAMT column, value_as_number=1 pack per day or more. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation WHERE person_id  = '153' AND observation_date  = '2012-03-14' AND value_as_number  = '2.00' AND observation_source_value  = 'CGTPKAMT') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 155: Patient answered 1 for question FLU_SHOT, observation record created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 155 AS id, 'Patient answered 1 for question FLU_SHOT, observation record created. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation WHERE person_id  = '155' AND observation_source_value  = 'FLU_SHOT') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 157: Event date is outside of observation_period, observation record created. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 157 AS id, 'Event date is outside of observation_period, observation record created. Id is PERSON_ID' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.observation WHERE person_id  = '157' AND observation_date  = '2022-03-14' AND value_as_number  = '2.00' AND observation_source_value  = 'CGTPKAMT') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 159: Person does not have prescription benefits and is excluded. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 159 AS id, 'Person does not have prescription benefits and is excluded. Id is PERSON_ID.' AS description, 'Expect No payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '159') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 160: Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 160 AS id, 'Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '160' AND payer_plan_period_start_date  = '2013-01-01' AND payer_plan_period_end_date  = '2013-01-31' AND payer_source_value  = 'N Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 160 AS id, 'Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '160' AND payer_plan_period_start_date  = '2013-05-01' AND payer_plan_period_end_date  = '2013-05-31' AND payer_source_value  = 'N Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 161: Person has a gap of <32 days between enrollment periods with the same payer_source_value; person has ONE records. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 161 AS id, 'Person has a gap of <32 days between enrollment periods with the same payer_source_value; person has ONE records. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '161' AND payer_plan_period_start_date  = '2013-01-01' AND payer_plan_period_end_date  = '2013-02-28' AND payer_source_value  = 'N Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 161 AS id, 'Person has a gap of <32 days between enrollment periods with the same payer_source_value; person has ONE records. Id is PERSON_ID.' AS description, 'Expect 1 payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '161') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 162: Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 162 AS id, 'Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '162' AND payer_plan_period_start_date  = '2012-04-01' AND payer_plan_period_end_date  = '2012-04-06' AND payer_source_value  = 'C Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 162 AS id, 'Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '162' AND payer_plan_period_start_date  = '2012-04-07' AND payer_plan_period_end_date  = '2012-04-30' AND payer_source_value  = 'C Commercial POS') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 163: Family source value derived from ENROLID. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 163 AS id, 'Family source value derived from ENROLID. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '163' AND payer_plan_period_start_date  = '2012-04-01' AND payer_plan_period_end_date  = '2012-04-30' AND payer_source_value  = 'C Commercial PPO' AND family_source_value  = '000000001') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 164: Person does not have prescription benefits and is excluded. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 164 AS id, 'Person does not have prescription benefits and is excluded. Id is PERSON_ID.' AS description, 'Expect No payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '164') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 165: Payer_source_value 11
INSERT INTO ccae_tests_cdm.test_results SELECT 165 AS id, 'Payer_source_value 11' AS description, 'Expect No payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '165' AND payer_source_value  = '') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 165 AS id, 'Payer_source_value 11' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '165' AND payer_source_value  = 'N Commercial Basic/Major Medical') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 166: Payer_source_value 22
INSERT INTO ccae_tests_cdm.test_results SELECT 166 AS id, 'Payer_source_value 22' AS description, 'Expect No payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '166' AND payer_source_value  = '') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 166 AS id, 'Payer_source_value 22' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.payer_plan_period WHERE person_id  = '166' AND payer_source_value  = 'C Commercial Comprehensive') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 167: Person with two genders is excluded. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 167 AS id, 'Person with two genders is excluded. Id is PERSON_ID.' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '167') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 168: Person with two birth years >2 yrs apart is excluded. Note person is <90 years old for MDCD test. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 168 AS id, 'Person with two birth years >2 yrs apart is excluded. Note person is <90 years old for MDCD test. Id is PERSON_ID.' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '168') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 169: Person with two birth years <2 yrs apart is kept with last birth year selected. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 169 AS id, 'Person with two birth years <2 yrs apart is kept with last birth year selected. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '169' AND year_of_birth  = '1971') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 170: Person born before 1900 is excluded. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 170 AS id, 'Person born before 1900 is excluded. Id is PERSON_ID.' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '170') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 171: Person born after the current year is excluded. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 171 AS id, 'Person born after the current year is excluded. Id is PERSON_ID.' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '171') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 172: Person born in 2014 but enrolled in 2012 is excluded. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 172 AS id, 'Person born in 2014 but enrolled in 2012 is excluded. Id is PERSON_ID.' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '172') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 173: Person born in 2013 but enrolled in 2012 is kept, latest birth year taken. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 173 AS id, 'Person born in 2013 but enrolled in 2012 is kept, latest birth year taken. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '173' AND year_of_birth  = '2013') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 174: Person with two enrollment_detail records has one person record. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 174 AS id, 'Person with two enrollment_detail records has one person record. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '174' AND year_of_birth  = '1980') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 174 AS id, 'Person with two enrollment_detail records has one person record. Id is PERSON_ID.' AS description, 'Expect 1 person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '174') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 175: Person with sex=3 is excluded. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 175 AS id, 'Person with sex=3 is excluded. Id is PERSON_ID.' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '175') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 176: Person born after current year. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 176 AS id, 'Person born after current year. Id is PERSON_ID.' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '176') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 177: Person has record with sex=3 but last record has sex=1, person is kept. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 177 AS id, 'Person has record with sex=3 but last record has sex=1, person is kept. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '177' AND gender_concept_id  = '8507') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 178: Person born the same year as enrolled, use first enrollment month to impute month of birth and day of birth. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 178 AS id, 'Person born the same year as enrolled, use first enrollment month to impute month of birth and day of birth. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '178' AND year_of_birth  = '2012' AND month_of_birth  = '4' AND day_of_birth  = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 179: sex=1 => gender_concept_id=8507
INSERT INTO ccae_tests_cdm.test_results SELECT 179 AS id, 'sex=1 => gender_concept_id=8507' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '179' AND gender_concept_id  = '8507') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 180: sex=2 => gender_concept_id=8532
INSERT INTO ccae_tests_cdm.test_results SELECT 180 AS id, 'sex=2 => gender_concept_id=8532' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '180' AND gender_concept_id  = '8532') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 181: sex=3 => discarded
INSERT INTO ccae_tests_cdm.test_results SELECT 181 AS id, 'sex=3 => discarded' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '181') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 182: Person. Constants
INSERT INTO ccae_tests_cdm.test_results SELECT 182 AS id, 'Person. Constants' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '182' AND race_concept_id  = '0' AND ethnicity_concept_id  = '0' AND gender_source_concept_id  = '0' AND race_source_concept_id  = '0' AND ethnicity_source_concept_id  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 183: Person with Rx benefits is kept. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 183 AS id, 'Person with Rx benefits is kept. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '183') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 184: Person without Rx benefits is excluded. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 184 AS id, 'Person without Rx benefits is excluded. Id is PERSON_ID.' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '184') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 185: Person with last enrollment_detail record that has egeoloc=11 gets associated to NJ. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 185 AS id, 'Person with last enrollment_detail record that has egeoloc=11 gets associated to NJ. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.person WHERE person_id  = '185') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 186: Patient has a value in PPROC and PROC1 within inpatient_services. Two records should be created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 186 AS id, 'Patient has a value in PPROC and PROC1 within inpatient_services. Two records should be created. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '186' AND procedure_concept_id  = '2514413' AND procedure_date  = '2000-01-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 186 AS id, 'Patient has a value in PPROC and PROC1 within inpatient_services. Two records should be created. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '186' AND procedure_concept_id  = '2514404' AND procedure_date  = '2000-01-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 188: Patient has two PPROC values, two are created, one with inpatient claim detail and the other with inpatient claim header as the procedure_type_concept. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 188 AS id, 'Patient has two PPROC values, two are created, one with inpatient claim detail and the other with inpatient claim header as the procedure_type_concept. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '188' AND procedure_concept_id  = '40757105' AND procedure_date  = '2012-06-11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 188 AS id, 'Patient has two PPROC values, two are created, one with inpatient claim detail and the other with inpatient claim header as the procedure_type_concept. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '188' AND procedure_concept_id  = '40757126' AND procedure_date  = '2012-06-11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 190: If event date is outside of observation_period, procedure_occurrence record created anyway. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 190 AS id, 'If event date is outside of observation_period, procedure_occurrence record created anyway. Id is PERSON_ID' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '190' AND procedure_date  = '2022-06-11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 192: Procedure occurrence quantity - if not populated in source, leave it NULL. Id is PERSON_ID
INSERT INTO ccae_tests_cdm.test_results SELECT 192 AS id, 'Procedure occurrence quantity - if not populated in source, leave it NULL. Id is PERSON_ID' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '192' AND procedure_date  = '2022-05-15' AND quantity  IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 194: Patient has two different providers for the same procedure, two records should be created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 194 AS id, 'Patient has two different providers for the same procedure, two records should be created. Id is PERSON_ID.' AS description, 'Expect 2 procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '194' AND procedure_concept_id  = '4021253' AND procedure_date  = '2012-10-20') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 196: Patient has HCPCS procedure code with value in PROCMOD. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 196 AS id, 'Patient has HCPCS procedure code with value in PROCMOD. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '196' AND procedure_concept_id  = '4196153' AND procedure_date  = '2012-05-12' AND modifier_concept_id  = '4320556') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 198: Patient has two records for the same procedure, two records created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 198 AS id, 'Patient has two records for the same procedure, two records created. Id is PERSON_ID.' AS description, 'Expect 2 procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '198' AND procedure_concept_id  = '4200063' AND procedure_date  = '2012-02-15' AND procedure_type_concept_id  = '32846') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 200: Patient has procedure in proc5 position in facility header, procedure_type_concept_id = 32846 Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 200 AS id, 'Patient has procedure in proc5 position in facility header, procedure_type_concept_id = 32846 Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '200' AND procedure_type_concept_id  = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 200 AS id, 'Patient has procedure in proc5 position in facility header, procedure_type_concept_id = 32846 Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '200' AND procedure_concept_id  = '2313827' AND procedure_type_concept_id  = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 202: Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 202 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '202' AND procedure_concept_id  = '4180942' AND procedure_type_concept_id  = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 202 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '202' AND procedure_concept_id  = '2314322' AND procedure_type_concept_id  = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 202 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '202' AND procedure_concept_id  = '40757149' AND procedure_type_concept_id  = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 202 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.procedure_occurrence WHERE person_id  = '202' AND procedure_concept_id  = '42739018' AND procedure_type_concept_id  = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 202 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '202' AND measurement_concept_id  = '4167674' AND measurement_type_concept_id  = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 202 AS id, 'Patient has procedures in proc1 - proc6 positions in facility header, procedure_type_concept_id = 32846. Record should be created for each procedure. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.measurement WHERE person_id  = '202' AND measurement_concept_id  = '709845' AND measurement_type_concept_id  = '32846') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 204: Provider in facility header table with stdprov=220, specialty = emergency medicine. Id is PROVIDER_SOURCE_VALUE
INSERT INTO ccae_tests_cdm.test_results SELECT 204 AS id, 'Provider in facility header table with stdprov=220, specialty = emergency medicine. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.provider WHERE specialty_concept_id  = '38004510' AND specialty_source_value  = '220') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 206: Provider in facility header table with stdprov=''. Id is PROVIDER_SOURCE_VALUE
INSERT INTO ccae_tests_cdm.test_results SELECT 206 AS id, 'Provider in facility header table with stdprov=''. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.provider WHERE specialty_concept_id  = '38004514') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 208: Provider in outpatient_services table with stdprov=285, specialty = infectious disease. Id is PROVIDER_SOURCE_VALUE
INSERT INTO ccae_tests_cdm.test_results SELECT 208 AS id, 'Provider in outpatient_services table with stdprov=285, specialty = infectious disease. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.provider WHERE specialty_concept_id  = '38004484' AND specialty_source_value  = '285') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 210: provider in inpatient_services table with stdprov=540, specialty = cardiac surgery. Id is PROVIDER_SOURCE_VALUE
INSERT INTO ccae_tests_cdm.test_results SELECT 210 AS id, 'provider in inpatient_services table with stdprov=540, specialty = cardiac surgery. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.provider WHERE specialty_concept_id  = '38004497' AND specialty_source_value  = '540') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 212: provider in lab table with stdprov =22, specialty = addiction medicine. Id is PROVIDER_SOURCE_VALUE
INSERT INTO ccae_tests_cdm.test_results SELECT 212 AS id, 'provider in lab table with stdprov =22, specialty = addiction medicine. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.provider WHERE specialty_concept_id  = '38004498' AND specialty_source_value  = '22') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 214: Even when PROVID IS NULL create a PROVIDER (HIX-1404). Id is PROVIDER_SOURCE_VALUE
INSERT INTO ccae_tests_cdm.test_results SELECT 214 AS id, 'Even when PROVID IS NULL create a PROVIDER (HIX-1404). Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.provider WHERE provider_source_value  IS NULL AND specialty_source_value  = '220') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 216: Provider. Constants
INSERT INTO ccae_tests_cdm.test_results SELECT 216 AS id, 'Provider. Constants' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.provider WHERE specialty_concept_id  = '0' AND care_site_id  = '0' AND gender_concept_id  = '0' AND gender_source_concept_id  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 218: Patient with visit detail that starts before the observation period, start date trimmed to beginning of observation period. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 218 AS id, 'Patient with visit detail that starts before the observation period, start date trimmed to beginning of observation period. Id is PERSON_ID.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_detail WHERE person_id  = '218' AND visit_detail_start_date  = '2012-01-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 220: svcdate>tsvcdate, visit_end_date is svcdate. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 220 AS id, 'svcdate>tsvcdate, visit_end_date is svcdate. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '220' AND visit_start_date  = '2012-03-21' AND visit_end_date  = '2012-03-21') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 222: Service falls during observation period but ends after the period ends, visit_end_date is not trimmed to the observation_period_end_date. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 222 AS id, 'Service falls during observation period but ends after the period ends, visit_end_date is not trimmed to the observation_period_end_date. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '222' AND visit_start_date  = '2012-12-30' AND visit_end_date  = '2013-01-08') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 224: service in inpatient_services with stdplac of 23, visit classified as ER. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 224 AS id, 'service in inpatient_services with stdplac of 23, visit classified as ER. Id is PERSON_ID.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_detail WHERE person_id  = '224' AND visit_detail_concept_id  = '8870' AND visit_detail_start_date  = '2012-04-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 226: Two visits created, expect a visit with a PRECEDING_VISIT_OCCURRENCE_ID. Id is PERSON_ID. (HIX-1521)
INSERT INTO ccae_tests_cdm.test_results SELECT 226 AS id, 'Two visits created, expect a visit with a PRECEDING_VISIT_OCCURRENCE_ID. Id is PERSON_ID. (HIX-1521)' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '226' AND visit_start_date  = '2012-10-01' AND preceding_visit_occurrence_id  IN (SELECT visit_occurrence_id FROM ccae_tests_cdm.visit_occurrence WHERE person_id = '226' AND visit_start_date = '2012-08-08')) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 228: patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 228 AS id, 'patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '228' AND visit_start_date  = '2012-08-08' AND visit_end_date  = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO ccae_tests_cdm.test_results SELECT 228 AS id, 'patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '228' AND visit_start_date  = '2012-10-01' AND visit_end_date  = '2012-10-05') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 230: Patient has an ER record that starts and ends on the first day of the IP visit, one ER visit created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 230 AS id, 'Patient has an ER record that starts and ends on the first day of the IP visit, one ER visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '230' AND visit_concept_id  = '262' AND visit_start_date  = '2012-09-03' AND visit_end_date  = '2012-09-10') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 232: Patient has two lines in the inpatient_services table where the difference between the end_date of one line and the start_date of the next is <= 1, one visit created. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 232 AS id, 'Patient has two lines in the inpatient_services table where the difference between the end_date of one line and the start_date of the next is <= 1, one visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '232' AND visit_start_date  = '2012-05-15' AND visit_end_date  = '2012-05-17') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 234: Setting discharged_to_concept_id for IP Record (HIX-1429). Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 234 AS id, 'Setting discharged_to_concept_id for IP Record (HIX-1429). Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '234' AND visit_start_date  = '2012-03-21' AND visit_end_date  = '2012-03-21' AND discharged_to_concept_id  = '581476') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 236: If event date is outside of observation_period, visit_occurrence record created anyway. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 236 AS id, 'If event date is outside of observation_period, visit_occurrence record created anyway. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '236' AND visit_start_date  = '2022-03-21' AND visit_end_date  = '2022-03-21' AND discharged_to_concept_id  = '581476') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 238: Patient has record in outpatient_services table but no rx benefits, visit dropped. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 238 AS id, 'Patient has record in outpatient_services table but no rx benefits, visit dropped. Id is PERSON_ID.' AS description, 'Expect No visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '238') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 240: Patient has two records in the same visit with different provid and provstd. Id is PERSON_ID.
INSERT INTO ccae_tests_cdm.test_results SELECT 240 AS id, 'Patient has two records in the same visit with different provid and provstd. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM ccae_tests_cdm.visit_occurrence WHERE person_id  = '240' AND visit_start_date  = '2012-08-08' AND visit_end_date  = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;