DROP TABLE IF EXISTS optum_extended_cdm_test.test_results;
CREATE TABLE optum_extended_cdm_test.test_results (id INT, description VARCHAR(512), test VARCHAR(256), status VARCHAR(5));
-- 25: Person location test (DOD)
INSERT INTO optum_extended_cdm_test.test_results SELECT 25 AS id, 'Person location test (DOD)' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.location WHERE location_source_value = 'PA') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 26: Tests if 2 enrollment durations (where second is subsumed by the first) results in a single observation period
INSERT INTO optum_extended_cdm_test.test_results SELECT 26 AS id, 'Tests if 2 enrollment durations (where second is subsumed by the first) results in a single observation period' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation_period WHERE person_id = '26') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 27: Tests if 2 enrollment durations (where second is within 30 days of first) results in a single observation period
INSERT INTO optum_extended_cdm_test.test_results SELECT 27 AS id, 'Tests if 2 enrollment durations (where second is within 30 days of first) results in a single observation period' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation_period WHERE person_id = '27') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 28: Tests if 2 enrollment durations (where second starts 33 days after first) results in two observation periods
INSERT INTO optum_extended_cdm_test.test_results SELECT 28 AS id, 'Tests if 2 enrollment durations (where second starts 33 days after first) results in two observation periods' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation_period WHERE person_id = '28') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 29: Tests when patient has multiple payers active in the same time window.
INSERT INTO optum_extended_cdm_test.test_results SELECT 29 AS id, 'Tests when patient has multiple payers active in the same time window.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '29') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 30: Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 30 AS id, 'Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '30' AND payer_concept_id = '281' AND payer_source_value = 'MCR0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 31: Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 31 AS id, 'Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '31' AND payer_concept_id = '327' AND payer_source_value = 'COM0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 32: Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 32 AS id, 'Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '32' AND payer_source_value = 'COM0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 33: Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 33 AS id, 'Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '33' AND payer_source_value = 'COM0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 34: Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 34 AS id, 'Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '34' AND payer_source_value = 'COM0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 35: Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 35 AS id, 'Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '35' AND payer_concept_id = '275' AND payer_source_value = 'COM1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 36: Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 36 AS id, 'Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '36' AND payer_source_value = 'COM Health Maint Org') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 37: Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 37 AS id, 'Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '37' AND payer_concept_id = '276' AND payer_source_value = 'COM2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 38: Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 38 AS id, 'Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '38' AND payer_source_value = 'COM0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 39: Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 39 AS id, 'Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '39' AND payer_source_value = 'COM0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 40: Patient has multiple payer plan periods that should be collapsed based on PAYER_SOURCE_VALUE and PLAN_SOURCE_VALUE
INSERT INTO optum_extended_cdm_test.test_results SELECT 40 AS id, 'Patient has multiple payer plan periods that should be collapsed based on PAYER_SOURCE_VALUE and PLAN_SOURCE_VALUE' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id = '40') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 41: A person defined with year of birth is 0, id is person_id
INSERT INTO optum_extended_cdm_test.test_results SELECT 41 AS id, 'A person defined with year of birth is 0, id is person_id' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '41') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 42: A person defined with year of birth > 1 year after the earliest coverage start from patient history
INSERT INTO optum_extended_cdm_test.test_results SELECT 42 AS id, 'A person defined with year of birth > 1 year after the earliest coverage start from patient history' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '42') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 43: Person with a Gender source value of M
INSERT INTO optum_extended_cdm_test.test_results SELECT 43 AS id, 'Person with a Gender source value of M' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '43' AND gender_concept_id = '8507') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 44: Person with a Gender source value of F
INSERT INTO optum_extended_cdm_test.test_results SELECT 44 AS id, 'Person with a Gender source value of F' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '44' AND gender_concept_id = '8532') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 45: Person with a Gender source value of U
INSERT INTO optum_extended_cdm_test.test_results SELECT 45 AS id, 'Person with a Gender source value of U' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '45') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 46: Person with 2 YOBs that are have a MIN/MAX(YOB) > 2 years apart
INSERT INTO optum_extended_cdm_test.test_results SELECT 46 AS id, 'Person with 2 YOBs that are have a MIN/MAX(YOB) > 2 years apart' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '46') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 47: Person who flips gender across different OPs
INSERT INTO optum_extended_cdm_test.test_results SELECT 47 AS id, 'Person who flips gender across different OPs' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '47') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 48: Month of birth test: Month should be mapped
INSERT INTO optum_extended_cdm_test.test_results SELECT 48 AS id, 'Month of birth test: Month should be mapped' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '48' AND month_of_birth = '3') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 49: Month of birth test: Month should NOT be mapped
INSERT INTO optum_extended_cdm_test.test_results SELECT 49 AS id, 'Month of birth test: Month should NOT be mapped' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '49' AND month_of_birth IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 50: Day of birth test: Day should be mapped
INSERT INTO optum_extended_cdm_test.test_results SELECT 50 AS id, 'Day of birth test: Day should be mapped' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '50' AND day_of_birth = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 51: Day of birth test: Day should NOT be mapped
INSERT INTO optum_extended_cdm_test.test_results SELECT 51 AS id, 'Day of birth test: Day should NOT be mapped' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '51' AND day_of_birth IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 52: SES Person who has Asian race
INSERT INTO optum_extended_cdm_test.test_results SELECT 52 AS id, 'SES Person who has Asian race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '52' AND race_concept_id = '8515' AND ethnicity_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 53: SES Person who has Black race
INSERT INTO optum_extended_cdm_test.test_results SELECT 53 AS id, 'SES Person who has Black race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '53' AND race_concept_id = '8516' AND ethnicity_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 54: SES Person who has White race
INSERT INTO optum_extended_cdm_test.test_results SELECT 54 AS id, 'SES Person who has White race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '54' AND race_concept_id = '8527' AND ethnicity_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 55: SES Person who has Unknown race
INSERT INTO optum_extended_cdm_test.test_results SELECT 55 AS id, 'SES Person who has Unknown race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '55' AND race_concept_id = '0' AND ethnicity_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 56: Person who has Hispanic ethnicity
INSERT INTO optum_extended_cdm_test.test_results SELECT 56 AS id, 'Person who has Hispanic ethnicity' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id = '56' AND race_concept_id = '0' AND ethnicity_concept_id = '38003563') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 57: Patient has 2 medical records which have the same proc code listed in proc position 1-3, with repeated PROC_CD in both records.
INSERT INTO optum_extended_cdm_test.test_results SELECT 57 AS id, 'Patient has 2 medical records which have the same proc code listed in proc position 1-3, with repeated PROC_CD in both records.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id = '57' AND procedure_concept_id = '2211331') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 57 AS id, 'Patient has 2 medical records which have the same proc code listed in proc position 1-3, with repeated PROC_CD in both records.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id = '57' AND procedure_concept_id = '43527998') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 59: Patient has medical records which have some valid and invalid formatted PROC codes.
INSERT INTO optum_extended_cdm_test.test_results SELECT 59 AS id, 'Patient has medical records which have some valid and invalid formatted PROC codes.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id = '59' AND procedure_concept_id = '43527998') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 59 AS id, 'Patient has medical records which have some valid and invalid formatted PROC codes.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id = '59' AND procedure_concept_id = '0' AND procedure_source_value = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 61: Patient has a series of 3 inpatient visits with same dates and procedure codes in separate records.
INSERT INTO optum_extended_cdm_test.test_results SELECT 61 AS id, 'Patient has a series of 3 inpatient visits with same dates and procedure codes in separate records.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id = '61' AND procedure_concept_id = '2211331') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 61 AS id, 'Patient has a series of 3 inpatient visits with same dates and procedure codes in separate records.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id = '61' AND procedure_concept_id = '43527998') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 61 AS id, 'Patient has a series of 3 inpatient visits with same dates and procedure codes in separate records.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id = '61') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 63: Creates a provider entry from a record found in RX and MEDICAL table for a single patient.
INSERT INTO optum_extended_cdm_test.test_results SELECT 63 AS id, 'Creates a provider entry from a record found in RX and MEDICAL table for a single patient.' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.provider WHERE provider_source_value = '123456') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 63 AS id, 'Creates a provider entry from a record found in RX and MEDICAL table for a single patient.' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.provider WHERE npi = 'NPI63' AND dea = 'DEA63' AND provider_source_value = 'NPI63-DEA63') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 65: Creates multiple IP admission claims with different pat_planids, should get a single IP visit occurrence.
INSERT INTO optum_extended_cdm_test.test_results SELECT 65 AS id, 'Creates multiple IP admission claims with different pat_planids, should get a single IP visit occurrence.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id = '65' AND visit_concept_id = '9201') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 65 AS id, 'Creates multiple IP admission claims with different pat_planids, should get a single IP visit occurrence.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id = '65' AND visit_detail_concept_id = '9201') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 67: Creates an Inpatient Visit Occurrence for a patient with a single medical diagnosis.
INSERT INTO optum_extended_cdm_test.test_results SELECT 67 AS id, 'Creates an Inpatient Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id = '67' AND visit_concept_id = '9201') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 67 AS id, 'Creates an Inpatient Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id = '67' AND visit_detail_concept_id = '9201') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 69: Creates an Outpatient Visit Occurrence for a patient with a single medical diagnosis.
INSERT INTO optum_extended_cdm_test.test_results SELECT 69 AS id, 'Creates an Outpatient Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id = '69' AND visit_concept_id = '9202') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 69 AS id, 'Creates an Outpatient Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id = '69' AND visit_detail_concept_id = '9202') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 71: Creates an Emergency Room Visit Occurrence for a patient with a single medical diagnosis.
INSERT INTO optum_extended_cdm_test.test_results SELECT 71 AS id, 'Creates an Emergency Room Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id = '71' AND visit_concept_id = '9203') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 71 AS id, 'Creates an Emergency Room Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id = '71' AND visit_detail_concept_id = '8870') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 73: Creates an Long Term Care Visit Occurrence for a patient with a single medical diagnosis.
INSERT INTO optum_extended_cdm_test.test_results SELECT 73 AS id, 'Creates an Long Term Care Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id = '73' AND visit_concept_id = '42898160') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 73 AS id, 'Creates an Long Term Care Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id = '73' AND visit_detail_concept_id = '8615') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 75: Patient has a series of diagnoses that fall outside of their Observation Period, but record stays the same.
INSERT INTO optum_extended_cdm_test.test_results SELECT 75 AS id, 'Patient has a series of diagnoses that fall outside of their Observation Period, but record stays the same.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id = '75' AND visit_concept_id = '9202' AND visit_start_date = '2009-07-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;