IF OBJECT_ID('optum_extended_cdm_test.test_results', 'U') IS NOT NULL DROP TABLE optum_extended_cdm_test.test_results;
CREATE TABLE optum_extended_cdm_test.test_results (id INT, description VARCHAR(512), test VARCHAR(256), status VARCHAR(5));
-- 1: CARE_SITE - Creates a CARE_SITE entry from a record found in native provider table where prov_type is NULL.
INSERT INTO optum_extended_cdm_test.test_results SELECT 1 AS id, 'CARE_SITE - Creates a CARE_SITE entry from a record found in native provider table where prov_type is NULL.' AS description, 'Expect care_site' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.care_site WHERE care_site_id  = '1' AND place_of_service_concept_id  = '0' AND care_site_source_value  = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 2: CARE_SITE - Creates a CARE_SITE entry from a record found in native provider table where prov_type = 2.
INSERT INTO optum_extended_cdm_test.test_results SELECT 2 AS id, 'CARE_SITE - Creates a CARE_SITE entry from a record found in native provider table where prov_type = 2.' AS description, 'Expect care_site' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.care_site WHERE care_site_id  = '2' AND place_of_service_concept_id  = '8717' AND care_site_source_value  = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 3: CARE_SITE - Creates a CARE_SITE entry from a record found in native provider table where prov_type = 3.
INSERT INTO optum_extended_cdm_test.test_results SELECT 3 AS id, 'CARE_SITE - Creates a CARE_SITE entry from a record found in native provider table where prov_type = 3.' AS description, 'Expect care_site' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.care_site WHERE care_site_id  = '3' AND place_of_service_concept_id  = '38004693' AND care_site_source_value  = '3') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 4: CARE_SITE - Creates a CARE_SITE entry from a record found in native provider table where prov_type = 4.
INSERT INTO optum_extended_cdm_test.test_results SELECT 4 AS id, 'CARE_SITE - Creates a CARE_SITE entry from a record found in native provider table where prov_type = 4.' AS description, 'Expect care_site' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.care_site WHERE care_site_id  = '4' AND place_of_service_concept_id  = '0' AND care_site_source_value  = '4') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 6: CARE_SITE - Creates a CARE_SITE entry from an Rx_claims record
INSERT INTO optum_extended_cdm_test.test_results SELECT 6 AS id, 'CARE_SITE - Creates a CARE_SITE entry from an Rx_claims record' AS description, 'Expect care_site' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.care_site WHERE care_site_id  = '6' AND place_of_service_concept_id  = '38004340' AND care_site_source_value  = '6') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 8: CONDITION_ERA - Patient has Medical records (some which are Concept_ID = 0) that both collapse and stay separate in the Condition Era table
INSERT INTO optum_extended_cdm_test.test_results SELECT 8 AS id, 'CONDITION_ERA - Patient has Medical records (some which are Concept_ID = 0) that both collapse and stay separate in the Condition Era table' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_era WHERE person_id  = '8' AND condition_concept_id  = '141095' AND condition_occurrence_count  = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 8 AS id, 'CONDITION_ERA - Patient has Medical records (some which are Concept_ID = 0) that both collapse and stay separate in the Condition Era table' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_era WHERE person_id  = '8' AND condition_concept_id  = '31317' AND condition_occurrence_count  = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 8 AS id, 'CONDITION_ERA - Patient has Medical records (some which are Concept_ID = 0) that both collapse and stay separate in the Condition Era table' AS description, 'Expect No condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_era WHERE person_id  = '8' AND condition_concept_id  = '0') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 13: CONDITION_OCCURRENCE - Patient has 1 record in med_diagnosis with diag in position 1
INSERT INTO optum_extended_cdm_test.test_results SELECT 13 AS id, 'CONDITION_OCCURRENCE - Patient has 1 record in med_diagnosis with diag in position 1' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '13' AND condition_concept_id  = '141095' AND condition_type_concept_id  = '32810' AND condition_status_concept_id  = '32901') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 15: CONDITION_OCCURRENCE - Patient has 1 record in med_diagnosis with diag in position 4
INSERT INTO optum_extended_cdm_test.test_results SELECT 15 AS id, 'CONDITION_OCCURRENCE - Patient has 1 record in med_diagnosis with diag in position 4' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '15' AND condition_concept_id  = '141095' AND condition_type_concept_id  = '32810') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 17: CONDITION_OCCURRENCE - Patient has medical records which have some valid and invalid formatted DIAG codes.
INSERT INTO optum_extended_cdm_test.test_results SELECT 17 AS id, 'CONDITION_OCCURRENCE - Patient has medical records which have some valid and invalid formatted DIAG codes.' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '17' AND condition_concept_id  = '141095') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 17 AS id, 'CONDITION_OCCURRENCE - Patient has medical records which have some valid and invalid formatted DIAG codes.' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '17' AND condition_concept_id  = '0' AND condition_source_value  = '99999') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 19: CONDITION_OCCURRENCE - Patient has a series of 3 inpatient visits with same dates and diagnoses in separate records.
INSERT INTO optum_extended_cdm_test.test_results SELECT 19 AS id, 'CONDITION_OCCURRENCE - Patient has a series of 3 inpatient visits with same dates and diagnoses in separate records.' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '19' AND condition_concept_id  = '141095') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 19 AS id, 'CONDITION_OCCURRENCE - Patient has a series of 3 inpatient visits with same dates and diagnoses in separate records.' AS description, 'Expect 3 condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '19') != 3 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 21: CONDITION_OCCURRENCE - Creates two Condition Occurrences from a single Medical row that specifies an ICD9 code that has multiple SNOMED mappings.
INSERT INTO optum_extended_cdm_test.test_results SELECT 21 AS id, 'CONDITION_OCCURRENCE - Creates two Condition Occurrences from a single Medical row that specifies an ICD9 code that has multiple SNOMED mappings.' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '21' AND condition_concept_id  = '443727' AND condition_source_value  = '24910') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 21 AS id, 'CONDITION_OCCURRENCE - Creates two Condition Occurrences from a single Medical row that specifies an ICD9 code that has multiple SNOMED mappings.' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '21' AND condition_concept_id  = '195771' AND condition_source_value  = '24910') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 21 AS id, 'CONDITION_OCCURRENCE - Creates two Condition Occurrences from a single Medical row that specifies an ICD9 code that has multiple SNOMED mappings.' AS description, 'Expect 2 condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '21') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 23: CONDITION_OCCURRENCE - Tests ICD10 CM vs International
INSERT INTO optum_extended_cdm_test.test_results SELECT 23 AS id, 'CONDITION_OCCURRENCE - Tests ICD10 CM vs International' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '23' AND condition_concept_id  = '43020481' AND condition_source_value  = 'Z731') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 23 AS id, 'CONDITION_OCCURRENCE - Tests ICD10 CM vs International' AS description, 'Expect No condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '23' AND condition_source_value  = 'Z731' AND condition_source_concept_id  = '45581067') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 27: Tests POA = Y;01
INSERT INTO optum_extended_cdm_test.test_results SELECT 27 AS id, 'Tests POA = Y;01' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '27' AND condition_status_concept_id  = '32901' AND condition_status_source_value  = 'Y;01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 29: Tests POA = N;01
INSERT INTO optum_extended_cdm_test.test_results SELECT 29 AS id, 'Tests POA = N;01' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '29' AND condition_status_concept_id  = '32902' AND condition_status_source_value  = 'N;01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 31: Tests POA = U;01
INSERT INTO optum_extended_cdm_test.test_results SELECT 31 AS id, 'Tests POA = U;01' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '31' AND condition_status_concept_id  = '32902' AND condition_status_source_value  = 'U;01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 33: Tests POA = W;01
INSERT INTO optum_extended_cdm_test.test_results SELECT 33 AS id, 'Tests POA = W;01' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '33' AND condition_status_concept_id  = '32902' AND condition_status_source_value  = 'W;01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 35: DEVICE - Patient has NDC source codes mapping to domain Device
INSERT INTO optum_extended_cdm_test.test_results SELECT 35 AS id, 'DEVICE - Patient has NDC source codes mapping to domain Device' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '35' AND visit_concept_id  = '9201') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 35 AS id, 'DEVICE - Patient has NDC source codes mapping to domain Device' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.device_exposure WHERE person_id  = '35' AND device_concept_id  = '46358737' AND device_source_value  = '24840153001') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 35 AS id, 'DEVICE - Patient has NDC source codes mapping to domain Device' AS description, 'Expect No condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '35') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 37: DEVICE - Patient has proc source codes mapping to domain Device, does not get mapped to Procedure
INSERT INTO optum_extended_cdm_test.test_results SELECT 37 AS id, 'DEVICE - Patient has proc source codes mapping to domain Device, does not get mapped to Procedure' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '37' AND visit_concept_id  = '9202') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 37 AS id, 'DEVICE - Patient has proc source codes mapping to domain Device, does not get mapped to Procedure' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.device_exposure WHERE person_id  = '37' AND device_source_value  = 'K0901') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 37 AS id, 'DEVICE - Patient has proc source codes mapping to domain Device, does not get mapped to Procedure' AS description, 'Expect No procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '37' AND procedure_source_value  = 'K0901') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 39: DEVICE - Patient has proc source codes in medical_claims mapping to domain Device and visit_place_of_service of OP does not get mapped to Procedure
INSERT INTO optum_extended_cdm_test.test_results SELECT 39 AS id, 'DEVICE - Patient has proc source codes in medical_claims mapping to domain Device and visit_place_of_service of OP does not get mapped to Procedure' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '39' AND visit_concept_id  = '9202') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 39 AS id, 'DEVICE - Patient has proc source codes in medical_claims mapping to domain Device and visit_place_of_service of OP does not get mapped to Procedure' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.device_exposure WHERE person_id  = '39' AND device_source_value  = 'K0901') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 39 AS id, 'DEVICE - Patient has proc source codes in medical_claims mapping to domain Device and visit_place_of_service of OP does not get mapped to Procedure' AS description, 'Expect No procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '39' AND procedure_source_value  = 'K0901') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 41: DRUG_EXPOSURE - Patient has 2 RX records, the first within the enrollment period, the second outside of enrollment.
INSERT INTO optum_extended_cdm_test.test_results SELECT 41 AS id, 'DRUG_EXPOSURE - Patient has 2 RX records, the first within the enrollment period, the second outside of enrollment.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.drug_exposure WHERE person_id  = '41' AND drug_concept_id  = '1322189' AND drug_source_value  = '55111067101') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 41 AS id, 'DRUG_EXPOSURE - Patient has 2 RX records, the first within the enrollment period, the second outside of enrollment.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '41' AND visit_concept_id  = '581458' AND visit_start_date  = '2013-10-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 41 AS id, 'DRUG_EXPOSURE - Patient has 2 RX records, the first within the enrollment period, the second outside of enrollment.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.drug_exposure WHERE person_id  = '41' AND drug_concept_id  = '0' AND drug_source_value  = '58487000102') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 41 AS id, 'DRUG_EXPOSURE - Patient has 2 RX records, the first within the enrollment period, the second outside of enrollment.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '41' AND visit_concept_id  = '581458' AND visit_start_date  = '2013-12-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 43: DRUG_EXPOSURE - Patient has multiple RX records, all within enrollment period, but have the same patid, pat_planid, ndc.
INSERT INTO optum_extended_cdm_test.test_results SELECT 43 AS id, 'DRUG_EXPOSURE - Patient has multiple RX records, all within enrollment period, but have the same patid, pat_planid, ndc.' AS description, 'Expect 3 drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.drug_exposure WHERE person_id  = '43') != 3 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 43 AS id, 'DRUG_EXPOSURE - Patient has multiple RX records, all within enrollment period, but have the same patid, pat_planid, ndc.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '43' AND visit_concept_id  = '581458' AND visit_start_date  = '2013-10-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 43 AS id, 'DRUG_EXPOSURE - Patient has multiple RX records, all within enrollment period, but have the same patid, pat_planid, ndc.' AS description, 'Expect 1 visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '43') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 43 AS id, 'DRUG_EXPOSURE - Patient has multiple RX records, all within enrollment period, but have the same patid, pat_planid, ndc.' AS description, 'Expect 3 visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '43') != 3 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 45: DRUG_EXPOSURE - Patient has procedure in MEDICAL_CLAIMS that should map to a DRUG_EXPOSURE record.
INSERT INTO optum_extended_cdm_test.test_results SELECT 45 AS id, 'DRUG_EXPOSURE - Patient has procedure in MEDICAL_CLAIMS that should map to a DRUG_EXPOSURE record.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.drug_exposure WHERE person_id  = '45' AND drug_concept_id  = '41212830') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 47: DRUG_EXPOSURE - Patient has procedure in MED_PROCEDURE.
INSERT INTO optum_extended_cdm_test.test_results SELECT 47 AS id, 'DRUG_EXPOSURE - Patient has procedure in MED_PROCEDURE.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.drug_exposure WHERE person_id  = '47' AND drug_concept_id  = '41212830') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 47 AS id, 'DRUG_EXPOSURE - Patient has procedure in MED_PROCEDURE.' AS description, 'Expect No procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '47') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 49: DRUG_EXPOSURE - NDC codes from Medical map to drug exposure
INSERT INTO optum_extended_cdm_test.test_results SELECT 49 AS id, 'DRUG_EXPOSURE - NDC codes from Medical map to drug exposure' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.drug_exposure WHERE person_id  = '49' AND drug_concept_id  = '1322189' AND drug_source_value  = '55111067101') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 51: DRUG_EXPOSURE - Proc codes from lab results map to drug exposure
INSERT INTO optum_extended_cdm_test.test_results SELECT 51 AS id, 'DRUG_EXPOSURE - Proc codes from lab results map to drug exposure' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.drug_exposure WHERE person_id  = '51' AND drug_concept_id  = '45892510' AND drug_source_value  = '90651') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 53: DRUG_EXPOSURE - Record from inpatient_confinement with a procedure code that maps to a drug
INSERT INTO optum_extended_cdm_test.test_results SELECT 53 AS id, 'DRUG_EXPOSURE - Record from inpatient_confinement with a procedure code that maps to a drug' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.drug_exposure WHERE person_id  = '53' AND drug_concept_id  = '45892510' AND drug_source_value  = '90651') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 55: LOCATION - Person location test (SES)
INSERT INTO optum_extended_cdm_test.test_results SELECT 55 AS id, 'LOCATION - Person location test (SES)' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.location WHERE location_source_value  = 'PA') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 56: LOCATION - Provider location test (SES)
INSERT INTO optum_extended_cdm_test.test_results SELECT 56 AS id, 'LOCATION - Provider location test (SES)' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.location WHERE location_source_value  = 'VA') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 57: MEASUREMENT - Patient has lab_result with 0 rslt_nbr and string rslt_txt
INSERT INTO optum_extended_cdm_test.test_results SELECT 57 AS id, 'MEASUREMENT - Patient has lab_result with 0 rslt_nbr and string rslt_txt' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '57' AND value_as_number  = '0' AND measurement_source_value  = '22962-5') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 59: MEASUREMENT - Patient has lab_result with non-zero rslt_nbr and string rslt_txt
INSERT INTO optum_extended_cdm_test.test_results SELECT 59 AS id, 'MEASUREMENT - Patient has lab_result with non-zero rslt_nbr and string rslt_txt' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '59' AND value_as_number  = '111.0' AND measurement_source_value  = '22962-5') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 61: MEASUREMENT - Patient has lab_result with both loinc_cd and proc_cd values that map to a Measurement record based on loinc_cd
INSERT INTO optum_extended_cdm_test.test_results SELECT 61 AS id, 'MEASUREMENT - Patient has lab_result with both loinc_cd and proc_cd values that map to a Measurement record based on loinc_cd' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '61' AND measurement_source_value  = '22962-5') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 61 AS id, 'MEASUREMENT - Patient has lab_result with both loinc_cd and proc_cd values that map to a Measurement record based on loinc_cd' AS description, 'Expect No measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '61' AND measurement_source_value  = '87517') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 63: MEASUREMENT - Patient has diag source codes mapping to domain Measurement and visit_place_of_service of IP does not get mapped to Condition
INSERT INTO optum_extended_cdm_test.test_results SELECT 63 AS id, 'MEASUREMENT - Patient has diag source codes mapping to domain Measurement and visit_place_of_service of IP does not get mapped to Condition' AS description, 'Expect No condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '63' AND condition_source_value  = 'V8271') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 63 AS id, 'MEASUREMENT - Patient has diag source codes mapping to domain Measurement and visit_place_of_service of IP does not get mapped to Condition' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '63' AND measurement_concept_id  = '4237017') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 63 AS id, 'MEASUREMENT - Patient has diag source codes mapping to domain Measurement and visit_place_of_service of IP does not get mapped to Condition' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '63' AND visit_concept_id  = '9201') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 65: MEASUREMENT - Patient has diag source codes mapping to domain Measurement and visit_place_of_service of OP does not get mapped to Condition
INSERT INTO optum_extended_cdm_test.test_results SELECT 65 AS id, 'MEASUREMENT - Patient has diag source codes mapping to domain Measurement and visit_place_of_service of OP does not get mapped to Condition' AS description, 'Expect No condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '65' AND condition_source_value  = 'V8271') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 65 AS id, 'MEASUREMENT - Patient has diag source codes mapping to domain Measurement and visit_place_of_service of OP does not get mapped to Condition' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '65' AND measurement_concept_id  = '4237017') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 65 AS id, 'MEASUREMENT - Patient has diag source codes mapping to domain Measurement and visit_place_of_service of OP does not get mapped to Condition' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '65' AND visit_concept_id  = '9202') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 67: MEASUREMENT - Patient has measurement value (sourced from lab_result rslt_nbr)
INSERT INTO optum_extended_cdm_test.test_results SELECT 67 AS id, 'MEASUREMENT - Patient has measurement value (sourced from lab_result rslt_nbr)' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '67' AND measurement_concept_id  = '3012939' AND value_as_number  = '1000') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 69: MEASUREMENT - Patient has procedure code in MEDICAL_CLAIMS that maps to measurement
INSERT INTO optum_extended_cdm_test.test_results SELECT 69 AS id, 'MEASUREMENT - Patient has procedure code in MEDICAL_CLAIMS that maps to measurement' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '69' AND measurement_concept_id  = '2213127') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 71: Patient has LOW result text
INSERT INTO optum_extended_cdm_test.test_results SELECT 71 AS id, 'Patient has LOW result text' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '71') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 73: Patient has HIGH result text
INSERT INTO optum_extended_cdm_test.test_results SELECT 73 AS id, 'Patient has HIGH result text' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '73') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 75: Patient has unit of measurement
INSERT INTO optum_extended_cdm_test.test_results SELECT 75 AS id, 'Patient has unit of measurement' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '75' AND unit_concept_id  = '9472') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 77: Patient has normal range values
INSERT INTO optum_extended_cdm_test.test_results SELECT 77 AS id, 'Patient has normal range values' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '77' AND range_low  = '10' AND range_high  = '100') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 79: MEASUREMENT - Patient has procedure code in MED_PROCEDURE that maps to measurement
INSERT INTO optum_extended_cdm_test.test_results SELECT 79 AS id, 'MEASUREMENT - Patient has procedure code in MED_PROCEDURE that maps to measurement' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '79' AND measurement_concept_id  = '2213127') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 81: MEASUREMENT - Patient has procedure code in inpatient_confinement that maps to measurement
INSERT INTO optum_extended_cdm_test.test_results SELECT 81 AS id, 'MEASUREMENT - Patient has procedure code in inpatient_confinement that maps to measurement' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '81' AND measurement_concept_id  = '2213127') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 83: MEASUREMENT - Patient has measurement source value of 000
INSERT INTO optum_extended_cdm_test.test_results SELECT 83 AS id, 'MEASUREMENT - Patient has measurement source value of 000' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.measurement WHERE person_id  = '83' AND measurement_source_value  = '000') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 85: OBSERVATION_PERIOD - Tests if 2 enrollment durations (where second is subsumed by the first) results in a single observation period
INSERT INTO optum_extended_cdm_test.test_results SELECT 85 AS id, 'OBSERVATION_PERIOD - Tests if 2 enrollment durations (where second is subsumed by the first) results in a single observation period' AS description, 'Expect 1 observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation_period WHERE person_id  = '85') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 85 AS id, 'OBSERVATION_PERIOD - Tests if 2 enrollment durations (where second is subsumed by the first) results in a single observation period' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation_period WHERE person_id  = '85' AND observation_period_start_date  = '2000-05-01' AND observation_period_end_date  = '2008-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 86: OBSERVATION_PERIOD - Tests if 2 enrollment durations (where second is within 30 days of first) results in a single observation period
INSERT INTO optum_extended_cdm_test.test_results SELECT 86 AS id, 'OBSERVATION_PERIOD - Tests if 2 enrollment durations (where second is within 30 days of first) results in a single observation period' AS description, 'Expect 1 observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation_period WHERE person_id  = '86') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 86 AS id, 'OBSERVATION_PERIOD - Tests if 2 enrollment durations (where second is within 30 days of first) results in a single observation period' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation_period WHERE person_id  = '86' AND observation_period_start_date  = '2000-05-01' AND observation_period_end_date  = '2011-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 87: OBSERVATION_PERIOD - Tests if 2 enrollment durations (where second starts > 33 days after first) results in two observation periods
INSERT INTO optum_extended_cdm_test.test_results SELECT 87 AS id, 'OBSERVATION_PERIOD - Tests if 2 enrollment durations (where second starts > 33 days after first) results in two observation periods' AS description, 'Expect 2 observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation_period WHERE person_id  = '87') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 87 AS id, 'OBSERVATION_PERIOD - Tests if 2 enrollment durations (where second starts > 33 days after first) results in two observation periods' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation_period WHERE person_id  = '87' AND observation_period_start_date  = '2001-04-01' AND observation_period_end_date  = '2006-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 87 AS id, 'OBSERVATION_PERIOD - Tests if 2 enrollment durations (where second starts > 33 days after first) results in two observation periods' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation_period WHERE person_id  = '87' AND observation_period_start_date  = '2000-05-01' AND observation_period_end_date  = '2000-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 88: OBSERVATION - Patient has series of observations in lab_results that translates to Observation records.
INSERT INTO optum_extended_cdm_test.test_results SELECT 88 AS id, 'OBSERVATION - Patient has series of observations in lab_results that translates to Observation records.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation WHERE person_id  = '88' AND observation_source_value  = '76345-8') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 88 AS id, 'OBSERVATION - Patient has series of observations in lab_results that translates to Observation records.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation WHERE person_id  = '88' AND observation_source_value  = '75415-0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 90: OBSERVATION - Patient has diag source codes mapping to domain Observation and visit_place_of_service of IP does not get mapped to Condition
INSERT INTO optum_extended_cdm_test.test_results SELECT 90 AS id, 'OBSERVATION - Patient has diag source codes mapping to domain Observation and visit_place_of_service of IP does not get mapped to Condition' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '90' AND visit_concept_id  = '9201') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 90 AS id, 'OBSERVATION - Patient has diag source codes mapping to domain Observation and visit_place_of_service of IP does not get mapped to Condition' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation WHERE person_id  = '90' AND observation_source_value  = 'E001') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 92: OBSERVATION - Patient has diag source codes mapping to domain Observation and visit_place_of_service of OP does not get mapped to Condition
INSERT INTO optum_extended_cdm_test.test_results SELECT 92 AS id, 'OBSERVATION - Patient has diag source codes mapping to domain Observation and visit_place_of_service of OP does not get mapped to Condition' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '92' AND visit_concept_id  = '9202') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 92 AS id, 'OBSERVATION - Patient has diag source codes mapping to domain Observation and visit_place_of_service of OP does not get mapped to Condition' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation WHERE person_id  = '92' AND observation_source_value  = 'E001') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 94: OBSERVATION - Patient has proc codes in medical_claims mapping to domain Observation
INSERT INTO optum_extended_cdm_test.test_results SELECT 94 AS id, 'OBSERVATION - Patient has proc codes in medical_claims mapping to domain Observation' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '94' AND visit_concept_id  = '9201') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 94 AS id, 'OBSERVATION - Patient has proc codes in medical_claims mapping to domain Observation' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation WHERE person_id  = '94' AND observation_source_value  = 'A0210') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 96: OBSERVATION - Patient has proc codes in inpatient_confinement mapping to domain Observation
INSERT INTO optum_extended_cdm_test.test_results SELECT 96 AS id, 'OBSERVATION - Patient has proc codes in inpatient_confinement mapping to domain Observation' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '96' AND visit_concept_id  = '9201') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 96 AS id, 'OBSERVATION - Patient has proc codes in inpatient_confinement mapping to domain Observation' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.observation WHERE person_id  = '96' AND observation_source_value  = 'A0210') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 98: PAYER_PLAN_PERIOD - Tests when patient has multiple payers active in the same time window.
INSERT INTO optum_extended_cdm_test.test_results SELECT 98 AS id, 'PAYER_PLAN_PERIOD - Tests when patient has multiple payers active in the same time window.' AS description, 'Expect 2 payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '98') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 98 AS id, 'PAYER_PLAN_PERIOD - Tests when patient has multiple payers active in the same time window.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '98' AND payer_plan_period_start_date  = '2000-10-01' AND payer_plan_period_end_date  = '2000-10-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 99: PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 99 AS id, 'PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '99' AND payer_concept_id  = '281' AND payer_source_value  = 'MCR0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 100: PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 100 AS id, 'PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '100' AND payer_concept_id  = '327' AND payer_source_value  = 'COM0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 101: PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 101 AS id, 'PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '101' AND payer_concept_id  = '276' AND payer_source_value  = 'COM3') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 102: PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 102 AS id, 'PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '102' AND payer_concept_id  = '275' AND payer_source_value  = 'COM1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 103: PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 103 AS id, 'PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '103' AND payer_concept_id  = '0' AND payer_source_value  = 'UNK0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 104: PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 104 AS id, 'PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '104' AND payer_concept_id  = '276' AND payer_source_value  = 'NONE2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 105: PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 105 AS id, 'PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '105' AND plan_source_value  = 'HMO3') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 106: PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 106 AS id, 'PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '106' AND plan_source_value  = 'PPO3') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 107: PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 107 AS id, 'PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '107' AND plan_source_value  = 'OTH3') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 108: PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.
INSERT INTO optum_extended_cdm_test.test_results SELECT 108 AS id, 'PAYER_PLAN_PERIOD - Checks the PAYER_PLAN_SOURCE_VALUE mapping for all combos of source values.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '108' AND plan_source_value  = 'POS3') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 109: PAYER_PLAN_PERIOD - Patient has multiple payer plan periods that should be collapsed based on PAYER_SOURCE_VALUE and PLAN_SOURCE_VALUE
INSERT INTO optum_extended_cdm_test.test_results SELECT 109 AS id, 'PAYER_PLAN_PERIOD - Patient has multiple payer plan periods that should be collapsed based on PAYER_SOURCE_VALUE and PLAN_SOURCE_VALUE' AS description, 'Expect 1 payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.payer_plan_period WHERE person_id  = '109') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 110: PERSON - A person defined with year of birth is 0, id is person_id
INSERT INTO optum_extended_cdm_test.test_results SELECT 110 AS id, 'PERSON - A person defined with year of birth is 0, id is person_id' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '110') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 111: PERSON - A person defined with year of birth > 1 year after the earliest coverage start from patient history
INSERT INTO optum_extended_cdm_test.test_results SELECT 111 AS id, 'PERSON - A person defined with year of birth > 1 year after the earliest coverage start from patient history' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '111') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 112: PERSON - Person with a Gender source value of M
INSERT INTO optum_extended_cdm_test.test_results SELECT 112 AS id, 'PERSON - Person with a Gender source value of M' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '112' AND gender_concept_id  = '8507') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 113: PERSON - Person with a Gender source value of F
INSERT INTO optum_extended_cdm_test.test_results SELECT 113 AS id, 'PERSON - Person with a Gender source value of F' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '113' AND gender_concept_id  = '8532') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 114: PERSON - Person with a Gender source value of U
INSERT INTO optum_extended_cdm_test.test_results SELECT 114 AS id, 'PERSON - Person with a Gender source value of U' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '114') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 115: PERSON - Person with 2 YOBs that are have a MIN/MAX(YOB) > 2 years apart
INSERT INTO optum_extended_cdm_test.test_results SELECT 115 AS id, 'PERSON - Person with 2 YOBs that are have a MIN/MAX(YOB) > 2 years apart' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '115') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 116: PERSON - Person who flips gender across different OPs
INSERT INTO optum_extended_cdm_test.test_results SELECT 116 AS id, 'PERSON - Person who flips gender across different OPs' AS description, 'Expect No person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '116') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 117: PERSON - Month of birth test: Month should be mapped
INSERT INTO optum_extended_cdm_test.test_results SELECT 117 AS id, 'PERSON - Month of birth test: Month should be mapped' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '117' AND month_of_birth  = '3') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 118: PERSON - Month of birth test: Month should NOT be mapped
INSERT INTO optum_extended_cdm_test.test_results SELECT 118 AS id, 'PERSON - Month of birth test: Month should NOT be mapped' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '118' AND month_of_birth  IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 119: PERSON - Day of birth test: Day should be mapped
INSERT INTO optum_extended_cdm_test.test_results SELECT 119 AS id, 'PERSON - Day of birth test: Day should be mapped' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '119' AND day_of_birth  = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 120: PERSON - Day of birth test: Day should NOT be mapped
INSERT INTO optum_extended_cdm_test.test_results SELECT 120 AS id, 'PERSON - Day of birth test: Day should NOT be mapped' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '120' AND day_of_birth  IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 121: PERSON - Person who has Asian race
INSERT INTO optum_extended_cdm_test.test_results SELECT 121 AS id, 'PERSON - Person who has Asian race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '121' AND race_concept_id  = '8515' AND ethnicity_concept_id  = '38003564') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 122: PERSON - Person who has Black race
INSERT INTO optum_extended_cdm_test.test_results SELECT 122 AS id, 'PERSON - Person who has Black race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '122' AND race_concept_id  = '8516' AND ethnicity_concept_id  = '38003564') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 123: PERSON - Person who has White race
INSERT INTO optum_extended_cdm_test.test_results SELECT 123 AS id, 'PERSON - Person who has White race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '123' AND race_concept_id  = '8527' AND ethnicity_concept_id  = '38003564') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 124: PERSON - Person who has Unknown race
INSERT INTO optum_extended_cdm_test.test_results SELECT 124 AS id, 'PERSON - Person who has Unknown race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '124' AND race_concept_id  = '0' AND ethnicity_concept_id  = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 125: PERSON - Person who has Hispanic ethnicity
INSERT INTO optum_extended_cdm_test.test_results SELECT 125 AS id, 'PERSON - Person who has Hispanic ethnicity' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.person WHERE person_id  = '125' AND race_concept_id  = '0' AND ethnicity_concept_id  = '38003563') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 126: PROCEDURE_OCCURRENCE - Patient has 2 medical records which have the same proc code listed in proc position 1-3, with repeated PROC_CD in both records.
INSERT INTO optum_extended_cdm_test.test_results SELECT 126 AS id, 'PROCEDURE_OCCURRENCE - Patient has 2 medical records which have the same proc code listed in proc position 1-3, with repeated PROC_CD in both records.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '126' AND procedure_concept_id  = '2211331') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 126 AS id, 'PROCEDURE_OCCURRENCE - Patient has 2 medical records which have the same proc code listed in proc position 1-3, with repeated PROC_CD in both records.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '126' AND procedure_concept_id  = '43527998') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 128: PROCEDURE_OCCURRENCE - Patient has medical records which have some valid and invalid formatted PROC codes.
INSERT INTO optum_extended_cdm_test.test_results SELECT 128 AS id, 'PROCEDURE_OCCURRENCE - Patient has medical records which have some valid and invalid formatted PROC codes.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '128' AND procedure_concept_id  = '43527998') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 128 AS id, 'PROCEDURE_OCCURRENCE - Patient has medical records which have some valid and invalid formatted PROC codes.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '128' AND procedure_concept_id  = '0' AND procedure_source_value  = '2') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 130: PROCEDURE_OCCURRENCE - Patient has a series of 3 inpatient visits with same dates and procedure codes in separate records.
INSERT INTO optum_extended_cdm_test.test_results SELECT 130 AS id, 'PROCEDURE_OCCURRENCE - Patient has a series of 3 inpatient visits with same dates and procedure codes in separate records.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '130' AND procedure_concept_id  = '2211331') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 130 AS id, 'PROCEDURE_OCCURRENCE - Patient has a series of 3 inpatient visits with same dates and procedure codes in separate records.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '130' AND procedure_concept_id  = '43527998') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 132: Patient has series of procedures within a visit that should use the VISIT_END for PROC or FST_DT for PROC_CD to determine the procedure date.
INSERT INTO optum_extended_cdm_test.test_results SELECT 132 AS id, 'Patient has series of procedures within a visit that should use the VISIT_END for PROC or FST_DT for PROC_CD to determine the procedure date.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '132' AND procedure_concept_id  = '43527998' AND procedure_date  = '2013-07-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 132 AS id, 'Patient has series of procedures within a visit that should use the VISIT_END for PROC or FST_DT for PROC_CD to determine the procedure date.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '132' AND procedure_concept_id  = '2211331' AND procedure_date  = '2013-07-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 134: PROCEDURE_OCCURRENCE - Patient has multiple Medical rows with placeholders for procedure codes.
INSERT INTO optum_extended_cdm_test.test_results SELECT 134 AS id, 'PROCEDURE_OCCURRENCE - Patient has multiple Medical rows with placeholders for procedure codes.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '134' AND procedure_concept_id  = '43527998') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 134 AS id, 'PROCEDURE_OCCURRENCE - Patient has multiple Medical rows with placeholders for procedure codes.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '134' AND procedure_concept_id  = '2211331') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 136: PROCEDURE_OCCURRENCE - Patient has Medical records with a diag that maps to 2 SNOMED concepts, and single procedure.
INSERT INTO optum_extended_cdm_test.test_results SELECT 136 AS id, 'PROCEDURE_OCCURRENCE - Patient has Medical records with a diag that maps to 2 SNOMED concepts, and single procedure.' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '136' AND condition_concept_id  = '443727' AND condition_source_value  = '24910') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 136 AS id, 'PROCEDURE_OCCURRENCE - Patient has Medical records with a diag that maps to 2 SNOMED concepts, and single procedure.' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '136' AND condition_concept_id  = '195771' AND condition_source_value  = '24910') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 136 AS id, 'PROCEDURE_OCCURRENCE - Patient has Medical records with a diag that maps to 2 SNOMED concepts, and single procedure.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '136' AND procedure_concept_id  = '2211331') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 138: PROCEDURE_OCCURRENCE - Patient has 2 medical records with 2 different procedures, but only 1 record has diag specified.
INSERT INTO optum_extended_cdm_test.test_results SELECT 138 AS id, 'PROCEDURE_OCCURRENCE - Patient has 2 medical records with 2 different procedures, but only 1 record has diag specified.' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '138' AND condition_concept_id  = '141095') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 138 AS id, 'PROCEDURE_OCCURRENCE - Patient has 2 medical records with 2 different procedures, but only 1 record has diag specified.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '138' AND procedure_concept_id  = '43527998') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 138 AS id, 'PROCEDURE_OCCURRENCE - Patient has 2 medical records with 2 different procedures, but only 1 record has diag specified.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '138' AND procedure_concept_id  = '2211331') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 140: PROCEDURE_OCCURRENCE - Patient has diag source codes mapping to domain Procedure and visit_place_of_service of IP does not get mapped to Condition
INSERT INTO optum_extended_cdm_test.test_results SELECT 140 AS id, 'PROCEDURE_OCCURRENCE - Patient has diag source codes mapping to domain Procedure and visit_place_of_service of IP does not get mapped to Condition' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '140' AND procedure_concept_id  = '4180248') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 140 AS id, 'PROCEDURE_OCCURRENCE - Patient has diag source codes mapping to domain Procedure and visit_place_of_service of IP does not get mapped to Condition' AS description, 'Expect No condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '140' AND condition_source_value  = 'V5789') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 140 AS id, 'PROCEDURE_OCCURRENCE - Patient has diag source codes mapping to domain Procedure and visit_place_of_service of IP does not get mapped to Condition' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '140' AND visit_concept_id  = '9201') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 142: PROCEDURE_OCCURRENCE - Patient has diag source codes mapping to domain Procedure and visit_place_of_service of OP does not get mapped to Condition
INSERT INTO optum_extended_cdm_test.test_results SELECT 142 AS id, 'PROCEDURE_OCCURRENCE - Patient has diag source codes mapping to domain Procedure and visit_place_of_service of OP does not get mapped to Condition' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '142' AND procedure_concept_id  = '4180248') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 142 AS id, 'PROCEDURE_OCCURRENCE - Patient has diag source codes mapping to domain Procedure and visit_place_of_service of OP does not get mapped to Condition' AS description, 'Expect No condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.condition_occurrence WHERE person_id  = '142' AND condition_source_value  = 'V5789') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 142 AS id, 'PROCEDURE_OCCURRENCE - Patient has diag source codes mapping to domain Procedure and visit_place_of_service of OP does not get mapped to Condition' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '142' AND visit_concept_id  = '9202') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 144: Patient has procedure from a lab result proc_cd
INSERT INTO optum_extended_cdm_test.test_results SELECT 144 AS id, 'Patient has procedure from a lab result proc_cd' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.procedure_occurrence WHERE person_id  = '144' AND procedure_concept_id  = '2211331') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 146: PROVIDER - Creates a provider entry from record in native PROVIDER table.
INSERT INTO optum_extended_cdm_test.test_results SELECT 146 AS id, 'PROVIDER - Creates a provider entry from record in native PROVIDER table.' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.provider WHERE provider_source_value  = '146') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 147: PROVIDER - Creates a provider entry from record in native PROVIDER table, specialty in taxonomy1.
INSERT INTO optum_extended_cdm_test.test_results SELECT 147 AS id, 'PROVIDER - Creates a provider entry from record in native PROVIDER table, specialty in taxonomy1.' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.provider WHERE specialty_concept_id  = '38003640' AND provider_source_value  = '147' AND specialty_source_value  = '103TC2200X') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 148: PROVIDER - Creates a provider entry from record in native PROVIDER table, specialty in taxonomy2.
INSERT INTO optum_extended_cdm_test.test_results SELECT 148 AS id, 'PROVIDER - Creates a provider entry from record in native PROVIDER table, specialty in taxonomy2.' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.provider WHERE specialty_concept_id  = '38004510' AND provider_source_value  = '148' AND specialty_source_value  = '207PE0004X') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 149: VISIT_OCCURRENCE - Multiple IP admission claims on the same day with different pat_planids, should get a single IP visit occurrence.
INSERT INTO optum_extended_cdm_test.test_results SELECT 149 AS id, 'VISIT_OCCURRENCE - Multiple IP admission claims on the same day with different pat_planids, should get a single IP visit occurrence.' AS description, 'Expect 2 visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '149' AND visit_detail_concept_id  = '8717' AND visit_detail_start_date  = '2013-07-01') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 149 AS id, 'VISIT_OCCURRENCE - Multiple IP admission claims on the same day with different pat_planids, should get a single IP visit occurrence.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '149' AND visit_concept_id  = '9201' AND visit_start_date  = '2013-07-01' AND visit_end_date  = '2013-07-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 151: VISIT_OCCURRENCE - Inpatient Visit Occurrence for a patient with a single medical diagnosis.
INSERT INTO optum_extended_cdm_test.test_results SELECT 151 AS id, 'VISIT_OCCURRENCE - Inpatient Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '151' AND visit_concept_id  = '9201' AND visit_start_date  = '2014-03-01' AND visit_end_date  = '2014-03-13') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 151 AS id, 'VISIT_OCCURRENCE - Inpatient Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '151' AND visit_detail_concept_id  = '8717' AND visit_detail_start_date  = '2014-03-01' AND visit_detail_end_date  = '2014-03-13') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 153: VISIT_OCCURRENCE - Outpatient Visit Occurrence for a patient with a single medical diagnosis.
INSERT INTO optum_extended_cdm_test.test_results SELECT 153 AS id, 'VISIT_OCCURRENCE - Outpatient Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '153' AND visit_concept_id  = '9202') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 153 AS id, 'VISIT_OCCURRENCE - Outpatient Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '153' AND visit_detail_concept_id  = '581477') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 155: VISIT_OCCURRENCE - Emergency Room Visit Occurrence for a patient with a single medical diagnosis.
INSERT INTO optum_extended_cdm_test.test_results SELECT 155 AS id, 'VISIT_OCCURRENCE - Emergency Room Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '155' AND visit_concept_id  = '9203') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 155 AS id, 'VISIT_OCCURRENCE - Emergency Room Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '155' AND visit_detail_concept_id  = '8870') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 157: Non-hospital institution Visit Occurrence for a patient with a single medical diagnosis.
INSERT INTO optum_extended_cdm_test.test_results SELECT 157 AS id, 'Non-hospital institution Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '157' AND visit_concept_id  = '42898160') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 157 AS id, 'Non-hospital institution Visit Occurrence for a patient with a single medical diagnosis.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '157' AND visit_detail_concept_id  = '8615') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 159: Patient has a series of diagnoses that fall outside of their Observation Period but visit is still created.
INSERT INTO optum_extended_cdm_test.test_results SELECT 159 AS id, 'Patient has a series of diagnoses that fall outside of their Observation Period but visit is still created.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '159' AND visit_concept_id  = '9202' AND visit_start_date  = '2009-07-01' AND visit_end_date  = '2009-07-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 159 AS id, 'Patient has a series of diagnoses that fall outside of their Observation Period but visit is still created.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '159' AND visit_detail_concept_id  = '8756' AND visit_detail_start_date  = '2009-07-01' AND visit_detail_end_date  = '2009-07-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 161: Patient has a series of visits that are linked by foreign key
INSERT INTO optum_extended_cdm_test.test_results SELECT 161 AS id, 'Patient has a series of visits that are linked by foreign key' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '161' AND preceding_visit_occurrence_id  = (SELECT visit_occurrence_id FROM optum_extended_cdm_test.visit_occurrence WHERE person_id = '161' AND visit_start_date = '2012-11-01')) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 161 AS id, 'Patient has a series of visits that are linked by foreign key' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '161' AND preceding_visit_detail_id  = (SELECT visit_detail_id FROM optum_extended_cdm_test.visit_detail WHERE person_id = '161' AND visit_detail_start_date = '2012-11-01')) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 163: Patient has a series of inpatient_confinement records, with an outpatient record in the middle
INSERT INTO optum_extended_cdm_test.test_results SELECT 163 AS id, 'Patient has a series of inpatient_confinement records, with an outpatient record in the middle' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '163' AND visit_detail_start_date  = '2013-08-21' AND visit_detail_end_date  = '2013-08-21') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 163 AS id, 'Patient has a series of inpatient_confinement records, with an outpatient record in the middle' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '163' AND visit_detail_start_date  = '2013-08-11' AND visit_detail_end_date  = '2013-08-22') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 163 AS id, 'Patient has a series of inpatient_confinement records, with an outpatient record in the middle' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '163' AND visit_detail_start_date  = '2015-02-11' AND visit_detail_end_date  = '2015-02-15') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 163 AS id, 'Patient has a series of inpatient_confinement records, with an outpatient record in the middle' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '163' AND visit_start_date  = '2013-08-11' AND visit_end_date  = '2013-08-22') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 163 AS id, 'Patient has a series of inpatient_confinement records, with an outpatient record in the middle' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '163' AND visit_start_date  = '2015-02-11' AND visit_end_date  = '2015-02-15') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 165: VISIT_OCCURRENCE - Emergency Room Visit Occurrence occurring on the first day of an inpatient confinement.
INSERT INTO optum_extended_cdm_test.test_results SELECT 165 AS id, 'VISIT_OCCURRENCE - Emergency Room Visit Occurrence occurring on the first day of an inpatient confinement.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_occurrence WHERE person_id  = '165' AND visit_concept_id  = '262' AND visit_start_date  = '2013-09-01' AND visit_end_date  = '2013-09-22') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO optum_extended_cdm_test.test_results SELECT 165 AS id, 'VISIT_OCCURRENCE - Emergency Room Visit Occurrence occurring on the first day of an inpatient confinement.' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '165' AND visit_detail_concept_id  = '8870') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 167: VISIT_DETAIL - Record from medical claims creates a record in visit_detail
INSERT INTO optum_extended_cdm_test.test_results SELECT 167 AS id, 'VISIT_DETAIL - Record from medical claims creates a record in visit_detail' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '167' AND visit_detail_concept_id  = '38003620' AND visit_detail_start_date  = '2011-08-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 169: VISIT_DETAIL - Record from inpatient_confinement creates a record in visit_detail
INSERT INTO optum_extended_cdm_test.test_results SELECT 169 AS id, 'VISIT_DETAIL - Record from inpatient_confinement creates a record in visit_detail' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '169' AND visit_detail_concept_id  = '8717' AND visit_detail_start_date  = '2013-08-11' AND visit_detail_end_date  = '2013-08-22') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 171: VISIT_DETAIL - Record in rx_claims creates a record in visit_detail, mail_ind
INSERT INTO optum_extended_cdm_test.test_results SELECT 171 AS id, 'VISIT_DETAIL - Record in rx_claims creates a record in visit_detail, mail_ind' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '171' AND visit_detail_concept_id  = '581458' AND visit_detail_start_date  = '2012-02-02') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 173: VISIT_DETAIL - Record in rx_claims creates a record in visit_detail, spclt_ind
INSERT INTO optum_extended_cdm_test.test_results SELECT 173 AS id, 'VISIT_DETAIL - Record in rx_claims creates a record in visit_detail, spclt_ind' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '173' AND visit_detail_concept_id  = '38004348' AND visit_detail_start_date  = '2012-02-02') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 175: VISIT_DETAIL - Record in rx_claims with days_sup < 0 should set visit_detail_end_date = fill_dt
INSERT INTO optum_extended_cdm_test.test_results SELECT 175 AS id, 'VISIT_DETAIL - Record in rx_claims with days_sup < 0 should set visit_detail_end_date = fill_dt' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '175' AND visit_detail_concept_id  = '581458' AND visit_detail_start_date  = '2012-02-03' AND visit_detail_end_date  = '2012-02-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 177: VISIT_DETAIL - Record in rx_claims with days_sup > 365 should set visit_detail_end_date = fill_dt
INSERT INTO optum_extended_cdm_test.test_results SELECT 177 AS id, 'VISIT_DETAIL - Record in rx_claims with days_sup > 365 should set visit_detail_end_date = fill_dt' AS description, 'Expect visit_detail' AS test, CASE WHEN (SELECT COUNT(*) FROM optum_extended_cdm_test.visit_detail WHERE person_id  = '177' AND visit_detail_concept_id  = '581458' AND visit_detail_start_date  = '2012-02-04' AND visit_detail_end_date  = '2012-02-04') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;