CREATE TABLE drug_claims
(
   awp       float8,
   boe       char(1),
   cap       char(1),
   cob       float8,
   coins     float8,
   copay     float8,
   dawind    char(2),
   daysupp   smallint,
   deaclas   char(1),
   deduct    float8,
   dispfee   float8,
   dobyr     smallint,
   drugcovg  char(1),
   enrolid   bigint,
   generid   integer,
   genind    char(1),
   ingcost   float8,
   maintin   char(1),
   mas       char(1),
   mcasenum  varchar(16),
   medicare  char(1),
   metqty    float8,
   mhsacovg  char(1),
   ndcnum    varchar(11),
   netpay    float8,
   pay       float8,
   pddate    date,
   pharmid   varchar(16),
   plantyp   smallint,
   qty       integer,
   refill    smallint,
   seqnum    bigint,
   sex       char(1),
   stdrace   char(1),
   svcdate   date,
   thercls   smallint,
   thergrp   char(2),
   version   char(2),
   year      smallint,
   _gpi      varchar(14)
);



CREATE TABLE enrollment_detail
(
   boe       char(1),
   cap       char(1),
   dobyr     smallint,
   drugcovg  char(1),
   dtend     date,
   dtstart   date,
   enrolid   bigint,
   mas       char(1),
   mcasenum  varchar(16),
   medicare  char(1),
   memdays   smallint,
   mhsacovg  char(1),
   plantyp   smallint,
   seqnum    bigint,
   sex       char(1),
   stdrace   char(1),
   version   char(2),
   year      smallint
);



CREATE TABLE enrollment_summary
(
   boe       char(1),
   cap       char(1),
   dobyr     smallint,
   drugcovg  char(1),
   enrind1   smallint,
   enrind10  smallint,
   enrind11  smallint,
   enrind12  smallint,
   enrind2   smallint,
   enrind3   smallint,
   enrind4   smallint,
   enrind5   smallint,
   enrind6   smallint,
   enrind7   smallint,
   enrind8   smallint,
   enrind9   smallint,
   enrmon    smallint,
   enrolid   bigint,
   mas       char(1),
   mcasenum  varchar(16),
   medicare  char(1),
   memday1   smallint,
   memday10  smallint,
   memday11  smallint,
   memday12  smallint,
   memday2   smallint,
   memday3   smallint,
   memday4   smallint,
   memday5   smallint,
   memday6   smallint,
   memday7   smallint,
   memday8   smallint,
   memday9   smallint,
   memdays   smallint,
   mhsacovg  char(1),
   plntyp1   smallint,
   plntyp10  smallint,
   plntyp11  smallint,
   plntyp12  smallint,
   plntyp2   smallint,
   plntyp3   smallint,
   plntyp4   smallint,
   plntyp5   smallint,
   plntyp6   smallint,
   plntyp7   smallint,
   plntyp8   smallint,
   plntyp9   smallint,
   seqnum    bigint,
   sex       char(1),
   stdrace   char(1),
   version   char(2),
   year      smallint
);



CREATE TABLE facility_header
(
   billtyp   char(3),
   boe       char(1),
   cap       char(1),
   caseid    integer,
   cob       float8,
   coins     float8,
   copay     float8,
   deduct    float8,
   dobyr     smallint,
   drugcovg  char(1),
   dstatus   char(2),
   dx1       char(7),
   dx2       char(7),
   dx3       char(7),
   dx4       char(7),
   dx5       char(7),
   dx6       char(7),
   dx7       char(7),
   dx8       char(7),
   dx9       char(7),
   dxver     char(1),
   enrolid   bigint,
   fachdid   bigint,
   mas       char(1),
   mcasenum  varchar(16),
   mdc       char(2),
   medicare  char(1),
   mhsacovg  char(1),
   netpay    float8,
   pddate    date,
   plantyp   smallint,
   poadx1    char(1),
   poadx2    char(1),
   poadx3    char(1),
   poadx4    char(1),
   poadx5    char(1),
   poadx6    char(1),
   poadx7    char(1),
   poadx8    char(1),
   poadx9    char(1),
   proc1     char(7),
   proc2     char(7),
   proc3     char(7),
   proc4     char(7),
   proc5     char(7),
   proc6     char(7),
   prov_id   varchar(16),
   seqnum    bigint,
   sex       char(1),
   stdplac   smallint,
   stdprov   smallint,
   stdrace   char(1),
   svcdate   date,
   tsvcdat   date,
   version   char(2),
   year      smallint,
   npi       varchar(10),
   msclmid   integer
);



CREATE TABLE icd9
(
   icd_key                   varchar(50),
   icd_code                  varchar(50),
   parent_icd_code           varchar(50),
   level                     smallint,
   children_count            smallint,
   children_count_recursive  smallint,
   description               varchar(250)
);



CREATE TABLE inpatient_admissions
(
   admdate   date,
   admtyp    char(1),
   boe       char(1),
   cap       char(1),
   caseid    integer,
   days      smallint,
   disdate   date,
   dobyr     smallint,
   drg       smallint,
   drugcovg  char(1),
   dstatus   char(2),
   dx1       char(7),
   dx10      char(7),
   dx11      char(7),
   dx12      char(7),
   dx13      char(7),
   dx14      char(7),
   dx15      char(7),
   dx2       char(7),
   dx3       char(7),
   dx4       char(7),
   dx5       char(7),
   dx6       char(7),
   dx7       char(7),
   dx8       char(7),
   dx9       char(7),
   dxver     char(1),
   enrolid   bigint,
   hosp_id   varchar(16),
   hospnet   float8,
   hosppay   float8,
   mas       char(1),
   mcasenum  varchar(16),
   mdc       char(2),
   medicare  char(1),
   mhsacovg  char(1),
   pddate    date,
   pdx       char(7),
   phys_id   varchar(16),
   physnet   float8,
   physpay   float8,
   plantyp   smallint,
   poapdx    char(1),
   poadx1    char(1),
   poadx2    char(1),
   poadx3    char(1),
   poadx4    char(1),
   poadx5    char(1),
   poadx6    char(1),
   poadx7    char(1),
   poadx8    char(1),
   poadx9    char(1),
   poadx10   char(1),
   poadx11   char(1),
   poadx12   char(1),
   poadx13   char(1),
   poadx14   char(1),
   poadx15   char(1),
   pproc     char(7),
   proc1     char(7),
   proc10    char(7),
   proc11    char(7),
   proc12    char(7),
   proc13    char(7),
   proc14    char(7),
   proc15    char(7),
   proc2     char(7),
   proc3     char(7),
   proc4     char(7),
   proc5     char(7),
   proc6     char(7),
   proc7     char(7),
   proc8     char(7),
   proc9     char(7),
   seqnum    bigint,
   sex       char(1),
   stdrace   char(1),
   totcob    float8,
   totcoins  float8,
   totcopay  float8,
   totded    float8,
   totnet    float8,
   totpay    float8,
   version   char(2),
   year      smallint
);



CREATE TABLE inpatient_services
(
   admdate     date,
   admtyp      char(1),
   boe         char(1),
   cap         char(1),
   caseid      integer,
   cob         float8,
   coins       float8,
   copay       float8,
   deduct      float8,
   disdate     date,
   dobyr       smallint,
   drg         smallint,
   drugcovg    char(1),
   dstatus     char(2),
   dx1         char(7),
   dx2         char(7),
   dx3         char(7),
   dx4         char(7),
   dxver       char(1),
   enrolid     bigint,
   fachdid     bigint,
   facprof     char(1),
   mas         char(1),
   mcasenum    varchar(16),
   mdc         char(2),
   medicare    char(1),
   mhsacovg    char(1),
   netpay      float8,
   pay         float8,
   pddate      date,
   pdx         char(7),
   plantyp     smallint,
   pproc       char(7),
   proc1       char(7),
   proctyp     char(1),
   prov_id     varchar(16),
   qty         integer,
   revcode     char(4),
   seqnum      bigint,
   sex         char(1),
   stdplac     smallint,
   stdprov     smallint,
   stdrace     char(1),
   stdsvc      smallint,
   svcdate     date,
   svcscat     char(5),
   tsvcdat     date,
   version     char(2),
   year        smallint,
   units       float8,
   npi         varchar(10),
   msclmid     integer,
   procmod     varchar(2),
   _svcdate    date,
   _tsvcdat    date,
   _visittype  varchar(3)
);



CREATE TABLE long_term_care
(
   boe       char(1),
   cap       char(1),
   cob       float8,
   coins     float8,
   copay     float8,
   deduct    float8,
   dobyr     smallint,
   drugcovg  char(1),
   dx1       char(7),
   dx2       char(7),
   dx3       char(7),
   dx4       char(7),
   dxver     char(1),
   enrolid   bigint,
   fachdid   bigint,
   facprof   char(1),
   mas       char(1),
   mcasenum  varchar(16),
   mdc       char(2),
   medicare  char(1),
   mhsacovg  char(1),
   netpay    float8,
   pay       float8,
   pddate    date,
   plantyp   smallint,
   proc1     char(7),
   procgrp   smallint,
   proctyp   char(1),
   prov_id   varchar(16),
   qty       integer,
   revcode   char(4),
   seqnum    bigint,
   sex       char(1),
   stdplac   smallint,
   stdprov   smallint,
   stdrace   char(1),
   stdsvc    smallint,
   svcdate   date,
   svcscat   char(5),
   tsvcdat   date,
   version   char(2),
   year      smallint,
   units     float8,
   npi       varchar(10),
   msclmid   integer,
   procmod   varchar(2)
);



CREATE TABLE outpatient_services
(
   boe         char(1),
   cap         char(1),
   cob         float8,
   coins       float8,
   copay       float8,
   deduct      float8,
   dental      char(1),
   dobyr       smallint,
   drugcovg    char(1),
   dx1         char(7),
   dx2         char(7),
   dx3         char(7),
   dx4         char(7),
   dxver       char(1),
   enrolid     bigint,
   fachdid     bigint,
   facprof     char(1),
   mas         char(1),
   mcasenum    varchar(16),
   mdc         char(2),
   medicare    char(1),
   mhsacovg    char(1),
   netpay      float8,
   pay         float8,
   pddate      date,
   plantyp     smallint,
   proc1       char(7),
   procgrp     smallint,
   proctyp     char(1),
   prov_id     varchar(16),
   qty         integer,
   revcode     char(4),
   seqnum      bigint,
   sex         char(1),
   stdplac     smallint,
   stdprov     smallint,
   stdrace     char(1),
   stdsvc      smallint,
   svcdate     date,
   svcscat     char(5),
   tsvcdat     date,
   version     char(2),
   year        smallint,
   units       float8,
   npi         varchar(10),
   msclmid     integer,
   procmod     varchar(2),
   _svcdate    date,
   _tsvcdat    date,
   _visittype  varchar(3)
);

