GRANT SELECT ON ALL TABLES IN SCHEMA public to webapi_sa;
GRANT SELECT ON ALL TABLES IN SCHEMA vocabulary to webapi_sa;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA results to webapi_sa;